/*
 * `bcrypt.ts` is a from-scratch Blowfish/Eksblowfish implementation, so what
 * needs proving is not just the wrapper but the cipher itself. The
 * known-answer vectors below were generated independently via
 * `uvx --with bcrypt python3` (Python's `bcrypt` package, C-backed, sharing
 * no code with this file) rather than typed from memory — a memorised vector
 * cost a previous agent in this tool wave a lost character, and the failure
 * only surfaced as an opaque "check failed" with no way to point at which of
 * over a thousand embedded constants was wrong. `bcryptVerify` recomputes a
 * hash from the cost and salt embedded in each external string, so a match
 * proves the whole pipeline — key schedule, salt mixing, the 64-round
 * magic-string encryption, bcrypt's own base64 — against an implementation
 * that shares nothing with this one.
 *
 * `CheckSuite` is synchronous, so every value needing `await` is resolved at
 * module load time via top-level await, same pattern `hmac.mts` documents.
 */
import type { CheckSuite } from "./harness.mts";
import {
  bcryptHash,
  bcryptVerify,
  bcryptBase64Encode,
  bcryptBase64Decode,
  parseBcryptHash,
  BCRYPT_MIN_COST,
  BCRYPT_MAX_COST,
} from "../lib/bcrypt";

/* Known-answer vectors, cost 4/5/6 for check-suite speed: password, salt+cost
   embedded in the hash string itself, generated by `bcrypt.hashpw`. */
const kEmpty = await bcryptVerify("", "$2b$04$4V9a.7rBt.ZSZ0Kh9v3wt.rMx1wS73yRxp5Ni5B.ISXyqfKo5Lnja");
const kShort = await bcryptVerify("passw0rd", "$2b$04$18AF8aAUBJtfWTOqKoPg/.yLK9G5DWCdVFmhwbGQ1ndR0vkcFpfsC");
const kCost6 = await bcryptVerify("abc", "$2b$06$EIyeC6Ps3zax8Kp9zD3l5eg0mmgPmVLDGQhic2xleNdCkJX3cyEPO");
const kLegacyPrefix = await bcryptVerify(
  "legacy-prefix",
  "$2a$05$WgfnLcTJvrzxmHr7xPF1DenNXdr7UYqZOsaDCh7g8zLlXktRFOmOW",
);
/* UTF-8 multi-byte password ("ş", "ə", "Ə" are 2 bytes each) — 9 bytes total. */
const kAzUtf8 = await bcryptVerify("şifrəƏ", "$2b$04$IEf.krfGaWhPOmAKHJ9e7ewZW6VIMhHR/3BQztjK8hjRaTikA5CBW");

/* 72-byte truncation, proven against the same known-answer hash: a 72-byte
   password, that password plus one more byte, and that password plus a long
   unrelated tail all key the cipher identically, because bytes beyond 72 are
   dropped before hashing ever starts. Changing byte 72 itself — still inside
   the limit — must change the result, which is the contrast that proves the
   boundary sits at exactly 72 and not, say, 71. */
const truncationHash = "$2b$04$5c.xsXya8jzUyr5DpTjuoeZx82eAYwaXkiov7zrJh6wiEuR.swP5e";
const kTrunc72 = await bcryptVerify("A".repeat(72), truncationHash);
const kTrunc73 = await bcryptVerify("A".repeat(72) + "X", truncationHash);
const kTrunc73LongTail = await bcryptVerify(
  "A".repeat(72) + "Z" + "this tail is well past byte 73 and must not matter at all",
  truncationHash,
);
const kByte72Matters = await bcryptVerify("A".repeat(71) + "B", truncationHash);

const rejectedLowCost = await bcryptHash("x", BCRYPT_MIN_COST - 1);
const rejectedHighCost = await bcryptHash("x", BCRYPT_MAX_COST + 1);

const freshHash = await bcryptHash("round-trip-me", 4);
const freshVerifyMatch = freshHash.ok ? await bcryptVerify("round-trip-me", freshHash.hash) : null;
const freshVerifyMismatch = freshHash.ok ? await bcryptVerify("a-different-password", freshHash.hash) : null;

const parsedMalformed = parseBcryptHash("not-a-bcrypt-hash-at-all");

/* bcrypt's base64 shares standard base64's 6-bit MSB-first packing but not
   its alphabet: byte 0 encodes to "." here, "A" in standard base64. */
const bcryptZeroByte = bcryptBase64Encode(new Uint8Array([0]));

/* Round-trip on a real, externally-generated salt (from `kEmpty` above) —
   decoding it and re-encoding the result must reproduce the exact string,
   which only holds if the alphabet and bit packing both match bcrypt's own. */
const realSaltEncoded = "4V9a.7rBt.ZSZ0Kh9v3wt.";
const realSaltDecoded = bcryptBase64Decode(realSaltEncoded);
const realSaltReencoded = realSaltDecoded.ok ? bcryptBase64Encode(realSaltDecoded.bytes) : null;

const malformedBase64 = bcryptBase64Decode("has a space and a + in it");

export const checks: CheckSuite = (check) => {
  check(
    "bcrypt: known-answer vector matches for an empty password (cost 4)",
    kEmpty.ok && kEmpty.matches,
    kEmpty.ok ? `matches=${kEmpty.matches}` : `refused: ${kEmpty.error}`,
  );

  check(
    "bcrypt: known-answer vector matches for a short password (cost 4)",
    kShort.ok && kShort.matches,
    kShort.ok ? `matches=${kShort.matches}` : `refused: ${kShort.error}`,
  );

  check(
    "bcrypt: known-answer vector matches at cost 6",
    kCost6.ok && kCost6.matches,
    kCost6.ok ? `matches=${kCost6.matches}, cost=${kCost6.cost}` : `refused: ${kCost6.error}`,
  );

  check(
    "bcrypt: known-answer vector matches under the legacy $2a$ prefix",
    kLegacyPrefix.ok && kLegacyPrefix.matches && kLegacyPrefix.version === "2a",
    kLegacyPrefix.ok
      ? `matches=${kLegacyPrefix.matches}, version=${kLegacyPrefix.version}`
      : `refused: ${kLegacyPrefix.error}`,
  );

  check(
    "bcrypt: known-answer vector matches for a UTF-8 Azerbaijani password and reports its true byte length",
    kAzUtf8.ok && kAzUtf8.matches && kAzUtf8.passwordBytes === 9,
    kAzUtf8.ok ? `matches=${kAzUtf8.matches}, passwordBytes=${kAzUtf8.passwordBytes}` : `refused: ${kAzUtf8.error}`,
  );

  check(
    "bcrypt: a 73rd byte does not change the hash — silently truncated at 72",
    kTrunc72.ok && kTrunc72.matches && kTrunc73.ok && kTrunc73.matches,
    `72-byte matches=${kTrunc72.ok ? kTrunc72.matches : kTrunc72.error}, 73-byte matches=${kTrunc73.ok ? kTrunc73.matches : kTrunc73.error}`,
  );

  check(
    "bcrypt: bytes well past 72 do not change the hash either",
    kTrunc73LongTail.ok && kTrunc73LongTail.matches,
    kTrunc73LongTail.ok ? `matches=${kTrunc73LongTail.matches}` : `refused: ${kTrunc73LongTail.error}`,
  );

  check(
    "bcrypt: changing byte 72 itself — still inside the limit — does change the hash",
    kByte72Matters.ok && !kByte72Matters.matches,
    kByte72Matters.ok ? `matches=${kByte72Matters.matches}` : `refused: ${kByte72Matters.error}`,
  );

  check(
    `bcrypt: cost below ${BCRYPT_MIN_COST} is refused with a message, not thrown`,
    !rejectedLowCost.ok && rejectedLowCost.error.length > 0,
    rejectedLowCost.ok ? "an out-of-range low cost was accepted" : "no message",
  );

  check(
    `bcrypt: cost above ${BCRYPT_MAX_COST} is refused with a message, not thrown`,
    !rejectedHighCost.ok && rejectedHighCost.error.length > 0,
    rejectedHighCost.ok ? "an out-of-range high cost was accepted" : "no message",
  );

  check(
    "bcrypt: hashing then verifying the same password round-trips to a match",
    freshHash.ok && freshVerifyMatch !== null && freshVerifyMatch.ok && freshVerifyMatch.matches,
    freshHash.ok ? `hash=${freshHash.hash}` : `hash refused: ${freshHash.error}`,
  );

  check(
    "bcrypt: verifying a fresh hash against the wrong password reports no match, not an error",
    freshVerifyMismatch !== null && freshVerifyMismatch.ok && !freshVerifyMismatch.matches,
    freshVerifyMismatch !== null && freshVerifyMismatch.ok
      ? `matches=${freshVerifyMismatch.matches}`
      : "no result to check",
  );

  check(
    "bcrypt: a malformed hash is refused with a message, not thrown",
    !parsedMalformed.ok && parsedMalformed.error.length > 0,
    parsedMalformed.ok ? "a malformed hash was parsed as valid" : "no message",
  );

  check(
    "bcrypt: its base64 alphabet differs from standard base64 — byte 0 encodes to \".\", not \"A\"",
    bcryptZeroByte[0] === ".",
    `got: ${JSON.stringify(bcryptZeroByte)}`,
  );

  check(
    "bcrypt: decoding a real externally-generated salt and re-encoding it reproduces the same string",
    realSaltDecoded.ok && realSaltDecoded.bytes.length === 16 && realSaltReencoded === realSaltEncoded,
    realSaltDecoded.ok
      ? `bytes=${realSaltDecoded.bytes.length}, reencoded=${realSaltReencoded}`
      : `refused: ${realSaltDecoded.error}`,
  );

  check(
    "bcrypt: a character outside its alphabet is refused with a message, not thrown",
    !malformedBase64.ok && malformedBase64.error.length > 0,
    malformedBase64.ok ? "an invalid character was accepted" : "no message",
  );
};
