/*
 * Generated test runner. Reads every check file in this folder (except
 * itself and `harness.mts`) and runs its `checks` export, the same way
 * camalali.com's own `scripts/verify-tools.mts` drives `scripts/tools-checks/`.
 *
 * Regenerated by `export-tools.mts` — do not hand-edit.
 */
import { readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Check, CheckSuite } from "./harness.mts";

const HERE = dirname(fileURLToPath(import.meta.url));

let passed = 0;
let failed = 0;

const check: Check = (name, condition, because) => {
  if (condition) {
    passed += 1;
    console.log(`  ok    ${name}`);
  } else {
    failed += 1;
    console.log(`  XETA  ${name} — ${because}`);
  }
};

const files = readdirSync(HERE)
  .filter((name) => name.endsWith(".mts") && name !== "harness.mts" && name !== "run.mts")
  .sort();

for (const file of files) {
  const suite = (await import(`./${file}`)) as { checks?: CheckSuite };
  if (typeof suite.checks !== "function") {
    failed += 1;
    console.log(`  XETA  ${file}: 'checks' ixrac edilməyib`);
    continue;
  }
  suite.checks(check);
}

console.log(`\n${passed} kecdi, ${failed} kecmedi (${files.length} fayl)`);
process.exit(failed === 0 ? 0 : 1);
