/*
 * The rows behind the `docker-emrleri` reference table. Shape and search live
 * in `reference.ts`; this file only supplies the terms, grouped by what a
 * visitor is doing — running a container, building an image, freeing disk
 * space — rather than by Docker's own subcommand tree.
 */
import type { ReferenceRow, ReferenceSection } from "./reference.js";

export const dockerEmrleriSections: ReferenceSection[] = [
  { id: "konteyner", label: "Konteyner" },
  { id: "sekil", label: "Şəkil" },
  { id: "compose", label: "Compose" },
  { id: "sebeke", label: "Şəbəkə və volume" },
  { id: "temizlik", label: "Yer boşaltma" },
  { id: "sazlama", label: "Sazlama" },
];

export const dockerEmrleriRows: ReferenceRow[] = [
  /* ---------- konteyner ---------- */
  {
    term: "docker run",
    note: "Şəkildən (image) yeni konteyner yaradır və işə salır. Konteyner ön planda işləyir və terminalı tutur: çıxmaq üçün Ctrl+C, arxa planda işə salmaq üçünsə -d lazımdır.",
    example: "docker run nginx:alpine",
    section: "konteyner",
    match: ["konteyner işə sal", "yeni konteyner yarat"],
  },
  {
    term: "docker run -d",
    note: "Konteyneri arxa planda (detached) işə salır və terminalı dərhal geri qaytarır. Uzun müddət işləyəcək servislər (verilənlər bazası, veb server) üçün standart üsuldur.",
    example: "docker run -d -p 8080:80 --name veb nginx:alpine",
    section: "konteyner",
    match: ["arxa planda işə sal", "background", "detached"],
  },
  {
    term: "docker run -it",
    note: "Konteyneri interaktiv terminal ilə açır: içərisində əl ilə komanda yazmaq üçün. Şəkili yoxlamaq və ya konteynerin içində problem axtarmaq üçün işlədilir.",
    example: "docker run -it ubuntu bash",
    section: "konteyner",
    match: ["interaktiv konteyner", "terminala düş", "shell aç"],
  },
  {
    term: "docker run --rm",
    note: "Konteyner dayananda onu avtomatik silir. Bir dəfəlik komanda işlətmək (test, skript) üçün, geridə boş, dayanmış konteynerlər yığılmasın deyə.",
    example: "docker run --rm -it node:20 node -v",
    section: "konteyner",
    match: ["bir dəfəlik konteyner", "avtomatik sil"],
  },
  {
    term: "docker ps",
    note: "İşləyən konteynerlərin siyahısını göstərir: ID, şəkil, port və vəziyyəti ilə. Hansı konteynerlərin canlı olduğunu yoxlamaq üçün ilk işlədilən əmrdir.",
    example: "docker ps",
    section: "konteyner",
    match: ["işləyən konteynerlər", "canlı konteynerlər"],
  },
  {
    term: "docker ps -a",
    note: "Dayandırılmış konteynerləri də daxil edərək bütün konteynerləri göstərir. Bir konteynerin niyə işə düşmədiyini araşdırarkən lazımdır.",
    example: "docker ps -a",
    section: "konteyner",
    match: ["bütün konteynerlər", "dayanmış konteynerlər"],
  },
  {
    term: "docker stop",
    note: "Konteynerə dayanma siqnalı göndərir və prosesin özü təmiz bağlanmasına vaxt verir, vaxt bitəndə məcburi dayandırır. Konteyneri saxlamadan (silmədən) müvəqqəti söndürmək üçündür.",
    example: "docker stop veb",
    section: "konteyner",
    match: ["konteyneri söndür", "dayandır"],
  },
  {
    term: "docker start",
    note: "Əvvəllər dayandırılmış, amma silinməmiş konteyneri həmin vəziyyətindən yenidən işə salır. run-dan fərqli olaraq yeni konteyner yaratmır.",
    example: "docker start veb",
    section: "konteyner",
    match: ["dayanmış konteyneri işə sal"],
  },
  {
    term: "docker restart",
    note: "Konteyneri dayandırıb dərhal yenidən işə salır: konfiqurasiya faylını yenidən oxutmaq və ya asılı qalmış prosesi sıfırlamaq üçün ən qısa yoldur.",
    example: "docker restart veb",
    section: "konteyner",
    match: ["yenidən başlat"],
  },
  {
    term: "docker rm",
    note: "Dayandırılmış konteyneri tamamilə silir: işləyən konteyneri silmək üçün əvvəlcə stop, ya da -f ilə məcburi silmək lazımdır.",
    example: "docker rm veb",
    section: "konteyner",
    match: ["konteyneri sil"],
  },
  {
    term: "docker exec -it",
    note: "İşləyən konteynerin içində əlavə bir komanda (adətən bash və ya sh) açır, konteyneri yenidən başlatmadan. Canlı konteynerin içinə baxıb problemi diaqnoz etmək üçün ən çox işlədilən əmrdir.",
    example: "docker exec -it veb sh",
    section: "konteyner",
    match: ["konteynerin içinə gir", "shell aç"],
  },
  {
    term: "docker logs",
    note: "Konteynerin stdout/stderr çıxışını göstərir. Konteyner niyə dayandığını və ya səhv verdiyini ilk yoxlanan yer budur.",
    example: "docker logs veb",
    section: "konteyner",
    match: ["konteyner logları", "çıxışı göstər"],
  },
  {
    term: "docker logs -f",
    note: "Logları göstərməklə yanaşı axını açıq saxlayır: yeni sətir yazılan kimi ekrana düşür. Canlı sistemi izləyərkən ən çox işlədilən formadır.",
    example: "docker logs -f veb",
    section: "konteyner",
    match: ["logları canlı izlə", "follow"],
  },
  {
    term: "docker inspect",
    note: "Konteyner və ya şəkil haqqında bütün detalları (IP ünvanı, mount-lar, mühit dəyişənləri, ayarlar) JSON formatında verir. Bir dəyərin dəqiq nə olduğunu skriptdən oxumaq üçün lazımdır.",
    example: "docker inspect veb",
    section: "konteyner",
    match: ["detallara bax", "json ayarlar"],
  },
  {
    term: "docker stats",
    note: "İşləyən konteynerlərin CPU, yaddaş və şəbəkə istifadəsini canlı göstərir. Hansı konteynerin resursu çox yediyini tapmaq üçündür.",
    example: "docker stats",
    section: "konteyner",
    match: ["resurs istifadəsi", "cpu yaddaş"],
  },
  {
    term: "docker top",
    note: "Konteynerin içində işləyən prosesləri host-un ps əmrindəki kimi göstərir. Konteynerin içində gözlənilməz bir proses işləyib-işləmədiyini yoxlamaq üçün.",
    example: "docker top veb",
    section: "konteyner",
    match: ["konteynerdəki proseslər"],
  },
  {
    term: "docker cp",
    note: "Fayl və ya qovluğu konteynerlə host arasında köçürür, hər iki istiqamətdə. Konteynerin içindəki bir log faylını və ya konfiqi tez çıxarmaq üçün işlədilir.",
    example: "docker cp veb:/etc/nginx/nginx.conf ./nginx.conf",
    section: "konteyner",
    match: ["faylı konteynerdən çıxar", "faylı konteynerə at"],
  },
  {
    term: "docker port",
    note: "Konteynerin daxili portlarının host-da hansı porta bağlandığını göstərir. -p ilə göstərilən eşləmə hardadır sualının cavabıdır.",
    example: "docker port veb",
    section: "konteyner",
    match: ["port eşləməsi"],
  },
  {
    term: "docker rename",
    note: "İşləyən və ya dayanmış konteynerin adını dəyişir, konteyneri yenidən yaratmadan.",
    example: "docker rename veb veb-kohne",
    section: "konteyner",
    match: ["konteynerin adını dəyiş"],
  },
  {
    term: "docker pause",
    note: "Konteynerin bütün proseslərini dayandırmadan dondurur: CPU planlaşdırıcısından müvəqqəti çıxarır. Resurs istifadəsini bir anlıq kəsmək, konteyneri isə saxlamaq lazım olanda işlədilir.",
    example: "docker pause veb",
    section: "konteyner",
    match: ["konteyneri dondur"],
  },
  {
    term: "docker unpause",
    note: "pause ilə dondurulmuş konteyneri qaldığı yerdən davam etdirir.",
    example: "docker unpause veb",
    section: "konteyner",
    match: ["konteyneri qaldığı yerdən davam etdir", "dondurmadan çıxar"],
  },
  {
    term: "docker kill",
    note: "Konteynerə dərhal dayanma siqnalı (SIGKILL) göndərir, təmiz bağlanmaya vaxt vermir. stop cavab vermədiyi asılı qalmış konteynerlər üçün son çarədir.",
    example: "docker kill veb",
    section: "konteyner",
    match: ["konteyneri məcburi öldür"],
  },
  {
    term: "docker wait",
    note: "Konteyner dayanana qədər gözləyir və çıxış kodunu qaytarır. Skriptdə bir konteynerin bitməsini gözləyib nəticəyə görə davam etmək üçün lazımdır.",
    example: "docker wait veb",
    section: "konteyner",
    match: ["konteynerin bitməsini gözlə", "çıxış kodu"],
  },

  /* ---------- sekil ---------- */
  {
    term: "docker build",
    note: "Dockerfile-a əsasən yeni bir şəkil qurur. Cari qovluqdakı Dockerfile-ı oxuyub addım-addım qatlar yaradır.",
    example: "docker build .",
    section: "sekil",
    match: ["şəkil qur", "dockerfile-dan qur"],
  },
  {
    term: "docker build -t",
    note: "Qurulan şəkilə ad və etiket (tag) verir: adsız şəkil yalnız ID ilə tapılır, bu isə onu adla işlətməyə imkan verir.",
    example: "docker build -t veb:1.0 .",
    section: "sekil",
    match: ["şəkilə ad ver", "tag ilə qur"],
  },
  {
    term: "docker build --no-cache",
    note: "Əvvəlki qatların keşini işlətmədən, hər addımı sıfırdan yenidən işlədir. Keşlənmiş bir addımın köhnəlmiş nəticə verdiyindən şübhələnəndə lazımdır.",
    example: "docker build --no-cache -t veb:1.0 .",
    section: "sekil",
    match: ["keşsiz qur", "sıfırdan qur"],
  },
  {
    term: "docker images",
    note: "Lokalda saxlanan bütün şəkillərin siyahısını, ölçüləri ilə birlikdə göstərir. Disk yerini hansı şəkillərin apardığını görmək üçün işlədilir.",
    example: "docker images",
    section: "sekil",
    match: ["şəkillər siyahısı"],
  },
  {
    term: "docker pull",
    note: "Uzaq reyestrdən (defolt olaraq Docker Hub) bir şəkili lokala endirir, işə salmadan. run əslində şəkil lokalda yoxdursa bunu özü çağırır.",
    example: "docker pull postgres:16",
    section: "sekil",
    match: ["şəkili endir"],
  },
  {
    term: "docker push",
    note: "Lokal şəkili uzaq reyestrə göndərir, adətən öz hesabın altında. Başqa serverdə və ya komanda yoldaşında eyni şəkili işlətmək üçün əvvəlcə bura göndərilir.",
    example: "docker push mehesabim/veb:1.0",
    section: "sekil",
    match: ["şəkili göndər", "reyestrə yüklə"],
  },
  {
    term: "docker tag",
    note: "Mövcud şəkilə əlavə bir ad-etiket qoyur, yeni şəkil yaratmadan: eyni şəkilin bir neçə adı ola bilər. push etməzdən əvvəl şəkili reyestrin gözlədiyi adla etiketləmək üçün lazımdır.",
    example: "docker tag veb:1.0 mehesabim/veb:1.0",
    section: "sekil",
    match: ["şəkilə etiket ver", "yenidən adlandır"],
  },
  {
    term: "docker rmi",
    note: "Lokal şəkili silir. Şəkildən yaradılmış konteyner hələ varsa, əvvəlcə o konteyner silinməlidir.",
    example: "docker rmi veb:1.0",
    section: "sekil",
    match: ["şəkili sil"],
  },
  {
    term: "docker save",
    note: "Şəkili tək bir .tar faylına yazır: internetsiz mühitə köçürmək üçün. load ilə bu faylın əksi edilir.",
    example: "docker save -o veb.tar veb:1.0",
    section: "sekil",
    match: ["şəkili fayla yaz", "arxivlə"],
  },
  {
    term: "docker load",
    note: "save ilə yaradılmış .tar faylından şəkili lokal Docker-ə geri yükləyir: internetsiz mühitdə şəkil paylaşmağın yoludur.",
    example: "docker load -i veb.tar",
    section: "sekil",
    match: ["arxivdən şəkil yüklə"],
  },
  {
    term: "docker history",
    note: "Şəkilin hansı qatlardan (layer) yarandığını, hər qatın hansı Dockerfile sətrindən gəldiyini və ölçüsünü göstərir. Şəkilin niyə bu qədər böyük olduğunu tapmaq üçün istifadə olunur.",
    example: "docker history veb:1.0",
    section: "sekil",
    match: ["qat tarixçəsi", "şəkil niyə böyükdür"],
  },
  {
    term: "docker commit",
    note: "İşləyən bir konteynerin cari vəziyyətini yeni bir şəkil olaraq dondurur. Adətən müvəqqəti sınaq üçün işlədilir: daimi dəyişikliklər Dockerfile-a yazılmalıdır.",
    example: "docker commit veb veb:sinaq",
    section: "sekil",
    match: ["konteyneri şəkilə çevir"],
  },

  /* ---------- compose ---------- */
  {
    term: "docker compose up",
    note: "compose.yaml-dakı bütün servisləri qurur (lazımdırsa) və ön planda işə salır: terminalı tutur, hamısının logunu qarışıq göstərir. Yeni layihəni ilk dəfə ayağa qaldırarkən nəyin baş verdiyini görmək üçün rahatdır.",
    example: "docker compose up",
    section: "compose",
    match: ["bütün servisləri işə sal"],
  },
  {
    term: "docker compose up -d",
    note: "Eyni işi arxa planda görür: terminalı geri qaytarır. Gündəlik inkişaf mühitini işə salmağın standart yoludur.",
    example: "docker compose up -d",
    section: "compose",
    match: ["arxa planda hamısını işə sal"],
  },
  {
    term: "docker compose down",
    note: "up ilə yaradılmış bütün konteynerləri və şəbəkəni dayandırıb silir, amma adlandırılmış volume-lara toxunmur: verilənlər qalır.",
    example: "docker compose down",
    section: "compose",
    match: ["hamısını dayandır və sil"],
  },
  {
    term: "docker compose down -v",
    note: "down-un etdiyi hər şeyə əlavə olaraq adlandırılmış volume-ları da silir: verilənlər bazasındakı bütün məlumat da daxil. Sıfırdan təmiz başlamaq istəyəndə, itkiyə hazır olaraq işlədilir.",
    example: "docker compose down -v",
    section: "compose",
    match: ["verilənləri də sil", "volume-ları sil"],
  },
  {
    term: "docker compose logs -f",
    note: "Bütün servislərin loglarını hər birinin adı ilə qarışıq, canlı axın kimi göstərir. Bir neçə servisin bir-birinə necə cavab verdiyini izləmək üçün lazımdır.",
    example: "docker compose logs -f",
    section: "compose",
    match: ["compose loglarını izlə"],
  },
  {
    term: "docker compose ps",
    note: "compose.yaml-dakı servislərin hansının işlədiyini, hansının dayandığını göstərir: düz docker ps-dən fərqli olaraq yalnız bu layihəyə aid olanları.",
    example: "docker compose ps",
    section: "compose",
    match: ["compose servislər siyahısı"],
  },
  {
    term: "docker compose build",
    note: "compose.yaml-da build göstərilən servislərin şəkillərini yenidən qurur, işə salmadan. Dockerfile-da dəyişiklik etdikdən sonra up-dan əvvəl işlədilir.",
    example: "docker compose build",
    section: "compose",
    match: ["compose şəkilləri qur"],
  },
  {
    term: "docker compose exec",
    note: "İşləyən bir compose servisinin içində komanda açır: adi docker exec-in servis adları ilə işləyən qarşılığıdır.",
    example: "docker compose exec veb sh",
    section: "compose",
    match: ["compose servisinə gir"],
  },
  {
    term: "docker compose restart",
    note: "compose.yaml-dakı bir və ya bütün servisləri yenidən başladır, konteynerləri silmədən.",
    example: "docker compose restart veb",
    section: "compose",
    match: ["compose servisini yenidən başlat"],
  },

  /* ---------- sebeke ---------- */
  {
    term: "docker network ls",
    note: "Docker-in idarə etdiyi bütün şəbəkələrin siyahısını göstərir: bridge, host, none və əl ilə yaradılanlar.",
    example: "docker network ls",
    section: "sebeke",
    match: ["şəbəkələr siyahısı"],
  },
  {
    term: "docker network create",
    note: "Konteynerlərin bir-birini adları ilə tapa biləcəyi yeni bir şəbəkə yaradır. Ayrı-ayrı docker run ilə açılan konteynerləri eyni şəbəkəyə qoşmaq üçün lazımdır.",
    example: "docker network create layihe-seb",
    section: "sebeke",
    match: ["yeni şəbəkə yarat"],
  },
  {
    term: "docker network connect",
    note: "İşləyən bir konteyneri əlavə bir şəbəkəyə qoşur, konteyneri yenidən yaratmadan.",
    example: "docker network connect layihe-seb veb",
    section: "sebeke",
    match: ["konteyneri şəbəkəyə qoş"],
  },
  {
    term: "docker network inspect",
    note: "Bir şəbəkənin ayarlarını və ona qoşulu bütün konteynerlərin siyahısını göstərir. İki konteyner niyə bir-birini görmür sualının cavabı adətən buradadır.",
    example: "docker network inspect layihe-seb",
    section: "sebeke",
    match: ["şəbəkə detalları", "kim qoşulub"],
  },
  {
    term: "docker volume ls",
    note: "Bütün adlandırılmış volume-ların siyahısını göstərir. Verilənlərin harada saxlandığını izləmək üçün ilk baxılan yerdir.",
    example: "docker volume ls",
    section: "sebeke",
    match: ["volume siyahısı"],
  },
  {
    term: "docker volume create",
    note: "Konteynerin ömründən asılı olmayan, ayrıca saxlanan bir volume yaradır. Verilənlər bazası kimi konteyner silinəndə də qalmalı olan verilənlər üçün lazımdır.",
    example: "docker volume create db-data",
    section: "sebeke",
    match: ["yeni volume yarat"],
  },
  {
    term: "docker volume rm",
    note: "Adlandırılmış volume-u tamamilə silir: içindəki verilənlər də silinir. Heç bir konteyner tərəfindən işlədilmirsə silinə bilər.",
    example: "docker volume rm db-data",
    section: "sebeke",
    match: ["volume-u sil"],
  },
  {
    term: "docker volume inspect",
    note: "Volume-un diskdə həqiqətən harada saxlandığını və hansı ayarlarla yaradıldığını göstərir.",
    example: "docker volume inspect db-data",
    section: "sebeke",
    match: ["volume detalları"],
  },

  /* ---------- temizlik ---------- */
  {
    term: "docker system df",
    note: "Şəkillərin, konteynerlərin, volume-ların və build keşinin nə qədər disk yeri apardığını, nə qədərinin işlədilmədiyini göstərir. system prune-dan əvvəl nəyin təmizlənəcəyini görmək üçün.",
    example: "docker system df",
    section: "temizlik",
    match: ["disk istifadəsi", "yer nə qədər gedir"],
  },
  {
    term: "docker system prune",
    note: "Dayandırılmış konteynerləri, işlədilməyən şəbəkələri və etiketsiz (dangling) şəkilləri silir. Adlandırılmış şəkillər və volume-lar toxunulmaz qalır.",
    example: "docker system prune",
    section: "temizlik",
    match: ["yer boşalt", "təmizlə"],
  },
  {
    term: "docker system prune -a --volumes",
    note: "Təhlükəlidir: yalnız dayandırılmış konteynerləri deyil, işlədilməyən bütün şəkilləri (etiketli olsa belə) və işlədilməyən bütün volume-ları da silir: verilənlər bazası volume-u istifadədə deyilsə geri qaytarılmadan itir. İşlətmədən əvvəl docker system df ilə nəyin siləcəyinə baxmaq lazımdır.",
    example: "docker system prune -a --volumes",
    section: "temizlik",
    match: ["hər şeyi təmizlə", "bütün yeri boşalt", "təhlükəli təmizlik"],
  },
  {
    term: "docker image prune",
    note: "Yalnız etiketsiz (dangling) şəkilləri silir: işlədilən heç bir şəkilə toxunmur. system prune-un daha ehtiyatlı, yalnız şəkillərə baxan forması.",
    example: "docker image prune",
    section: "temizlik",
    match: ["işlənməyən şəkilləri sil"],
  },
  {
    term: "docker container prune",
    note: "Yalnız dayandırılmış konteynerləri silir, işləyənlərə toxunmur. Test üçün açılıb unudulan konteynerləri təmizləmək üçün rahatdır.",
    example: "docker container prune",
    section: "temizlik",
    match: ["dayanmış konteynerləri sil"],
  },
  {
    term: "docker builder prune",
    note: "build zamanı yığılan keşi silir. Keş çox yer tutmağa başlayanda, ya da köhnəlmiş keşdən şübhələnəndə işlədilir.",
    example: "docker builder prune",
    section: "temizlik",
    match: ["build keşini sil"],
  },

  /* ---------- sazlama ---------- */
  {
    term: "docker login",
    note: "Docker Hub və ya başqa bir reyestrlə hesabını əlaqələndirir: bundan sonrakı pull/push bu hesabla aparılır. Şəxsi (private) şəkilləri çəkmək və ya öz şəkilini göndərmək üçün ilk addımdır.",
    example: "docker login",
    section: "sazlama",
    match: ["reyestrə giriş"],
  },
  {
    term: "docker logout",
    note: "Cari reyestr sessiyasından çıxır: saxlanmış giriş məlumatını silir. Paylaşılan maşında işi bitirdikdən sonra işlədilməlidir.",
    example: "docker logout",
    section: "sazlama",
    match: ["reyestrdən çıx"],
  },
  {
    term: "docker info",
    note: "Docker mühərrikinin ümumi vəziyyətini göstərir: neçə konteyner, neçə şəkil işlədiyi, hansı sürücülərin aktiv olduğu. Quraşdırmanın düzgün işlədiyini yoxlamaq üçün lazımdır.",
    example: "docker info",
    section: "sazlama",
    match: ["docker vəziyyəti", "mühərrik məlumatı"],
  },
  {
    term: "docker version",
    note: "Həm client, həm də server (daemon) tərəfinin versiya nömrələrini göstərir. İkisi uyğun gəlmirsə bəzi əmrlər gözlənilməz işləyə bilər.",
    example: "docker version",
    section: "sazlama",
    match: ["versiya yoxla"],
  },
  {
    term: "docker context ls",
    note: "Docker CLI-nin qoşula biləcəyi bütün mühərrikləri (lokal, uzaq server, WSL) siyahı ilə göstərir və hansının aktiv olduğunu işarələyir. Komandaların birdən yanlış serverə getdiyini görəndə yoxlanılan ilk yerdir.",
    example: "docker context ls",
    section: "sazlama",
    match: ["mühərriklər siyahısı", "hansı docker-ə qoşuluyam"],
  },
];
