/*
 * The rows behind the `git-emrleri` reference table. Shape and search live in
 * `reference.ts`; this file only supplies the terms, in six task-shaped
 * groups rather than git's own porcelain/plumbing split — a visitor comes
 * here mid-task ("how do I undo this"), not mid-manual.
 */
import type { ReferenceRow, ReferenceSection } from "./reference";

export const gitEmrleriSections: ReferenceSection[] = [
  { id: "gundelik", label: "Gündəlik iş" },
  { id: "budaq", label: "Budaq və birləşdirmə" },
  { id: "tarixce", label: "Tarixçə və axtarış" },
  { id: "geri", label: "Geri qaytarma" },
  { id: "uzaq", label: "Uzaq repo" },
  { id: "sazlama", label: "Sazlama və təmizlik" },
];

export const gitEmrleriRows: ReferenceRow[] = [
  /* ---------- gundelik ---------- */
  {
    term: "git init",
    note: "Cari qovluqda yeni, boş Git deposu yaradır — .git qovluğu buraya düşür. Mövcud layihəni versiya nəzarətinə indi başlamaq istəyəndə işlədilir.",
    example: "git init",
    section: "gundelik",
    match: ["yeni depo", "repo yarat"],
  },
  {
    term: "git clone",
    note: "Uzaq depon tam tarixçəsi ilə birlikdə lokal qovluğa köçürür və origin adlı uzaq bağlantını özü qurur. Mövcud layihəyə qoşulmağın standart yoludur.",
    example: "git clone git@github.com:istifadeci/repo.git",
    section: "gundelik",
    match: ["depon köçür", "layihəni endir"],
  },
  {
    term: "git status",
    note: "Hansı faylların dəyişdiyini, hansıların stage-də olduğunu və hansı budaqda olduğunu göstərir. Hər commitdən əvvəl vəziyyəti yoxlamaq üçün ilk işlədilən əmrdir.",
    example: "git status",
    section: "gundelik",
    match: ["vəziyyəti göstər", "nə dəyişib"],
  },
  {
    term: "git add",
    note: "Seçilən faylları stage sahəsinə əlavə edir — növbəti commitə nələrin daxil olacağını müəyyən edir. Faylı hazırlamaq deyəndə bu nəzərdə tutulur.",
    example: "git add src/index.ts",
    section: "gundelik",
    match: ["stage et", "commitə hazırla"],
  },
  {
    term: "git add -A",
    note: "Yeni, dəyişdirilmiş və silinmiş bütün faylları bir dəfəyə stage edir. Tək-tək faylı seçmək vaxt aparanda, bütün işi commitə hazırlamaq üçün işlədilir.",
    example: "git add -A",
    section: "gundelik",
    match: ["hamısını stage et", "add all"],
  },
  {
    term: "git add -p",
    note: "Hər faylın dəyişikliklərini kiçik parçalara bölüb, hansı parçanın stage-ə düşəcəyini bir-bir soruşur. Bir faylda həm commitə aid, həm də əlaqəsiz dəyişiklik olanda işə yarayır.",
    example: "git add -p src/index.ts",
    section: "gundelik",
    match: ["qismən stage", "interactive add", "parça-parça əlavə et"],
  },
  {
    term: "git commit",
    note: "Stage edilmiş dəyişiklikləri tarixçəyə yeni bir nöqtə kimi yazır. Mesaj vermədən çağırılanda əvvəlcədən təyin edilmiş redaktor pəncərəsi açılır.",
    example: "git commit",
    section: "gundelik",
    match: ["dəyişikliyi yadda saxla", "commit et"],
  },
  {
    term: "git commit -m",
    note: "Commiti mesajı ilə birlikdə tək sətirdə yaradır, ayrıca redaktor açılmır. Qısa, aydın dəyişikliklər üçün ən çox işlədilən formadır.",
    example: 'git commit -m "login formasında validasiya düzəldildi"',
    section: "gundelik",
    match: ["mesajla commit"],
  },
  {
    term: "git commit --amend",
    note: "Son commiti tamamilə əvəz edir — mesajını dəyişə, unudulmuş faylı əlavə edə bilərsən. Amma bu commit artıq push edilibsə tarixçəni dəyişdiyi üçün diqqətli olmaq lazımdır.",
    example: 'git commit --amend -m "düzəldilmiş mesaj"',
    section: "gundelik",
    match: ["son commiti düzəlt", "amend", "commiti dəyiş"],
  },
  {
    term: "git diff",
    note: "Working directory ilə son commit arasındakı fərqi sətir-sətir göstərir — hələ stage edilməmiş dəyişiklikləri görmək üçün.",
    example: "git diff src/index.ts",
    section: "gundelik",
    match: ["fərqə bax", "nə dəyişib sətir"],
  },
  {
    term: "git diff --staged",
    note: "Yalnız artıq stage edilmiş dəyişiklikləri göstərir — commit etməzdən əvvəl nəyin daxil olacağını son dəfə yoxlamaq üçün.",
    example: "git diff --staged",
    section: "gundelik",
    match: ["stage olunanlara bax", "diff --cached"],
  },
  {
    term: "git restore",
    note: "Bir faylı son commitdəki halına qaytarır, working directory-dəki dəyişikliyi ləğv edir. Səhv redaktəni geri götürmək üçün istifadə olunur.",
    example: "git restore src/index.ts",
    section: "gundelik",
    match: ["dəyişikliyi ləğv et", "faylı köhnə hala qaytar"],
  },
  {
    term: "git restore --staged",
    note: "Faylı stage sahəsindən çıxarır, amma faylın özündəki dəyişikliyi silmir. Səhvən add etdiyin faylı commitdən çıxarmaq üçün lazımdır.",
    example: "git restore --staged src/index.ts",
    section: "gundelik",
    match: ["unstage et", "stage-dən çıxar"],
  },
  {
    term: "git rm --cached",
    note: "Faylı Git-in izləməsindən çıxarır, amma diskdəki faylı toxunulmaz saxlayır. Adətən .gitignore-a sonradan əlavə edilən faylı depodan çıxarmaq üçün işlədilir.",
    example: "git rm --cached .env",
    section: "gundelik",
    match: ["izləməni dayandır", "faylı depodan çıxar"],
  },
  {
    term: "git mv",
    note: "Faylı köçürür və ya adını dəyişir, həm də bu əməliyyatı stage edir — ayrıca mv və add etməyə ehtiyac qalmır.",
    example: "git mv kohne-ad.ts yeni-ad.ts",
    section: "gundelik",
    match: ["faylı köçür", "adını dəyiş"],
  },

  /* ---------- budaq ---------- */
  {
    term: "git branch",
    note: "Mövcud budaqların siyahısını göstərir, arqumentsiz çağırılanda; adla çağırılanda isə həmin adda yeni budaq yaradır, amma ona keçmir.",
    example: "git branch yeni-ozellik",
    section: "budaq",
    match: ["budaqlar siyahısı", "yeni budaq yarat"],
  },
  {
    term: "git branch -a",
    note: "Lokal budaqlarla yanaşı uzaq depodakı bütün izlənən budaqları da göstərir. Kiminsə push etdiyi budağı görmək üçün lazımdır.",
    example: "git branch -a",
    section: "budaq",
    match: ["bütün budaqlar", "uzaq budaqlar siyahısı"],
  },
  {
    term: "git branch -d",
    note: "Artıq main-ə birləşdirilmiş budağı silir. Birləşdirilməyibsə Git xəbərdarlıq edib silməkdən imtina edir — məcburi silmək üçün -D lazımdır.",
    example: "git branch -d kohne-ozellik",
    section: "budaq",
    match: ["budağı sil", "delete branch"],
  },
  {
    term: "git checkout",
    note: "Başqa bir budağa keçir və ya konkret fayl üçün onu son commitdəki halına qaytarır. Bu ikili məna sonradan switch və restore ilə ayrıldı, amma checkout hələ də çox işlədilən əmrlərdəndir.",
    example: "git checkout main",
    section: "budaq",
    match: ["budağa keç", "köhnə əmr"],
  },
  {
    term: "git switch",
    note: "checkout-un budaq dəyişməyə həsr olunmuş, daha sadə yeni forması — yalnız budaq dəyişir, fayl bərpa etmir.",
    example: "git switch main",
    section: "budaq",
    match: ["budağa keç", "yeni switch"],
  },
  {
    term: "git switch -c",
    note: "Yeni budaq yaradır və dərhal ona keçir — branch və checkout-un iki addımını birləşdirir.",
    example: "git switch -c yeni-ozellik",
    section: "budaq",
    match: ["yeni budaq yarat və keç", "checkout -b"],
  },
  {
    term: "git merge",
    note: "Başqa budağın commitlərini cari budağa gətirir. Sürətli-irəli mümkündürsə tarixçə düz xətt olaraq qalır, deyilsə birləşdirmə commiti yaranır.",
    example: "git merge ozellik-budagi",
    section: "budaq",
    match: ["budaqları birləşdir"],
  },
  {
    term: "git merge --no-ff",
    note: "Sürətli-irəli mümkün olsa belə ayrıca birləşdirmə commiti yaradır, ona görə budağın nə vaxt və hansı işlə gəldiyi tarixçədə açıq qalır.",
    example: "git merge --no-ff ozellik-budagi",
    section: "budaq",
    match: ["merge commit yarat", "fast-forward yox"],
  },
  {
    term: "git rebase",
    note: "Cari budağın commitlərini başqa budağın üstünə, sanki oradan başlanmış kimi yenidən tətbiq edir. Nəticədə tarixçə düz xətt olur, amma commit hash-ləri dəyişir.",
    example: "git rebase main",
    section: "budaq",
    match: ["budağı yenilə", "tarixçəni düzləşdir"],
  },
  {
    term: "git rebase -i",
    note: "Commitləri bir-bir redaktə etmək, sıraya salmaq, birləşdirmək (squash) və ya silmək imkanı verən interaktiv rebase. Push etməmiş yerli commitləri təmizləmək üçün istifadə olunur.",
    example: "git rebase -i HEAD~3",
    section: "budaq",
    match: ["interaktiv rebase", "commitləri birləşdir", "squash"],
  },
  {
    term: "git rebase --onto",
    note: "Commitləri bir budaqdan başqa bir nöqtəyə, aralıq budağı tamamilə yox sayaraq köçürür. Səhv nöqtədən açılmış budağı düzəltmək üçün lazımdır.",
    example: "git rebase --onto main eski-baslangic ozellik-budagi",
    section: "budaq",
    match: ["budağı köçür", "yenidən əsasla"],
  },
  {
    term: "git cherry-pick",
    note: "Başqa budaqdan tək bir commiti seçib cari budağa tətbiq edir, bütün budağı birləşdirmədən. Başqa yerdə düzəldilmiş bir baq düzəlişini bura da gətirmək üçün işlədilir.",
    example: "git cherry-pick a1b2c3d",
    section: "budaq",
    match: ["tək commit köçür", "commiti gətir"],
  },
  {
    term: "git worktree add",
    note: "Eyni depo üçün ayrı bir qovluqda başqa budağı checkout edir — iki budaq üzərində eyni anda, budaq dəyişmədən işləmək üçün.",
    example: "git worktree add ../hotfix hotfix-budagi",
    section: "budaq",
    match: ["paralel budaq qovluğu", "ikinci checkout"],
  },

  /* ---------- tarixce ---------- */
  {
    term: "git log",
    note: "Commit tarixçəsini ən yenidən başlayaraq göstərir — hər commitin hash-i, müəllifi, tarixi və mesajı ilə. Nə vaxt nə edildiyini görmək üçün başlanğıc nöqtədir.",
    example: "git log -5",
    section: "tarixce",
    match: ["tarixçəyə bax", "commitlər siyahısı"],
  },
  {
    term: "git log --oneline --graph",
    note: "Hər commiti tək sətirdə göstərir və budaqların necə birləşdiyini ASCII xətlərlə çəkir. Qarışıq bir tarixçəni tez anlamaq üçün ən oxunaqlı formadır.",
    example: "git log --oneline --graph --all",
    section: "tarixce",
    match: ["budaq xəritəsi", "tarixçə qrafiki"],
  },
  {
    term: "git log -p",
    note: "Hər commitin mesajı ilə yanaşı, onun daxilindəki faktiki dəyişiklikləri (patch) də göstərir. Nə vaxt hansı sətrin dəyişdiyini tapmaq üçün lazımdır.",
    example: "git log -p -- src/index.ts",
    section: "tarixce",
    match: ["commit patch-ları", "dəyişiklikləri tarixçədə gör"],
  },
  {
    term: "git show",
    note: "Bir commitin tam məzmununu — mesajını və dəyişikliklərini — göstərir. Konkret bir commitə yaxından baxmaq üçün işlədilir.",
    example: "git show a1b2c3d",
    section: "tarixce",
    match: ["commit detalları"],
  },
  {
    term: "git blame",
    note: "Faylın hər sətrini onu son dəfə dəyişən commitə və müəllifə bağlayır. Bir sətrin niyə belə yazıldığını öyrənmək üçün ən sürətli yoldur.",
    example: "git blame src/index.ts",
    section: "tarixce",
    match: ["kim yazıb", "sətir tarixçəsi"],
  },
  {
    term: "git bisect",
    note: "İki nöqtə arasında ikili axtarışla baqın hansı commitdə yarandığını tapır — hər addımda commiti yaxşı ya da pis kimi işarələyirsən, Git özü ortadakı commiti sınamağa təklif edir.",
    example: "git bisect start",
    section: "tarixce",
    match: ["baqı tap", "hansı commit sındırıb"],
  },
  {
    term: "git shortlog",
    note: "Commitləri müəllif üzrə qruplaşdırıb sayır — kimin nə qədər commit etdiyini tez görmək üçün.",
    example: "git shortlog -sn",
    section: "tarixce",
    match: ["müəllif üzrə commit sayı"],
  },
  {
    term: "git describe",
    note: "Cari commiti ən yaxın tag-a görə adlandırır, məsələn v1.2.0-5-ga1b2c3d — versiya nömrəsindən neçə commit uzaqda olduğunu göstərir.",
    example: "git describe --tags",
    section: "tarixce",
    match: ["ən yaxın tag", "versiya adı"],
  },
  {
    term: "git grep",
    note: "Bütün izlənən fayllar üzrə mətn axtarışı aparır, amma .gitignore-dakı faylları buraxır — adi grep-dən daha sürətli və təmizdir.",
    example: 'git grep "TODO"',
    section: "tarixce",
    match: ["kodda axtar", "mətn axtarışı"],
  },
  {
    term: "git cat-file",
    note: "Git-in daxili obyekt bazasındakı bir obyektin (commit, ağac, blob) tam məzmununu göstərir. Adətən Git-in içərisini öyrənmək və ya skript yazarkən işlədilir.",
    example: "git cat-file -p a1b2c3d",
    section: "tarixce",
    match: ["obyekt məzmunu", "blob göstər"],
  },
  {
    term: "git ls-files",
    note: "Stage sahəsindəki və izlənən bütün faylların siyahısını verir — .gitignore-a düşməyən faylların tam siyahısı.",
    example: "git ls-files",
    section: "tarixce",
    match: ["izlənən fayllar", "stage siyahısı"],
  },

  /* ---------- geri ---------- */
  {
    term: "git reset --soft",
    note: "HEAD-i göstərilən commitə geri çəkir, amma stage sahəsini və working directory-ni toxunulmaz saxlayır — dəyişikliklər hələ də stage-dədir. Bir neçə commiti birləşdirib yenidən commit etmək istəyəndə lazımdır.",
    example: "git reset --soft HEAD~1",
    section: "geri",
    match: ["commit-i geri al", "undo commit", "yumşaq reset"],
  },
  {
    term: "git reset --mixed",
    note: "HEAD-i geri çəkir və stage sahəsini təmizləyir, amma faylların özündəki dəyişikliyi saxlayır — bu, reset-in defolt rejimidir. Commiti geri alıb yenidən diqqətlə stage etmək istəyəndə işlədilir.",
    example: "git reset --mixed HEAD~1",
    section: "geri",
    match: ["commit-i geri al", "undo commit", "orta reset"],
  },
  {
    term: "git reset --hard",
    note: "Təhlükəlidir: HEAD-i geri çəkir və həm stage sahəsini, həm də working directory-ni geri çəkilən nöqtəyə uyğunlaşdırır — commitlənməmiş bütün dəyişikliklər geri qaytarılmadan silinir. İşlətmədən əvvəl narahat olduğun dəyişiklikləri ayrıca commit ilə saxlamağa dəyər.",
    example: "git reset --hard HEAD~1",
    section: "geri",
    match: ["commit-i geri al", "undo commit", "sərt reset", "hər şeyi sil"],
  },
  {
    term: "git revert",
    note: "Köhnə commiti silmək əvəzinə, onun etdiyini ləğv edən yeni bir commit yaradır. Paylaşılmış, artıq push edilmiş budaqda təhlükəsiz geri qaytarma üsuludur, çünki tarixçəni dəyişdirmir.",
    example: "git revert a1b2c3d",
    section: "geri",
    match: ["commit-i geri al", "undo", "təhlükəsiz geri qaytarma"],
  },
  {
    term: "git stash",
    note: "Hazır olmayan dəyişiklikləri commit etmədən kənara qoyur və working directory-ni son commitin təmiz halına qaytarır. Başqa budağa tez keçmək lazım olanda, amma iş yarımçıqdırsa istifadə olunur.",
    example: "git stash",
    section: "geri",
    match: ["müvəqqəti saxla", "dəyişiklikləri gizlət"],
  },
  {
    term: "git stash pop",
    note: "Ən son saxlanmış stash-in içindəkiləri işlək qovluğa yenidən tətbiq edir və siyahıdan silir. Başqa budaqdakı işə davam etmək üçün ilk növbədə bu işlədilir.",
    example: "git stash pop",
    section: "geri",
    match: ["stash-i tətbiq et", "saxlananı gətir"],
  },
  {
    term: "git stash list",
    note: "Bütün saxlanmış stash-lərin siyahısını göstərir — hər biri nə vaxt hansı budaqda yaradıldığı ilə birlikdə. Birdən çox stash yığılanda hansının lazım olduğunu tapmaq üçündür.",
    example: "git stash list",
    section: "geri",
    match: ["stash siyahısı"],
  },
  {
    term: "git stash show -p",
    note: "Seçilmiş stash-in içindəki dəyişiklikləri onu tətbiq etmədən göstərir. Hansı stash-in lazım olduğuna əmin olmadıqda əvvəlcə buna baxılır.",
    example: "git stash show -p stash@{0}",
    section: "geri",
    match: ["stash içərisinə bax"],
  },
  {
    term: "git reflog",
    note: 'HEAD-in hərəkət etdiyi hər nöqtəni qeyd edir — reset --hard, rebase və ya budaq silmə ilə "itmiş" görünən commitlər əslində reflog-da qalır və oradan tapılıb bərpa edilə bilər.',
    example: "git reflog",
    section: "geri",
    match: ["itmiş commit-i tap", "HEAD tarixçəsi", "geri qaytar", "undo"],
  },

  /* ---------- uzaq ---------- */
  {
    term: "git fetch",
    note: "Uzaq depodakı yeni commitləri lokal repoya endirir, amma cari budağı dəyişdirmir — yalnız uzaq izləmə budaqlarını yeniləyir. Nə dəyişdiyinə birləşdirmədən əvvəl baxmaq üçün təhlükəsiz yoldur.",
    example: "git fetch origin",
    section: "uzaq",
    match: ["uzaqdan yenilə", "yenilikləri endir"],
  },
  {
    term: "git pull",
    note: "fetch ilə merge-i bir addımda edir — uzaq budağı endirib dərhal cari budağa birləşdirir. Ən sadə yenilənmə yoludur, amma lokal commitlərin varsa əlavə merge commiti yaradır.",
    example: "git pull origin main",
    section: "uzaq",
    match: ["yenilə və birləşdir"],
  },
  {
    term: "git pull --rebase",
    note: "fetch etdikdən sonra merge əvəzinə rebase edir — lokal commitlərin uzaqdakıların üstünə düzülür, gərəksiz merge commitləri yaranmır. Düz tarixçə saxlamaq istəyən komandalar bunu defolt edir.",
    example: "git pull --rebase origin main",
    section: "uzaq",
    match: ["yenilə və yenidən əsasla"],
  },
  {
    term: "git push",
    note: "Lokal commitləri uzaq depoya göndərir. Budaq uzaqda hələ yoxdursa, əvvəlcə -u ilə əlaqələndirmək lazımdır.",
    example: "git push origin main",
    section: "uzaq",
    match: ["dəyişiklikləri göndər", "uzağa göndər"],
  },
  {
    term: "git push -u",
    note: "Push edərkən lokal budağı uzaq budağa əlaqələndirir (upstream qurur) — bundan sonra tək sözlə git push və git pull kifayət edir. Yeni budağı ilk dəfə uzağa göndərəndə işlədilir.",
    example: "git push -u origin ozellik-budagi",
    section: "uzaq",
    match: ["upstream qur", "budağı əlaqələndir"],
  },
  {
    term: "git push --force-with-lease",
    note: "Uzaq budağı məcburi yeniləyir, amma sadə --force-dan fərqli olaraq əvvəlcə uzaqda kiminsə səndən xəbərsiz yeni commit əlavə etmədiyini yoxlayır və toqquşma varsa göndərmədən imtina edir. Sadə git push --force təhlükəlidir, çünki başqasının commitlərini xəbərdarlıq etmədən siləcək — rebase və ya amend etdikdən sonra paylaşılan budağı yeniləmək lazımdırsa əvəzinə bu işlədilməlidir.",
    example: "git push --force-with-lease origin ozellik-budagi",
    section: "uzaq",
    match: ["təhlükəsiz force push", "məcburi push", "force push"],
  },
  {
    term: "git remote -v",
    note: "Depoya bağlı bütün uzaq ünvanları (fetch və push üçün) siyahı ilə göstərir. Hansı ünvana push etdiyini unudanda ilk yoxlanılan şeydir.",
    example: "git remote -v",
    section: "uzaq",
    match: ["uzaq repo siyahısı"],
  },
  {
    term: "git remote add",
    note: "Depoya yeni bir uzaq bağlantı əlavə edir, adətən origin-dən fərqli ad ilə. Fork-dan əsl depoya keçid saxlamaq üçün ikinci uzaq (upstream) əlavə edərkən lazımdır.",
    example: "git remote add upstream git@github.com:esl-sahib/repo.git",
    section: "uzaq",
    match: ["yeni uzaq əlavə et"],
  },
  {
    term: "git remote remove",
    note: "Artıq lazım olmayan uzaq bağlantını depodan çıxarır. Səhv və ya köhnəlmiş bir remote-u təmizləmək üçün işlədilir.",
    example: "git remote remove upstream",
    section: "uzaq",
    match: ["uzağı sil", "remote sil"],
  },
  {
    term: "git tag",
    note: "Cari commitə sabit bir ad — adətən versiya nömrəsi — qoyur. Budaqdan fərqli olaraq tag irəli getmir, həmişə eyni commitə işarə edir.",
    example: "git tag v1.2.0",
    section: "uzaq",
    match: ["versiya nişanı"],
  },
  {
    term: "git tag -a",
    note: "Müəllif, tarix və mesajla birlikdə tam (annotated) tag yaradır. Rəsmi buraxılışlar üçün sadə tag əvəzinə bu tövsiyə olunur.",
    example: 'git tag -a v1.2.0 -m "ilk stabil buraxılış"',
    section: "uzaq",
    match: ["annotated tag", "versiya qeydi"],
  },
  {
    term: "git format-patch",
    note: "Hər commiti ayrıca .patch faylına çevirir — e-poçtla göndərmək və ya Git host-u olmayan yerdə paylaşmaq üçün.",
    example: "git format-patch -1 HEAD",
    section: "uzaq",
    match: ["patch faylı yarat", "email patch"],
  },
  {
    term: "git am",
    note: "format-patch ilə yaradılmış .patch fayllarını mesajları ilə birlikdə commit olaraq tətbiq edir. Uzaq depo olmadan, fayl mübadiləsi ilə commit almağın yoludur.",
    example: "git am 0001-duzelis.patch",
    section: "uzaq",
    match: ["patch tətbiq et", "mailbox patch"],
  },

  /* ---------- sazlama ---------- */
  {
    term: "git clean -fd",
    note: "Git-in heç vaxt izləmədiyi faylları və qovluqları (build çıxışı, təsadüfən yaranan fayllar) silir. Əvvəlcə -n ilə nəyin siləcəyinə baxmaq, sonra -fd ilə həqiqətən silmək tövsiyə olunur — geri qaytarılmır.",
    example: "git clean -fd",
    section: "sazlama",
    match: ["izlənməyən faylları sil", "təmizlə"],
  },
  {
    term: "git config --global",
    note: "İstifadəçi adı, e-poçt və redaktor kimi ayarları bütün depolarda keçərli olacaq şəkildə qlobal fayla yazır. Yeni bir maşında Git-i işə salmazdan əvvəl ilk edilən şeydir.",
    example: 'git config --global user.name "Ad Soyad"',
    section: "sazlama",
    match: ["qlobal ayar", "istifadəçi adını qur"],
  },
  {
    term: "git config --global --edit",
    note: "Qlobal konfiqurasiya faylını birbaşa mətn redaktorunda açır. Bir neçə ayarı eyni anda gözdən keçirmək və ya əl ilə düzəltmək lazım olanda daha rahatdır.",
    example: "git config --global --edit",
    section: "sazlama",
    match: ["qlobal faylı aç", "config faylını redaktə et"],
  },
  {
    term: "git check-ignore",
    note: ".gitignore qaydalarına görə bir faylın nə üçün (hansı sətirə görə) görməzdən gəlindiyini göstərir. Gözlədiyin fayl niyə əlavə olunmur sualına cavab verir.",
    example: "git check-ignore -v node_modules/paket",
    section: "sazlama",
    match: ["gitignore yoxla", "niyə görünmür"],
  },
  {
    term: "git apply",
    note: "Diff formatındakı bir yamağı working directory-yə tətbiq edir, commit yaratmadan. Başqasının göndərdiyi kiçik dəyişikliyi sınamaq üçün işlədilir.",
    example: "git apply duzelis.patch",
    section: "sazlama",
    match: ["patch tətbiq et", "yamağı tətbiq et"],
  },
  {
    term: "git notes",
    note: "Bir commitə, onun özünü dəyişmədən əlavə qeyd bağlayır — məsələn deploy tarixi və ya nəzərdən keçirmə şərhi. Adi commit mesajı kimi tarixçəyə hörülmür, ayrıca saxlanılır.",
    example: 'git notes add -m "staging-də yoxlanıldı" a1b2c3d',
    section: "sazlama",
    match: ["commitə qeyd əlavə et"],
  },
  {
    term: "git gc",
    note: "Deponu sıxışdırır — lazımsız obyektləri təmizləyir, qalanları daha səmərəli formata yığır. Böyük depolar zamanla ləng işləyəndə əl ilə də çağırıla bilər.",
    example: "git gc",
    section: "sazlama",
    match: ["deponu sıxışdır", "təmizlə"],
  },
  {
    term: "git fsck",
    note: "Depodakı bütün obyektlərin bütövlüyünü yoxlayır və zədələnmiş və ya əlaqəsiz obyektləri tapır. Depo qəribə davranırsa diaqnostika üçün ilk işlədilən əmrlərdəndir.",
    example: "git fsck --full",
    section: "sazlama",
    match: ["bütövlük yoxla", "depo xətası tap"],
  },
  {
    term: "git archive",
    note: "Cari halın .git tarixçəsi olmadan, sadəcə fayllardan ibarət arxivini (zip və ya tar) yaradır. Layihəni yalnız mənbə kodu kimi paylaşmaq üçün lazımdır.",
    example: "git archive --format=zip -o cixis.zip HEAD",
    section: "sazlama",
    match: ["zip yarat", "arxiv çıxar"],
  },
  {
    term: "git submodule update --init",
    note: "Depoya bağlı alt modulları (submodule) ilk dəfə klonlayır və göstərilən commitə uyğunlaşdırır. clone edərkən --recurse-submodules unudulubsa sonradan bu işlədilir.",
    example: "git submodule update --init --recursive",
    section: "sazlama",
    match: ["alt modulu yüklə", "submodule başlat"],
  },
  {
    term: "git sparse-checkout",
    note: "Böyük bir depodan yalnız lazım olan qovluqları working directory-yə çıxarır, qalanını Git izləməyə davam etsə də diskə yazmır. Monorepo-nun bir hissəsi ilə işləyərkən yer və sürət qazandırır.",
    example: "git sparse-checkout set src/paket-a",
    section: "sazlama",
    match: ["qismən checkout", "yalnız bu qovluq"],
  },
];
