/*
 * The HTTP headers glossary — what a header does and when it shows up, with a
 * real value in `example` rather than a placeholder. Split by the direction
 * and the job: what the browser sends, what the server sends back, what
 * governs caching, what governs cross-origin access, what describes the body,
 * and what protects the page.
 */
import type { ReferenceRow, ReferenceSection } from "./reference";

export const httpBasliqlariSections: ReferenceSection[] = [
  {
    id: "sorgu",
    label: "Sorğu",
    hint: "Sorğu başlıqları — brauzerin serverə nə istədiyini və kim olduğunu bildirir.",
  },
  {
    id: "cavab",
    label: "Cavab",
    hint: "Cavab başlıqları — serverin sorğuya necə cavab verdiyini bildirir.",
  },
  {
    id: "kes",
    label: "Keş",
    hint: "Nüsxənin nə qədər saxlanılacağını və yenidən yoxlamanın necə aparılacağını təyin edir.",
  },
  {
    id: "tehlukesizlik",
    label: "Təhlükəsizlik",
    hint: "Brauzerə səhifənin hansı qaydalarla qorunacağını bildirir.",
  },
  {
    id: "mezmun",
    label: "Məzmun",
    hint: "Göndərilən gövdənin növünü, ölçüsünü və necə ötürüldüyünü təsvir edir.",
  },
  {
    id: "cors",
    label: "CORS",
    hint: "Başqa mənşədən gələn sorğulara icazə mexanizmi.",
  },
];

export const httpBasliqlariRows: ReferenceRow[] = [
  // sorgu
  {
    term: "Accept",
    section: "sorgu",
    note: "Brauzerin hansı məzmun növlərini (HTML, JSON, şəkil və s.) qəbul edə biləcəyini bildirir: server bir neçə format təklif edə bildiyi halda buna görə seçim edir.",
    example: "Accept: text/html,application/json;q=0.9",
    match: ["mezmun novu", "content negotiation"],
  },
  {
    term: "Accept-Encoding",
    section: "sorgu",
    note: "Brauzerin hansı sıxılma alqoritmlərini (gzip, br və s.) qəbul edə biləcəyini bildirir: server cavabı sıxıb ötürməzdən əvvəl bunu yoxlayır.",
    example: "Accept-Encoding: gzip, br",
    match: ["gzip", "sixilma", "compression"],
  },
  {
    term: "Accept-Language",
    section: "sorgu",
    note: "Brauzerin üstünlük verdiyi dilləri sadalayır: server tərcümə olunmuş versiya varsa hansını qaytaracağını bu siyahıya görə seçir.",
    example: "Accept-Language: az-AZ,az;q=0.9,en;q=0.5",
    match: ["dil sazlamasi", "language negotiation"],
  },
  {
    term: "Authorization",
    section: "sorgu",
    note: "Sorğunu göndərənin kimliyini sübut edən açarı daşıyır: Bearer token, Basic autentifikasiya və ya digər sxem burada gedir.",
    example: "Authorization: Bearer eyJhbGciOiJIUzI1NiIs...",
    match: ["bearer token", "auth header", "kimlik teyini"],
  },
  {
    term: "Cookie",
    section: "sorgu",
    note: "Bu domen üçün əvvəllər `Set-Cookie` ilə saxlanmış kukiləri serverə geri göndərir: sessiya və izləmə məlumatları belə ötürülür.",
    example: "Cookie: session_id=a1b2c3; theme=dark",
    match: ["kuki", "session cookie"],
  },
  {
    term: "Host",
    section: "sorgu",
    note: "Sorğunun hansı domenə ünvanlandığını bildirir: eyni IP ünvanda bir neçə saytın (virtual host) işləməsini mümkün edən başlıqdır, HTTP/1.1-də məcburidir.",
    example: "Host: camalali.com",
    match: ["virtual host", "domen basligi"],
  },
  {
    term: "Referer",
    section: "sorgu",
    note: 'Ziyarətçinin bu sorğuya hansı səhifədən keçdiyini bildirir. Orfoqrafiyası standartın özündə səhvdir: düzgünü "Referrer" olmalı idi, amma RFC 1945-də belə yazılıb və indi dəyişdirilə bilməz.',
    example: "Referer: https://camalali.com/bloq/http-basliqlari",
    match: ["referrer", "yönləndirən sehife", "orfoqrafik sehv"],
  },
  {
    term: "User-Agent",
    section: "sorgu",
    note: "Sorğunu göndərən proqramı (brauzer adı, versiyası, əməliyyat sistemi) təsvir edir. Server bununla bota və köhnə brauzerə fərqli cavab verə bilər.",
    example: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    match: ["brauzer melumati", "user agent string"],
  },
  {
    term: "X-Forwarded-For",
    section: "sorgu",
    note: "Sorğu bir proksi və ya yükləmə balanslayıcısından keçəndə orijinal müştərinin IP ünvanını daşıyır: olmasa server yalnız proksinin IP-sini görər.",
    example: "X-Forwarded-For: 203.0.113.4, 198.51.100.2",
    match: ["proksi ip", "real ip"],
  },
  {
    term: "Proxy-Authorization",
    section: "sorgu",
    note: "Sorğu aradakı bir proksi serverdən keçərkən ona öz kimliyini sübut etmək üçün göndərilir: son serverə çatan `Authorization`-dan ayrıdır.",
    example: "Proxy-Authorization: Basic cHJveHl1c2VyOnBhc3M=",
    match: ["proksi kimlik teyini"],
  },
  {
    term: "Forwarded",
    section: "sorgu",
    note: "X-Forwarded-* başlıqlarının standartlaşdırılmış versiyası: proksinin gördüyü müştəri IP-sini, protokolu və host adını tək başlıqda daşıyır.",
    example: "Forwarded: for=203.0.113.4;proto=https;host=camalali.com",
    match: ["proksi basligi", "rfc 7239"],
  },
  {
    term: "Sec-Fetch-Site",
    section: "sorgu",
    note: "Sorğunun hansı münasibətdən gəldiyini bildirir: eyni sayt, eyni mənşə, başqa sayt və ya birbaşa yazılan ünvan. Server bunu bilərək sorğunu qəbul edib-etməməyi qərarlaşdıra bilər.",
    example: "Sec-Fetch-Site: same-origin",
    match: ["fetch metadata", "same-origin"],
  },
  {
    term: "Sec-Fetch-Mode",
    section: "sorgu",
    note: "Sorğunun brauzer tərəfindən necə başladıldığını bildirir: naviqasiya, `fetch()`, şəkil yükləməsi və s. arasında fərq qoyur.",
    example: "Sec-Fetch-Mode: navigate",
    match: ["fetch metadata"],
  },
  {
    term: "Sec-Fetch-Dest",
    section: "sorgu",
    note: "Sorğunun nəticəsinin harada işlədiləcəyini bildirir: sənəd, şəkil, skript, iframe və s. Server bunu CSRF-ə qarşı filtrasiyada işlədə bilər.",
    example: "Sec-Fetch-Dest: document",
    match: ["fetch metadata"],
  },
  {
    term: "Upgrade-Insecure-Requests",
    section: "sorgu",
    note: "Brauzer HTTP ünvanına rast gəlsə belə onun HTTPS versiyasını üstün tutduğunu bildirir, qarışıq məzmun (mixed content) xəbərdarlığının qarşısını almaq üçün.",
    example: "Upgrade-Insecure-Requests: 1",
    match: ["https tercih", "mixed content"],
  },
  {
    term: "Expect",
    section: "sorgu",
    note: "Müştəri gövdəni göndərməzdən əvvəl serverin onu qəbul edib-etməyəcəyini soruşur: böyük yükləmələrdə boş yerə göndərməmək üçün `100-continue` ilə işlədilir.",
    example: "Expect: 100-continue",
    match: ["100-continue"],
  },
  {
    term: "Idempotency-Key",
    section: "sorgu",
    note: "Rəsmi standart deyil, amma ödəniş və sifariş API-lərində geniş qəbul edilib: müştəri eyni sorğunu təkrar göndərsə də əməliyyatın iki dəfə icra olunmamasını təmin edir.",
    example: "Idempotency-Key: 3f29a1e4-6b8d-4c2a-9e11-7d8f2b1c9a00",
    match: ["idempotentlik", "tekrar sorgu qorunmasi"],
  },
  {
    term: "X-Request-Id",
    section: "sorgu",
    note: "Rəsmi standart deyil, amma geniş yayılıb: sorğunu bütün sistemlər boyu izləmək üçün unikal id daşıyır, log-larda bir sorğunu tapmağı asanlaşdırır.",
    example: "X-Request-Id: 7c9e6679-7425-40de-944b-e07fc1f90ae7",
    match: ["request tracing", "correlation id"],
  },

  // kes
  {
    term: "Cache-Control",
    section: "kes",
    note: "Cavabın nə qədər müddət və hansı şərtlərlə keşlənə biləcəyini müəyyən edir. Ən çox işlədilən keş başlığıdır, həm brauzer, həm CDN buna baxır.",
    example: "Cache-Control: public, max-age=31536000, immutable",
    match: ["keşləmə", "max-age"],
  },
  {
    term: "ETag",
    section: "kes",
    note: "Resursun cari versiyasının barmaq izini daşıyır: məzmun dəyişəndə ETag da dəyişir, brauzer sonrakı sorğuda bunu `If-None-Match` ilə göndərib dəyişiklik olub-olmadığını soruşur.",
    example: 'ETag: "33a64df551425fcc55e"',
    match: ["fingerprint", "versiya izi"],
  },
  {
    term: "Expires",
    section: "kes",
    note: "Nüsxənin nə vaxta qədər təzə sayılacağı tarixini bildirir. `max-age` direktivi ilə eyni işi görür, amma daha köhnədir və ikisi birlikdə olanda `max-age` üstün tutulur.",
    example: "Expires: Wed, 21 Oct 2026 07:28:00 GMT",
    match: ["kohne kesleme", "expiry"],
  },
  {
    term: "If-None-Match",
    section: "kes",
    note: "Brauzer əvvəlki `ETag`-i geri göndərib serverə soruşur: bu hələ də doğrudurmu? Cavab dəyişməyibsə server 304 qaytarır və gövdəni yenidən göndərmir.",
    example: 'If-None-Match: "33a64df551425fcc55e"',
    match: ["serti sorgu", "conditional request"],
  },
  {
    term: "If-Modified-Since",
    section: "kes",
    note: "Brauzer nüsxəsinin tarixini göndərib soruşur: bundan sonra dəyişiklik olubmu? Dəyişməyibsə server 304 qaytarır. ETag olmadıqda işlədilən köhnə üsuldur.",
    example: "If-Modified-Since: Wed, 21 Oct 2026 07:28:00 GMT",
    match: ["serti sorgu", "conditional request"],
  },
  {
    term: "If-Match",
    section: "kes",
    note: "Sorğunun yalnız resursun göstərilən ETag-a uyğun cari versiyasında icra olunmasını tələb edir: bir yazının başqası tərəfindən eyni anda üzərinə yazılmasını (lost update) önləmək üçün PUT/PATCH-də işlədilir.",
    example: 'If-Match: "33a64df551425fcc55e"',
    match: ["optimistic locking", "eyni anda deyisiklik"],
  },
  {
    term: "Last-Modified",
    section: "kes",
    note: "Resursun serverdə son dəyişdirilmə tarixini bildirir: `If-Modified-Since` ilə edilən şərtli sorğuların müqayisə nöqtəsidir.",
    example: "Last-Modified: Wed, 21 Oct 2026 07:28:00 GMT",
    match: ["son deyisiklik tarixi"],
  },
  {
    term: "Vary",
    section: "kes",
    note: "Eyni URL üçün fərqli versiyaların hansı sorğu başlığına görə fərqləndiyini bildirir: `Vary: Accept-Encoding` desə, keş sıxılmış və sıxılmamış versiyanı ayrı saxlamalıdır.",
    example: "Vary: Accept-Encoding, Accept-Language",
    match: ["kes acari", "content negotiation"],
  },
  {
    term: "Age",
    section: "kes",
    note: "Cavabın aradakı keşdə (CDN, proksi) nə qədər müddətdir saxlandığını saniyə ilə bildirir: sıfırdan böyükdürsə cavab orijinal serverdən deyil, keşdən gəlib.",
    example: "Age: 3600",
    match: ["kes yasi", "cdn cache"],
  },

  // cors
  {
    term: "Origin",
    section: "cors",
    note: "Cross-origin sorğunu göndərən səhifənin sxem, domen və port üçlüyünü bildirir: server bu ünvana icazə verib-vermədiyinə görə CORS cavabını formalaşdırır.",
    example: "Origin: https://camalali.com",
    match: ["mensey", "cross-origin"],
  },
  {
    term: "Access-Control-Allow-Origin",
    section: "cors",
    note: "Serverin bu resursu hansı mənşədən (origin) gələn sorğulara açdığını bildirir: `*` hamıya açır, konkret domen isə yalnız ona icazə verir.",
    example: "Access-Control-Allow-Origin: https://camalali.com",
    match: ["cors icazesi"],
  },
  {
    term: "Access-Control-Allow-Credentials",
    section: "cors",
    note: "Cross-origin sorğuda kukilərin və `Authorization` başlığının göndərilə biləcəyini təsdiqləyir: `true` olanda `Access-Control-Allow-Origin` `*` ola bilmir, konkret domen tələb olunur.",
    example: "Access-Control-Allow-Credentials: true",
    match: ["kredensial", "cors kuki"],
  },
  {
    term: "Access-Control-Allow-Methods",
    section: "cors",
    note: "Cross-origin sorğuya hansı HTTP metodları ilə icazə verildiyini bildirir: brauzer bunu `OPTIONS` ilə edilən preflight sorğusunun cavabında oxuyur.",
    example: "Access-Control-Allow-Methods: GET, POST, PUT, DELETE",
    match: ["preflight", "cors metodlari"],
  },
  {
    term: "Access-Control-Allow-Headers",
    section: "cors",
    note: "Cross-origin sorğuda müştərinin göndərə biləcəyi xüsusi başlıqları sadalayır: `Authorization` kimi standart olmayan başlıq göndərilirsə server bunu burada açıq elan etməlidir.",
    example: "Access-Control-Allow-Headers: Content-Type, Authorization",
    match: ["preflight", "cors basliqlari"],
  },
  {
    term: "Access-Control-Max-Age",
    section: "cors",
    note: "Preflight sorğusunun nəticəsinin brauzer tərəfindən nə qədər müddət keşlənəcəyini bildirir: hər sorğudan əvvəl təkrar `OPTIONS` göndərilməsinin qarşısını alır.",
    example: "Access-Control-Max-Age: 86400",
    match: ["preflight kesi"],
  },

  // tehlukesizlik
  {
    term: "Content-Security-Policy",
    section: "tehlukesizlik",
    note: "Səhifənin hansı mənbələrdən skript, stil, şəkil yükləyə biləcəyini məhdudlaşdıran təhlükəsizlik başlığıdır. XSS həmləsində zərərli skriptin işə düşməsinin qarşısını alan ən güclü müdafiədir.",
    example: "Content-Security-Policy: default-src 'self'; script-src 'self' cdn.camalali.com",
    match: ["csp", "xss qorunmasi"],
  },
  {
    term: "Strict-Transport-Security",
    section: "tehlukesizlik",
    note: "Brauzerə bu domenlə yalnız HTTPS üzərindən danışmasını əmr edən təhlükəsizlik başlığıdır. `max-age` bitənə qədər brauzer HTTP ünvanına belə HTTPS-ə yönləndirər, downgrade həmləsini önləyir.",
    example: "Strict-Transport-Security: max-age=63072000; includeSubDomains",
    match: ["hsts", "https mecburi"],
  },
  {
    term: "X-Content-Type-Options",
    section: "tehlukesizlik",
    note: "Brauzerin `Content-Type`-ı təxmin edərək fərqli formatda icra etməsini (MIME sniffing) bağlayan təhlükəsizlik başlığıdır: yeganə dəyəri `nosniff`-dir.",
    example: "X-Content-Type-Options: nosniff",
    match: ["mime sniffing"],
  },
  {
    term: "X-Frame-Options",
    section: "tehlukesizlik",
    note: "Səhifənin başqa saytın `<iframe>`-i içində açıla bilib-bilməyəcəyini məhdudlaşdıran köhnə təhlükəsizlik başlığıdır. Clickjacking-ə qarşı qoruyur, müasir layihələrdə `Content-Security-Policy: frame-ancestors` ilə əvəz olunur.",
    example: "X-Frame-Options: SAMEORIGIN",
    match: ["clickjacking", "iframe qadagasi"],
  },
  {
    term: "Permissions-Policy",
    section: "tehlukesizlik",
    note: "Səhifənin kamera, mikrofon, coğrafi məkan kimi brauzer imkanlarından hansını, hansı mənşədən işlədə biləcəyini məhdudlaşdıran təhlükəsizlik başlığıdır.",
    example: "Permissions-Policy: geolocation=(), camera=()",
    match: ["feature policy", "brauzer icazeleri"],
  },
  {
    term: "Cross-Origin-Opener-Policy",
    section: "tehlukesizlik",
    note: "Səhifənin başqa mənşədən açılan pəncərələrlə eyni brauzinq qrupunu paylaşmasının qarşısını alan təhlükəsizlik başlığıdır: Spectre tipli yan-kanal həmlələrinə qarşı təcrid yaradır.",
    example: "Cross-Origin-Opener-Policy: same-origin",
    match: ["coop", "spectre qorunmasi"],
  },
  {
    term: "Cross-Origin-Resource-Policy",
    section: "tehlukesizlik",
    note: "Resursun başqa mənşədən `<script>`, `<img>` kimi teqlərlə yüklənib-yüklənə bilməyəcəyini məhdudlaşdıran təhlükəsizlik başlığıdır.",
    example: "Cross-Origin-Resource-Policy: same-site",
    match: ["corp"],
  },
  {
    term: "Cross-Origin-Embedder-Policy",
    section: "tehlukesizlik",
    note: "Səhifənin özünün yalnız açıq şəkildə icazə verən (CORP və ya CORS başlığı olan) resursları yükləməsini məcbur edən təhlükəsizlik başlığıdır: `SharedArrayBuffer` kimi güclü imkanlar üçün brauzer bunu tələb edir.",
    example: "Cross-Origin-Embedder-Policy: require-corp",
    match: ["coep"],
  },
  {
    term: "WWW-Authenticate",
    section: "tehlukesizlik",
    note: "Server 401 cavabı ilə birlikdə hansı autentifikasiya sxeminin (Basic, Bearer, Digest) gözlənildiyini bildirən təhlükəsizlik başlığıdır.",
    example: 'WWW-Authenticate: Basic realm="Admin"',
    match: ["401 basligi", "auth scheme"],
  },
  {
    term: "X-Powered-By",
    section: "tehlukesizlik",
    note: "Serverin işlətdiyi texnologiyanı (Express, PHP versiyası və s.) açıq edən qeyri-standart başlıqdır. Təhlükəsizlik baxımından tövsiyə olunmur, çünki hücumçuya konkret zəifliyi axtarmaq üçün istiqamət verir.",
    example: "X-Powered-By: Express",
    match: ["texnologiya sizmasi", "fingerprinting"],
  },
  {
    term: "X-XSS-Protection",
    section: "tehlukesizlik",
    note: "Köhnə brauzerlərin daxili XSS filtrini idarə edirdi: özü zəiflik mənbəyi olduğu üçün müasir brauzerlər tərəfindən artıq nəzərə alınmır, yerini `Content-Security-Policy` tutub.",
    example: "X-XSS-Protection: 0",
    match: ["kohnelmis basliq", "xss filter"],
  },

  // mezmun
  {
    term: "Content-Type",
    section: "mezmun",
    note: "Gövdənin məzmun növünü və (mətn üçün) kodlaşdırmasını bildirir: brauzer bunu JSON kimi parse edəcəyini yoxsa şəkil kimi göstərəcəyini bu başlığa görə qərar verir.",
    example: "Content-Type: application/json; charset=utf-8",
    match: ["mime type", "content type"],
  },
  {
    term: "Content-Length",
    section: "mezmun",
    note: "Gövdənin bayt ölçüsünü bildirir: müştəri bununla cavabın nə vaxt tam alındığını bilir, `Transfer-Encoding: chunked` işlədiləndə lazım deyil.",
    example: "Content-Length: 1024",
    match: ["govde olcusu"],
  },
  {
    term: "Content-Encoding",
    section: "mezmun",
    note: "Gövdənin hansı alqoritmlə (gzip, br, deflate) sıxıldığını bildirir: müştəri onu göstərmədən əvvəl bu alqoritmlə açmalıdır.",
    example: "Content-Encoding: br",
    match: ["sixilma novu"],
  },
  {
    term: "Content-Disposition",
    section: "mezmun",
    note: "Cavabın brauzerdə birbaşa göstəriləcəyini yoxsa fayl kimi yüklənəcəyini bildirir: `attachment` yükləmə pəncərəsini açır, faylın adını da bu başlıqda vermək olur.",
    example: 'Content-Disposition: attachment; filename="hesabat.pdf"',
    match: ["fayl yuklemesi", "download"],
  },
  {
    term: "Content-Language",
    section: "mezmun",
    note: "Gövdənin hansı təbii dildə yazıldığını bildirir. `Accept-Language` ilə qarışdırılmasın, o sorğu tərəfindədir, bu isə cavabın özünün dilini elan edir.",
    example: "Content-Language: az",
    match: ["dil basligi"],
  },
  {
    term: "Range",
    section: "mezmun",
    note: "Müştərinin resursun tam deyil, yalnız müəyyən bayt aralığını istədiyini bildirir: fasilədən sonra yükləməni davam etdirmək və video axını üçün işlədilir.",
    example: "Range: bytes=1024-2047",
    match: ["hisseli yukleme", "byte range"],
  },
  {
    term: "Accept-Ranges",
    section: "mezmun",
    note: "Serverin bayt aralığı ilə edilən sorğuları (`Range`) dəstəklədiyini bildirir: dəstəkləmirsə `none`, dəstəkləyirsə vahidi (`bytes`) qaytarır.",
    example: "Accept-Ranges: bytes",
    match: ["range destegi"],
  },
  {
    term: "Transfer-Encoding",
    section: "mezmun",
    note: "Gövdənin ötürülmə üsulunu bildirir: `chunked` olanda gövdə ölçüsü əvvəlcədən bilinmir, kiçik parçalar halında ardıcıl göndərilir.",
    example: "Transfer-Encoding: chunked",
    match: ["chunked", "parcali gonderme"],
  },
  {
    term: "TE",
    section: "mezmun",
    note: "Müştərinin `Transfer-Encoding` üçün hansı əlavə kodlaşdırmaları (`trailers` kimi) qəbul edə biləcəyini bildirir: `Accept-Encoding`-in ötürmə səviyyəsindəki qarşılığıdır.",
    example: "TE: trailers",
    match: ["transfer encoding qebulu"],
  },
  {
    term: "Trailer",
    section: "mezmun",
    note: "Gövdə `chunked` göndəriləndə, gövdədən sonra hansı əlavə başlıqların (məsələn yekun kontrol cəmi) gələcəyini əvvəlcədən bildirir.",
    example: "Trailer: Content-MD5",
    match: ["chunked trailer"],
  },

  // cavab
  {
    term: "Set-Cookie",
    section: "cavab",
    note: "Serverin brauzerdə yeni kuki saxlamasını əmr edir: müddət, domen, `Secure` və `HttpOnly` kimi şərtlər eyni başlıqda gəlir, brauzer sonrakı sorğularda bunu `Cookie` ilə geri göndərir.",
    example: "Set-Cookie: session_id=a1b2c3; HttpOnly; Secure; SameSite=Lax",
    match: ["kuki qoyma"],
  },
  {
    term: "Location",
    section: "cavab",
    note: "Yönləndirmə (3xx) və ya yeni yaradılan resurs (201) cavabında hara baxılacağını bildirir: brauzer avtomatik yönləndirmədə birbaşa bu ünvana gedir.",
    example: "Location: https://camalali.com/bloq/yeni-yazi",
    match: ["yonlendirme unvani"],
  },
  {
    term: "Referrer-Policy",
    section: "cavab",
    note: "Bu səhifədən başqa ünvana keçiddə `Referer` başlığında nə qədər məlumatın (tam URL, yalnız domen, heç nə) göndəriləcəyini idarə edir.",
    example: "Referrer-Policy: strict-origin-when-cross-origin",
    match: ["referer siyaseti"],
  },
  {
    term: "Retry-After",
    section: "cavab",
    note: "429 və ya 503 kimi müvəqqəti xəta cavablarında müştəriyə nə qədər (saniyə və ya tarix) gözləyib yenidən cəhd etməli olduğunu bildirir.",
    example: "Retry-After: 120",
    match: ["yenidən cehd", "rate limit gozleme"],
  },
  {
    term: "Server",
    section: "cavab",
    note: "Cavabı hazırlayan server proqramını bildirir: bəzi layihələr bu başlığı qəsdən boşaldır ki, hücumçuya versiya məlumatı verilməsin.",
    example: "Server: nginx/1.29.0",
    match: ["server melumati"],
  },
  {
    term: "Connection",
    section: "cavab",
    note: "TCP bağlantısının sorğudan sonra açıq saxlanılıb-saxlanılmayacağını idarə edir: `keep-alive` eyni bağlantıdan növbəti sorğular üçün istifadəyə imkan verir, HTTP/2-də mənası yoxdur.",
    example: "Connection: keep-alive",
    match: ["baglanti idaresi", "keep-alive"],
  },
  {
    term: "Link",
    section: "cavab",
    note: "Cavabla əlaqəli başqa resursları göstərir: səhifələndirmədə növbəti/əvvəlki səhifəni, ya da bir resursun `preload` ediləcəyini bu başlıqla bildirmək olar.",
    example: 'Link: <https://camalali.com/bloq?page=2>; rel="next"',
    match: ["pagination header", "preload link"],
  },
  {
    term: "Alt-Svc",
    section: "cavab",
    note: "Eyni resursun başqa protokol və ya portla (məsələn HTTP/3, QUIC) da əlçatan olduğunu bildirir: brauzer sonrakı sorğularda daha sürətli yolu sınayır.",
    example: 'Alt-Svc: h3=":443"; ma=86400',
    match: ["http3", "quic"],
  },
  {
    term: "Upgrade",
    section: "cavab",
    note: "Müştərinin bağlantını başqa protokola (məsələn WebSocket-ə) keçirmək istədiyini bildirir: server bunu `101 Switching Protocols` ilə qəbul edir.",
    example: "Upgrade: websocket",
    match: ["protokol yukseltmesi"],
  },
  {
    term: "Warning",
    section: "cavab",
    note: "Cavabla bağlı əlavə xəbərdarlıq daşıyırdı, məsələn keşdəki nüsxənin köhnə ola biləcəyini bildirmək üçün. HTTP/1.1-dən sonra köhnəlmiş elan olunub, müasir API-lər bunun yerinə öz xəta formatını işlədir.",
    example: 'Warning: 110 - "Response is Stale"',
    match: ["kohnelmis basliq"],
  },
  {
    term: "Date",
    section: "cavab",
    note: "Cavabın serverdə hazırlandığı tarix və saatı bildirir: keş müddətinin hesablanmasında və saat fərqinin diaqnozunda istinad nöqtəsidir.",
    example: "Date: Wed, 21 Oct 2026 07:28:00 GMT",
    match: ["server saati"],
  },
];
