/*
 * The rows for the `linux-emrleri` reference table — the everyday shell
 * commands, one per row, with what each does, when it is reached for and a
 * line that actually runs. React-free, same as every other reference table's
 * data file: the drawing lives in `reference-table.tsx`, this file only holds
 * the list.
 */
import type { ReferenceRow, ReferenceSection } from "./reference.js";

export const linuxEmrleriSections: ReferenceSection[] = [
  { id: "fayl", label: "Fayl və qovluq" },
  { id: "metn", label: "Mətn və axtarış" },
  { id: "proses", label: "Proses" },
  { id: "sebeke", label: "Şəbəkə" },
  { id: "disk", label: "Disk və yer" },
  { id: "icaze", label: "İcazə və sahiblik" },
  { id: "paket", label: "Paket və xidmət" },
  { id: "sistem", label: "Sistem və istifadəçi" },
];

export const linuxEmrleriRows: ReferenceRow[] = [
  /* ---------- fayl ---------- */
  {
    term: "ls",
    note: "Qovluqdakı fayl və alt-qovluqları sadalayır. Heç bir arqument olmadan cari qovluğu göstərir.",
    section: "fayl",
    example: "ls",
    match: ["fayl siyahısı", "qovluğu göstər"],
  },
  {
    term: "ls -la",
    note: "Gizli faylları (nöqtə ilə başlayanlar) da qatır və hər sətirdə ölçü, icazə, sahib və tarixi göstərir.",
    section: "fayl",
    example: "ls -la /etc",
    match: ["gizli fayl", "ətraflı siyahı"],
  },
  {
    term: "cd",
    note: "İşlədiyin qovluğu dəyişir. Arqumentsiz ev qovluğuna, `cd -` isə əvvəlki qovluğa qaytarır.",
    section: "fayl",
    example: "cd /var/log",
    match: ["qovluğa keç", "directory dəyiş"],
  },
  {
    term: "pwd",
    note: "Hazırda hansı qovluqda olduğunu tam yolla göstərir: simvolik keçidlərdən sonra itəndə kömək edir.",
    section: "fayl",
    example: "pwd",
    match: ["cari qovluq", "haradayam"],
  },
  {
    term: "mkdir -p",
    note: "Yeni qovluq yaradır və yolda çatışmayan ara qovluqları da özü açır, ona görə xəta vermir.",
    section: "fayl",
    example: "mkdir -p layihe/src/components",
    match: ["qovluq yarat", "iç-içə qovluq"],
  },
  {
    term: "rm",
    note: "Faylı silir. Silinən fayl zibil qutusuna getmir, geri qaytarılmır.",
    section: "fayl",
    example: "rm köhnə-fayl.txt",
    match: ["fayl sil"],
  },
  {
    term: "rm -rf",
    note: "TƏHLÜKƏLİDİR: qovluğu içindəkilərlə birgə, heç bir sual vermədən və geri qaytarılmadan silir. Yolu iki dəfə yoxlamadan işlətmə, xüsusən kök qovluğa yaxın yerdə.",
    section: "fayl",
    example: "rm -rf node_modules",
    match: ["qovluğu sil", "zorla sil", "hamısını sil"],
  },
  {
    term: "cp",
    note: "Faylı başqa yerə və ya yeni adla köçürür, orijinal öz yerində qalır.",
    section: "fayl",
    example: "cp config.yaml config.backup.yaml",
    match: ["fayl köçür", "surət çıxar"],
  },
  {
    term: "cp -r",
    note: "Qovluğu içindəkilərlə birlikdə tam köçürür. Sadə `cp` qovluq üzərində xəta verir.",
    section: "fayl",
    example: "cp -r layihe/ layihe-yedek/",
    match: ["qovluq köçür", "rekursiv köçür"],
  },
  {
    term: "mv",
    note: "Faylı başqa yerə daşıyır və ya adını dəyişir: eyni əməliyyat, fərq yalnız hədəf yoldadır.",
    section: "fayl",
    example: "mv qeyd.txt arxiv/qeyd-2026.txt",
    match: ["ad dəyiş", "daşı", "rename"],
  },
  {
    term: "touch",
    note: "Boş fayl yaradır, fayl artıq varsa onun dəyişdirmə tarixini indiki vaxta yeniləyir.",
    section: "fayl",
    example: "touch README.md",
    match: ["boş fayl yarat"],
  },
  {
    term: "ln -s",
    note: "Simvolik keçid (shortcut) yaradır. Orijinal fayl silinsə keçid qırıq qalır.",
    section: "fayl",
    example: "ln -s /opt/app/config.yaml ./config.yaml",
    match: ["symlink", "keçid yarat", "qısayol"],
  },
  {
    term: "find",
    note: "Qovluq ağacında ad, ölçü, tarix və ya növünə görə fayl axtarır, `ls`-dən fərqli olaraq alt-qovluqlara enir.",
    section: "fayl",
    example: "find . -type f -mtime -1",
    match: ["fayl tap", "axtarış"],
  },
  {
    term: "find -name",
    note: "Ada görə axtarır, `*` joker kimi işləyir. Nəticə həmişə tam yolla göstərilir.",
    section: "fayl",
    example: 'find . -name "*.log"',
    match: ["ada görə fayl tap"],
  },
  {
    term: "find -exec",
    note: "Tapılan hər faylın üzərində başqa əmr işə salır: `{}` tapılan faylın yerinə, `\\;` isə əmrin sonuna qoyulur.",
    section: "fayl",
    example: 'find . -name "*.tmp" -exec rm {} \\;',
    match: ["tapılanı sil", "toplu əməliyyat"],
  },
  {
    term: "locate",
    note: "Əvvəlcədən qurulmuş indeksdən axtarır, `find`-dan qat-qat sürətlidir, amma indeks köhnəlmiş ola bilər (`updatedb` yeniləyir).",
    section: "fayl",
    example: "locate nginx.conf",
    match: ["sürətli fayl axtarışı"],
  },
  {
    term: "tree",
    note: "Qovluq quruluşunu budaqlanan ağac şəklində çəkir, layihənin quruluşunu bir baxışda görmək üçün.",
    section: "fayl",
    example: "tree -L 2 src/",
    match: ["qovluq ağacı", "struktur göstər"],
  },
  {
    term: "stat",
    note: "Faylın ölçüsünü, icazələrini, sahibini və üç tarixini (dəyişmə, giriş, dəyişdirmə) ətraflı göstərir.",
    section: "fayl",
    example: "stat /etc/hosts",
    match: ["fayl detalları", "metadata"],
  },
  {
    term: "file",
    note: "Faylın həqiqi növünü məzmununa baxaraq deyir. Uzantı yanlış və ya heç yoxdursa belə işləyir.",
    section: "fayl",
    example: "file logo.png",
    match: ["fayl növü", "mime tipi"],
  },
  {
    term: "basename/dirname",
    note: "`basename` yolun son hissəsini (fayl adını), `dirname` isə fayla qədərki qovluğu qaytarır, skriptlərdə yol parçalamaq üçün.",
    section: "fayl",
    example: "basename /var/log/nginx/error.log",
    match: ["yol parçala", "fayl adını çıxar"],
  },

  /* ---------- metn ---------- */
  {
    term: "cat",
    note: "Faylın bütün məzmununu terminala tökür. Bir neçə fayl versən onları ardıcıl birləşdirib çıxarır.",
    section: "metn",
    example: "cat /etc/os-release",
    match: ["faylı göstər", "faylı oxu"],
  },
  {
    term: "less",
    note: "Böyük faylı səhifə-səhifə açır, hamısını yaddaşa yükləmir. `/söz` ilə axtarır, `q` ilə çıxır.",
    section: "metn",
    example: "less /var/log/syslog",
    match: ["böyük faylı oxu", "səhifələ"],
  },
  {
    term: "head",
    note: "Faylın ilk 10 sətrini göstərir: `-n` ilə sayı dəyişmək olar. Böyük faylın başına tez baxmaq üçün.",
    section: "metn",
    example: "head -n 20 access.log",
    match: ["ilk sətirlər"],
  },
  {
    term: "tail",
    note: "Faylın son 10 sətrini göstərir. `-n` ilə sayı dəyişmək olar. Ən son log qeydlərinə baxmaq üçün.",
    section: "metn",
    example: "tail -n 50 error.log",
    match: ["son sətirlər"],
  },
  {
    term: "tail -f",
    note: "Faylın sonuna gedir və yeni sətir yazıldıqca ekranda göstərməyə davam edir, canlı logu izləmək üçün. `Ctrl+C` ilə dayanır.",
    section: "metn",
    example: "tail -f /var/log/nginx/access.log",
    match: ["canlı log izlə", "follow"],
  },
  {
    term: "grep",
    note: "Mətndə və ya faylda müəyyən sözü axtarıb tapan sətirləri çıxarır.",
    section: "metn",
    example: 'grep "ERROR" app.log',
    match: ["mətndə axtar", "sətir tap"],
  },
  {
    term: "grep -r",
    note: "Qovluğun içindəki bütün faylları, alt-qovluqlar daxil, ardıcıl axtarır, bir kod bazasında söz axtaranda ən çox işlədilən forma.",
    section: "metn",
    example: 'grep -rn "TODO" src/',
    match: ["qovluqda axtar", "rekursiv axtarış", "kodda axtar"],
  },
  {
    term: "grep -v",
    note: "Uyğun gələn sətirləri yox, uyğun GƏLMƏYƏN sətirləri göstərir, bir naxışı nəticədən çıxarmaq üçün.",
    section: "metn",
    example: 'ps aux | grep node | grep -v grep',
    match: ["əksini göstər", "istisna et"],
  },
  {
    term: "egrep/grep -E",
    note: "Genişləndirilmiş regex sintaksisinə icazə verir: `(a|b)`, `+`, `{2,3}` kimi işarələri qaçırmadan yazmaq olur.",
    section: "metn",
    example: 'grep -E "ERROR|WARN" app.log',
    match: ["genişləndirilmiş regex"],
  },
  {
    term: "sed",
    note: "Axan mətndə axtar-dəyiş əməliyyatı aparır, orijinal faylı dəyişmir, nəticəni ekrana yazır.",
    section: "metn",
    example: "sed 's/http:/https:/' url.txt",
    match: ["axtar dəyiş", "mətni redaktə et"],
  },
  {
    term: "sed -i",
    note: "Axtar-dəyişi birbaşa faylın üzərində edir. `-i.bak` versə əvvəlcə ehtiyat nüsxə də saxlayır.",
    section: "metn",
    example: 'sed -i "s/dev/prod/g" .env',
    match: ["faylı yerindəcə dəyiş"],
  },
  {
    term: "awk",
    note: "Mətni sütunlara bölüb üzərində işləyir: loglardan konkret sütunu çıxarmaq, cəmləmək üçün əvəzsizdir.",
    section: "metn",
    example: "awk '{print $1}' access.log",
    match: ["sütun ayır", "mətni işlə"],
  },
  {
    term: "cut",
    note: "Sətirdən müəyyən sütunu ya da simvol aralığını kəsib çıxarır (`awk`-dan sadə, bir ayırıcı kifayət olanda).",
    section: "metn",
    example: "cut -d: -f1 /etc/passwd",
    match: ["sütun kəs"],
  },
  {
    term: "sort",
    note: "Sətirləri əlifba və ya rəqəm sırasına düzür: `-n` rəqəmlə, `-r` tərsinə sıralayır.",
    section: "metn",
    example: "sort -n rəqəmlər.txt",
    match: ["sırala"],
  },
  {
    term: "sort -u",
    note: "Sıralayır və eyni zamanda təkrarlanan sətirləri təmizləyir, `sort | uniq` ilə eynidir, tək əmrdə.",
    section: "metn",
    example: "sort -u domenler.txt",
    match: ["təkrarları sil", "unikal sırala"],
  },
  {
    term: "uniq -c",
    note: "Ardıcıl təkrarlanan sətirləri birləşdirib neçə dəfə təkrarlandığını qarşısına yazır. Əvvəlcə `sort` etmək lazımdır.",
    section: "metn",
    example: "sort access.log | awk '{print $1}' | uniq -c | sort -rn",
    match: ["neçə dəfə təkrarlanıb", "tezlik say"],
  },
  {
    term: "wc -l",
    note: "Sətir sayını verir, faylda neçə qeyd, sorğuda neçə nəticə olduğunu tez öyrənmək üçün.",
    section: "metn",
    example: "cat access.log | wc -l",
    match: ["sətir say"],
  },
  {
    term: "tr",
    note: "Bir simvol dəstini başqasına çevirir, böyük hərfi kiçiyə salmaq, yeni sətri vergüllə əvəz etmək kimi.",
    section: "metn",
    example: "cat ad.txt | tr 'A-Z' 'a-z'",
    match: ["simvol dəyiş", "hərfləri çevir"],
  },
  {
    term: "diff",
    note: "İki faylı sətir-sətir müqayisə edib fərqi göstərir: hansı sətir əlavə olunub, hansı silinib.",
    section: "metn",
    example: "diff köhne.conf yeni.conf",
    match: ["faylları müqayisə et", "fərqi göstər"],
  },
  {
    term: "comm",
    note: "İki sıralanmış faylı müqayisə edib üç sütunda göstərir: yalnız birincidə, yalnız ikincidə, hər ikisində olanlar.",
    section: "metn",
    example: "comm -12 siyahi1.txt siyahi2.txt",
    match: ["ortaq sətirlər", "iki siyahını müqayisə et"],
  },
  {
    term: "xargs",
    note: "Bir əmrin çıxışını başqa əmrin arqumentinə çevirir, `find` ilə tapılan yüzlərlə faylı tək-tək yox, toplu işləmək üçün.",
    section: "metn",
    example: 'find . -name "*.log" | xargs rm',
    match: ["nəticəni arqumentə çevir", "toplu işlə"],
  },
  {
    term: "tee",
    note: "Girişi eyni anda həm ekrana yazır, həm də fayla saxlayır, boru xəttinin ortasında nəticəyə baxmaq üçün.",
    section: "metn",
    example: "ls -la | tee siyahi.txt",
    match: ["həm göstər həm saxla"],
  },

  /* ---------- proses ---------- */
  {
    term: "ps aux",
    note: "Sistemdəki bütün prosesləri, sahibini, yaddaş və CPU istifadəsini bir cədvəldə göstərir.",
    section: "proses",
    example: "ps aux | grep node",
    match: ["proses siyahısı", "işləyən proqramlar"],
  },
  {
    term: "top",
    note: "Prosesləri CPU istifadəsinə görə canlı yeniləyən cədvəldə göstərir: hansı proses maşını yükləyir.",
    section: "proses",
    example: "top",
    match: ["canlı proses monitoru", "yük göstər"],
  },
  {
    term: "htop",
    note: "`top`-un rəngli, siçanla idarə olunan versiyası (çox vaxt ayrıca quraşdırılmalıdır).",
    section: "proses",
    example: "htop",
    match: ["rəngli proses monitoru"],
  },
  {
    term: "kill",
    note: "Prosesə PID-i ilə sonlanma siqnalı (SIGTERM) göndərir. Proses özü təmiz bağlanmağa cəhd edir.",
    section: "proses",
    example: "kill 4821",
    match: ["prosesi dayandır", "prosesi öldür"],
  },
  {
    term: "kill -9",
    note: "SON ÇARƏDİR: SIGKILL göndərir, proses təmizlik aparmadan dərhal ölür. Yalnız adi `kill` işləmədikdə işlət. Yarımçıq qalan fayl və kilidlər ola bilər.",
    section: "proses",
    example: "kill -9 4821",
    match: ["prosesi zorla öldür", "prosesi öldür", "sigkill"],
  },
  {
    term: "killall",
    note: "PID yox, proses adı ilə axtarır və eyni addakı bütün prosesləri sonlandırır.",
    section: "proses",
    example: "killall node",
    match: ["ada görə prosesi öldür", "prosesi öldür"],
  },
  {
    term: "pkill",
    note: "Ada uyğun naxışla prosesi tapıb sonlandırır, `killall`-dan fərqli olaraq qismən uyğunluğu da qəbul edir.",
    section: "proses",
    example: "pkill -f 'node server.js'",
    match: ["naxışla prosesi öldür", "prosesi öldür"],
  },
  {
    term: "jobs",
    note: "Cari terminalda arxa plana atılmış (`&` ilə başladılmış) prosesləri sadalayır.",
    section: "proses",
    example: "jobs",
    match: ["arxa plan prosesləri"],
  },
  {
    term: "bg",
    note: "`Ctrl+Z` ilə dayandırılmış prosesi arxa planda davam etdirir, terminal boşalır.",
    section: "proses",
    example: "bg %1",
    match: ["arxa plana at"],
  },
  {
    term: "fg",
    note: "Arxa planda işləyən prosesi ön plana, yəni terminalın idarəsinə qaytarır.",
    section: "proses",
    example: "fg %1",
    match: ["ön plana gətir"],
  },
  {
    term: "nohup",
    note: "Terminal bağlansa belə prosesin işləməyə davam etməsini təmin edir, SSH sessiyası kəsiləndə uzun işi qorumaq üçün.",
    section: "proses",
    example: "nohup ./yigim.sh &",
    match: ["terminal bağlananda davam et"],
  },
  {
    term: "systemctl status",
    note: "Xidmətin işlək olub-olmadığını, son loglarını və avtomatik başlama vəziyyətini göstərir.",
    section: "proses",
    example: "systemctl status nginx",
    match: ["xidmət vəziyyəti", "servis işləyirmi"],
  },
  {
    term: "systemctl start",
    note: "Systemd xidmətini indi işə salır. Kompüter yenidən başlayanda avtomatik başlamır, bunun üçün `enable` lazımdır.",
    section: "proses",
    example: "systemctl start nginx",
    match: ["xidməti başlat"],
  },
  {
    term: "systemctl stop",
    note: "Systemd xidmətini dayandırır. Yenidən açılana qədər (və ya növbəti reboot-a qədər `enable`-dırsa) söndürülmüş qalır.",
    section: "proses",
    example: "systemctl stop nginx",
    match: ["xidməti dayandır"],
  },
  {
    term: "systemctl restart",
    note: "Xidməti dayandırıb dərhal yenidən başladır, konfiqurasiya dəyişikliyindən sonra tətbiq etmək üçün ən çox işlədilən forma.",
    section: "proses",
    example: "systemctl restart nginx",
    match: ["xidməti yenidən başlat"],
  },
  {
    term: "systemctl enable",
    note: "Xidməti sistem açılanda avtomatik başlamağa qurur. Özü indi başlatmır, `--now` versən ikisini birdən edir.",
    section: "proses",
    example: "systemctl enable --now nginx",
    match: ["açılışda başlat", "avtomatik başlat"],
  },
  {
    term: "journalctl -u",
    note: "Sadəcə bir systemd xidmətinin loglarını süzüb göstərir, bütün sistem jurnalı arasında itmədən.",
    section: "proses",
    example: "journalctl -u nginx",
    match: ["xidmət logları"],
  },
  {
    term: "journalctl -f",
    note: "Systemd jurnalını `tail -f` kimi canlı izləyir: yeni qeyd yazıldıqca ekranda görünür.",
    section: "proses",
    example: "journalctl -u nginx -f",
    match: ["canlı jurnal izlə"],
  },
  {
    term: "service",
    note: "Systemd-dən əvvəlki, daha köhnə xidmət idarə əmri. Yeni sistemlərdə `systemctl`-ə yönləndirilir.",
    section: "proses",
    example: "service nginx restart",
    match: ["köhnə xidmət idarəsi"],
  },
  {
    term: "crontab -e",
    note: "İstifadəçinin təkrarlanan tapşırıq cədvəlini (cron) redaktə edir: hər sətir bir tapşırıqdır, vaxt + əmr.",
    section: "proses",
    example: "crontab -e",
    match: ["cron redaktə et", "planlaşdırılmış tapşırıq"],
  },
  {
    term: "at",
    note: "Bir dəfəlik, gələcəkdə konkret vaxtda işə düşəcək tapşırıq planlaşdırır, cron təkrarlanan üçündür, `at` isə tək dəfəlik üçün.",
    section: "proses",
    example: 'echo "systemctl restart nginx" | at 03:00',
    match: ["bir dəfəlik tapşırıq"],
  },

  /* ---------- sebeke ---------- */
  {
    term: "curl",
    note: "URL-ə HTTP sorğusu göndərib cavabı terminala çıxarır, API-ni tez sınamaq üçün ən çox işlədilən əmr.",
    section: "sebeke",
    example: "curl https://api.example.com/status",
    match: ["http sorğu göndər", "api sına"],
  },
  {
    term: "curl -I",
    note: "Cavabın gövdəsini yükləmədən yalnız HTTP başlıqlarını göstərir, status kodunu, keş başlıqlarını yoxlamaq üçün.",
    section: "sebeke",
    example: "curl -I https://example.com",
    match: ["yalnız başlıqları göstər", "status kodunu yoxla"],
  },
  {
    term: "wget",
    note: "URL-dən faylı birbaşa diskə endirir, `curl`-dan fərqli olaraq nəticəsi standart olaraq fayldır, terminal çıxışı deyil.",
    section: "sebeke",
    example: "wget https://example.com/qurulum.tar.gz",
    match: ["fayl endir"],
  },
  {
    term: "ping",
    note: "Hədəfə kiçik paketlər göndərib cavab vaxtını ölçür, şəbəkə əlaqəsinin ümumiyyətlə olub-olmadığını yoxlamaq üçün ilk addım.",
    section: "sebeke",
    example: "ping 8.8.8.8",
    match: ["əlaqəni yoxla", "gecikməni ölç"],
  },
  {
    term: "traceroute",
    note: "Paketin hədəfə çatana qədər keçdiyi hər marşrutlayıcını sadalayır: gecikmə harada yaranır, harada dayanır göstərir.",
    section: "sebeke",
    example: "traceroute example.com",
    match: ["marşrutu göstər", "haradan keçir"],
  },
  {
    term: "dig",
    note: "DNS sorğusunu ətraflı, ham cavabla göstərir, A, MX, TXT qeydlərini yoxlamaq üçün əsas alət.",
    section: "sebeke",
    example: "dig example.com MX",
    match: ["dns sorğu", "domen qeydini yoxla"],
  },
  {
    term: "nslookup",
    note: "DNS-i sadə formada sorğulayır. `dig`-dən qısa çıxış verir, sürətli baxış üçün kifayət edir.",
    section: "sebeke",
    example: "nslookup example.com",
    match: ["dns sorğu"],
  },
  {
    term: "host",
    note: "Domendən IP-yə və ya IP-dən domenə ən sadə DNS çevrilməsini verir (`dig`-in yığcam qardaşı).",
    section: "sebeke",
    example: "host example.com",
    match: ["dns çevirmə"],
  },
  {
    term: "ss -tulpn",
    note: "Hansı portun açıq olduğunu və hansı prosesin ona qulaq asdığını göstərir. `netstat`-ın yerini tutub, çünki kernel məlumatını birbaşa oxuyur və böyük sistemdə xeyli sürətlidir.",
    section: "sebeke",
    example: "ss -tulpn",
    match: ["açıq portlar", "port kim dinləyir"],
  },
  {
    term: "netstat",
    note: "`ss`-dən əvvəlki, köhnə şəbəkə bağlantı əmri. Bir çox dağıtımda artıq quraşdırılmır, indi `ss` üstünlük verilən əvəzedicidir.",
    section: "sebeke",
    example: "netstat -tulpn",
    match: ["açıq portlar", "köhnə port yoxlaması"],
  },
  {
    term: "ip a",
    note: "Maşındakı bütün şəbəkə interfeyslərini və onlara verilmiş IP ünvanlarını göstərir. Köhnə `ifconfig`-in yerini tutur.",
    section: "sebeke",
    example: "ip a",
    match: ["ip ünvanını göstər", "interfeys siyahısı"],
  },
  {
    term: "ip r",
    note: "Marşrutlama cədvəlini göstərir: trafik hansı şlüzdən çıxır, defolt marşrut hansıdır.",
    section: "sebeke",
    example: "ip r",
    match: ["marşrutlama cədvəli", "default gateway"],
  },
  {
    term: "ifconfig",
    note: "İnterfeys və IP ünvanını göstərən köhnə əmr. Çoxu dağıtımda artıq yoxdur, əvəzinə `ip a` işlədilir.",
    section: "sebeke",
    example: "ifconfig",
    match: ["köhnə ip əmri"],
  },
  {
    term: "nc",
    note: "İki maşın arasında xam TCP/UDP bağlantı açır, port açıqdırmı yoxlamaq, kiçik fayl ötürmək kimi işlərdə.",
    section: "sebeke",
    example: "nc -zv example.com 443",
    match: ["port yoxla", "netcat"],
  },
  {
    term: "scp",
    note: "SSH üzərindən fayl köçürür: sintaksisi `cp`-yə bənzəyir, sadəcə hədəf `istifadəçi@host:yol` formasındadır.",
    section: "sebeke",
    example: "scp qeyd.txt user@server:/home/user/",
    match: ["ssh ilə fayl köçür", "uzaq serverə fayl göndər"],
  },
  {
    term: "rsync -av",
    note: "Fayl köçürür, amma yalnız dəyişən hissəni ötürür. Böyük qovluğu təkrar sinxronlaşdırmaq `scp`-dən qat-qat sürətlidir.",
    section: "sebeke",
    example: "rsync -av layihe/ user@server:/var/www/layihe/",
    match: ["sinxronlaşdır", "yalnız fərqi köçür"],
  },
  {
    term: "ssh",
    note: "Uzaq serverə şifrəli terminal sessiyası açır (server idarəsinin əsas girişi).",
    section: "sebeke",
    example: "ssh user@server.com",
    match: ["uzaq serverə qoşul"],
  },
  {
    term: "ssh -i",
    note: "Girişdə default açar əvəzinə konkret açar faylını göstərir, bir neçə server, bir neçə açarla işləyəndə lazımdır.",
    section: "sebeke",
    example: "ssh -i ~/.ssh/server_key user@server.com",
    match: ["açarla giriş"],
  },

  /* ---------- disk ---------- */
  {
    term: "df -h",
    note: "Bütün bağlı disk bölmələrinin ümumi, işlədilmiş və boş yerini oxunaqlı vahidlərlə (GB/MB) göstərir. Bölmə səviyyəsindədir: hansı qovluq yeri yediyini demir, bunun üçün `du` lazımdır.",
    section: "disk",
    example: "df -h",
    match: ["disk yeri", "bölmə dolub"],
  },
  {
    term: "du -sh",
    note: "Konkret bir qovluğun tutduğu ümumi yeri bir rəqəmlə göstərir, `df`-dən fərqli olaraq bölmə yox, qovluq səviyyəsində ölçür.",
    section: "disk",
    example: "du -sh /var/log",
    match: ["qovluq ölçüsü", "yer bitib"],
  },
  {
    term: "du -h --max-depth=1",
    note: "Cari qovluğun hər birinci səviyyə alt-qovluğunun ölçüsünü ayrı-ayrı göstərir, yeri hansı alt-qovluğun yediyini tapmaq üçün.",
    section: "disk",
    example: "du -h --max-depth=1 /var",
    match: ["hansı qovluq yer yeyir", "yer bitib"],
  },
  {
    term: "lsblk",
    note: "Sistemdəki bütün blok qurğularını (disk, bölmə, USB) ağac şəklində göstərir: hansı bölmə haraya bağlıdır.",
    section: "disk",
    example: "lsblk",
    match: ["disk siyahısı", "bölmələri göstər"],
  },
  {
    term: "mount",
    note: "Fayl sistemini bir qovluğa bağlayır. Arqumentsiz işlədilsə, hazırda nəyin haraya bağlı olduğunu sadalayır.",
    section: "disk",
    example: "mount /dev/sdb1 /mnt/disk",
    match: ["diski bağla"],
  },
  {
    term: "umount",
    note: "Bağlı fayl sistemini ayırır. Diski çıxarmadan əvvəl aparılmalıdır, yoxsa yazılmamış məlumat itə bilər.",
    section: "disk",
    example: "umount /mnt/disk",
    match: ["diski ayır", "diski çıxar"],
  },
  {
    term: "fdisk -l",
    note: "Bütün disklərin bölmə cədvəlini göstərir, ölçü, tip və bölmə sərhədləri daxil.",
    section: "disk",
    example: "fdisk -l",
    match: ["bölmə cədvəli"],
  },
  {
    term: "ncdu",
    note: "`du`-nun interaktiv, naviqasiya edilə bilən versiyası. Qovluqları ölçüyə görə sıralı göstərir, oxla içinə girə bilirsən. Ayrıca quraşdırılmalıdır.",
    section: "disk",
    example: "ncdu /var",
    match: ["interaktiv yer analizi"],
  },

  /* ---------- icaze ---------- */
  {
    term: "chmod",
    note: "Faylın oxuma, yazma, icra icazələrini dəyişir: rəqəmlə (755) və ya hərflə (u+x) yazıla bilər.",
    section: "icaze",
    example: "chmod 644 config.yaml",
    match: ["icazə dəyiş", "permission"],
  },
  {
    term: "chmod +x",
    note: "Fayla icra icazəsi əlavə edir, skripti `./skript.sh` kimi birbaşa işə salmaq üçün ilk şərt.",
    section: "icaze",
    example: "chmod +x deploy.sh",
    match: ["skripti icra edilə bilən et"],
  },
  {
    term: "chown",
    note: "Faylın sahibini (və istəyə görə qrupunu) dəyişir (`istifadəçi:qrup` formasında).",
    section: "icaze",
    example: "chown www-data:www-data /var/www/sayt",
    match: ["sahib dəyiş"],
  },
  {
    term: "chgrp",
    note: "Faylın sahibinə toxunmadan, yalnız qrup sahibliyini dəyişir.",
    section: "icaze",
    example: "chgrp developers layihe/",
    match: ["qrup dəyiş"],
  },
  {
    term: "umask",
    note: "Yeni yaradılan fayl və qovluqlara defolt hansı icazənin veriləcəyini müəyyən edir. Mövcud faylı dəyişmir, yalnız gələcəyi təyin edir.",
    section: "icaze",
    example: "umask 022",
    match: ["defolt icazə"],
  },
  {
    term: "sudo",
    note: "Növbəti əmri root (superuser) hüquqları ilə işə salır: parol soruşur, hərəkət audit jurnalına düşür.",
    section: "icaze",
    example: "sudo apt update",
    match: ["root kimi işlət", "superuser"],
  },
  {
    term: "su",
    note: "Başqa istifadəçiyə (defolt root-a) keçir və o sessiyada qalır, `sudo`-dan fərqli olaraq tək əmr yox, bütün seans üçün.",
    section: "icaze",
    example: "su - postgres",
    match: ["istifadəçi dəyiş"],
  },
  {
    term: "passwd",
    note: "Cari istifadəçinin (və ya root işlədəndə başqasının) parolunu dəyişir.",
    section: "icaze",
    example: "passwd",
    match: ["parol dəyiş"],
  },
  {
    term: "useradd",
    note: "Sistemdə yeni istifadəçi hesabı yaradır. Ev qovluğu üçün `-m` bayrağı verilməlidir, yoxsa açılmır.",
    section: "icaze",
    example: "useradd -m deploy",
    match: ["yeni istifadəçi yarat"],
  },
  {
    term: "usermod -aG",
    note: "İstifadəçini mövcud qruplara toxunmadan yeni bir qrupa əlavə edir. `-a` olmadan digər bütün qruplardan çıxarılır.",
    section: "icaze",
    example: "usermod -aG docker deploy",
    match: ["qrupa əlavə et"],
  },
  {
    term: "groups",
    note: "İstifadəçinin üzv olduğu bütün qrupları sadalayır.",
    section: "icaze",
    example: "groups deploy",
    match: ["hansı qruplardayam"],
  },
  {
    term: "id",
    note: "İstifadəçinin UID, GID və üzv olduğu qrupların rəqəm və adlarını birlikdə göstərir.",
    section: "icaze",
    example: "id deploy",
    match: ["istifadəçi kimliyi"],
  },
  {
    term: "whoami",
    note: "Cari sessiyada hansı istifadəçi kimi işlədiyini göstərir, `sudo -i`-dan sonra unudulanda tez yoxlamaq üçün.",
    section: "icaze",
    example: "whoami",
    match: ["hansı istifadəçiyəm"],
  },

  /* ---------- paket ---------- */
  {
    term: "apt install",
    note: "Debian/Ubuntu-da paketi endirib quraşdırır: asılılıqları da özü həll edir.",
    section: "paket",
    example: "sudo apt install nginx",
    match: ["paket quraşdır"],
  },
  {
    term: "apt update && apt upgrade",
    note: "`update` mövcud paketlərin siyahısını yeniləyir (heç nə quraşdırmır), `upgrade` isə köhnəlmiş paketləri yeni versiyaya qaldırır. Əvvəlcə `update`, sonra `upgrade` gərəkdir.",
    section: "paket",
    example: "sudo apt update && sudo apt upgrade",
    match: ["paketləri yenilə", "sistemi yenilə"],
  },
  {
    term: "apt search",
    note: "Paket adlarının və təsvirlərinin arasında açar sözlə axtarır, paketin dəqiq adını bilməyəndə.",
    section: "paket",
    example: "apt search postgresql",
    match: ["paket axtar"],
  },
  {
    term: "dpkg -l",
    note: "Sistemdə quraşdırılmış bütün `.deb` paketlərini versiyası ilə birgə sadalayır.",
    section: "paket",
    example: "dpkg -l | grep nginx",
    match: ["quraşdırılmış paketlər"],
  },
  {
    term: "snap install",
    note: "Snap formatındakı paketi quraşdırır: asılılıqları öz konteynerinə bağlayır, sistemin qalanından təcrid olunmuş işləyir.",
    section: "paket",
    example: "sudo snap install code --classic",
    match: ["snap paket quraşdır"],
  },

  /* ---------- sistem ---------- */
  {
    term: "uname -a",
    note: "Kernel versiyasını, arxitekturanı və host adını bir sətirdə verir (dəstək tələbi açanda ilk soruşulan məlumat).",
    section: "sistem",
    example: "uname -a",
    match: ["kernel versiyası", "sistem məlumatı"],
  },
  {
    term: "hostname",
    note: "Maşının şəbəkə adını göstərir.",
    section: "sistem",
    example: "hostname",
    match: ["maşının adı"],
  },
  {
    term: "uptime",
    note: "Sistemin nə qədər vaxtdır işlədiyini və son 1/5/15 dəqiqəlik yük ortalamasını göstərir.",
    section: "sistem",
    example: "uptime",
    match: ["nə qədərdir işləyir", "yük ortalaması"],
  },
  {
    term: "free -h",
    note: "Ümumi, işlədilmiş, boş yaddaşı və swap-ı oxunaqlı vahidlərlə göstərir.",
    section: "sistem",
    example: "free -h",
    match: ["yaddaş vəziyyəti", "ram istifadəsi"],
  },
  {
    term: "lscpu",
    note: "Prosessorun nüvə sayını, arxitekturasını və tezliyini ətraflı göstərir.",
    section: "sistem",
    example: "lscpu",
    match: ["prosessor məlumatı", "cpu nüvə sayı"],
  },
  {
    term: "date",
    note: "Sistemin cari tarix və vaxtını göstərir, format şablonu ilə istənilən görkəmə salına bilər.",
    section: "sistem",
    example: 'date +"%Y-%m-%d %H:%M"',
    match: ["cari tarix"],
  },
  {
    term: "timedatectl",
    note: "Sistemin saat qurşağını, avtomatik saat sinxronlaşdırmasının vəziyyətini göstərir və dəyişir.",
    section: "sistem",
    example: "timedatectl set-timezone Asia/Baku",
    match: ["saat qurşağı", "timezone dəyiş"],
  },
  {
    term: "env",
    note: "Cari sessiyada təyin olunmuş bütün mühit dəyişənlərini sadalayır.",
    section: "sistem",
    example: "env | grep PATH",
    match: ["mühit dəyişənləri"],
  },
  {
    term: "export",
    note: "Yeni mühit dəyişəni təyin edir və onu bu terminaldan açılan bütün alt-proseslərə ötürür.",
    section: "sistem",
    example: "export NODE_ENV=production",
    match: ["dəyişən təyin et", "env variable"],
  },
  {
    term: "history",
    note: "Bu terminalda əvvəl işlədilmiş əmrləri sadalayır. Nömrəsi ilə `!123` kimi təkrar çağırıla bilər.",
    section: "sistem",
    example: "history | grep ssh",
    match: ["keçmiş əmrlər"],
  },
  {
    term: "which",
    note: "Bir əmrin hansı fayldan işə düşdüyünü göstərir, eyni adlı bir neçə versiya olanda hansının işlədiyini tapmaq üçün.",
    section: "sistem",
    example: "which node",
    match: ["əmr haradan işləyir"],
  },
  {
    term: "whereis",
    note: "Əmrin icra faylını, mənbə kodunu və man səhifəsini birlikdə axtarır: `which`-dən daha geniş nəticə verir.",
    section: "sistem",
    example: "whereis python3",
    match: ["əmrin bütün fayllarını tap"],
  },
  {
    term: "man",
    note: "Əmrin rəsmi sənədini açır, bütün bayraqlar və istifadə nümunələri ilə. `q` ilə çıxılır.",
    section: "sistem",
    example: "man tar",
    match: ["sənədi göstər", "kömək səhifəsi"],
  },
  {
    term: "alias",
    note: "Uzun bir əmrə qısa ad verir. `.bashrc`-yə yazılsa hər terminalda mövcud olur.",
    section: "sistem",
    example: 'alias ll="ls -la"',
    match: ["əmrə qısayol"],
  },
  {
    term: "tar -czf",
    note: "Fayl və qovluqları bir `.tar.gz` arxivinə yığır və gzip ilə sıxır: `c` yarat, `z` gzip, `f` fayl adı deməkdir.",
    section: "sistem",
    example: "tar -czf yedek.tar.gz layihe/",
    match: ["arxivləşdir", "sıxılmış yedek"],
  },
  {
    term: "tar -xzf",
    note: "`.tar.gz` arxivini açır: `x` çıxart, `z` gzip, `f` fayl adı deməkdir.",
    section: "sistem",
    example: "tar -xzf yedek.tar.gz",
    match: ["arxivi aç"],
  },
  {
    term: "zip",
    note: "Faylları `.zip` arxivinə yığır. Windows-la paylaşılacaq faylda `tar.gz`-dən daha uyğundur.",
    section: "sistem",
    example: "zip -r yedek.zip layihe/",
    match: ["zip arxivi yarat"],
  },
  {
    term: "unzip",
    note: "`.zip` arxivini içindəkilərlə birlikdə cari qovluğa açır. `-d` bayrağı ilə başqa qovluq göstərmək olar.",
    section: "sistem",
    example: "unzip yedek.zip -d /tmp/açılmış",
    match: ["zip arxivi aç"],
  },
  {
    term: "gzip",
    note: "Tək bir faylı sıxaraq `.gz` uzantılı edir: orijinal fayl silinir, `-k` bayrağı ilə saxlanıla bilər.",
    section: "sistem",
    example: "gzip access.log",
    match: ["faylı sıx"],
  },
];
