/**
 * MIME type reference: what a browser or a server calls a file so the other
 * side knows how to treat it, without opening it first.
 *
 * The lookup runs both directions on purpose. Somebody who has a `.docx` file
 * and needs the `Content-Type` header for an upload API searches by
 * extension; somebody staring at a server log full of `application/json`
 * searches by the type itself. `label` carries the extension and `term`
 * carries the type, and both end up in the row's searchable text — so
 * either query finds the same row without a second data structure.
 *
 * The rows are grouped the way a visitor already thinks about files —
 * documents, images, audio and video, archives, fonts, and everything else
 * that moves data between programs rather than being opened by a person.
 */
import type { ReferenceRow, ReferenceSection } from "./reference.js";

export const mimeSections: ReferenceSection[] = [
  { id: "metn", label: "Mətn və sənəd" },
  { id: "sekil", label: "Şəkil" },
  { id: "audio-video", label: "Səs və video" },
  { id: "arxiv", label: "Arxiv və sıxılma" },
  { id: "srift", label: "Şrift" },
  {
    id: "data",
    label: "Data və proqram",
    hint: "Fayl deyil, API cavabının, formanın və ya axının Content-Type-ı olan tiplər də buradadır.",
  },
];

export const mimeRows: ReferenceRow[] = [
  /* ---------- metn ---------- */
  {
    term: "text/html",
    label: ".html, .htm",
    note: "Brauzerin göstərdiyi səhifənin əsas formatıdır: teqlərlə strukturlaşdırılmış mətn.",
    section: "metn",
    match: ["html", "htm", "hypertext"],
  },
  {
    term: "text/css",
    label: ".css",
    note: "Səhifənin görünüşünü təyin edən üslub cədvəlidir, HTML-dən ayrı fayl kimi yüklənir.",
    section: "metn",
    match: ["css", "stylesheet", "uslub"],
  },
  {
    term: "text/plain",
    label: ".txt",
    note: "Heç bir teq, heç bir işarələmə daşımayan xam mətndir, ən sadə mətn tipidir.",
    section: "metn",
    match: ["txt", "plain text", "xam metn"],
  },
  {
    term: "text/csv",
    label: ".csv",
    note: "Vergüllə ayrılmış cədvəl sətirləridir, Excel və Google Cədvəllər bunu birbaşa açır.",
    section: "metn",
    match: ["csv", "comma separated values"],
  },
  {
    term: "text/markdown",
    label: ".md",
    note: "Başlıq, siyahı və linki sadə işarələrlə yazan yüngül mətn formatıdır (README faylının standartı).",
    section: "metn",
    match: ["md", "markdown", "readme"],
  },
  {
    term: "application/pdf",
    label: ".pdf",
    note: "Səhifə düzülüşünü hər cihazda eyni saxlayan sənəd formatıdır, Adobe Acrobat-dan çıxıb.",
    section: "metn",
    match: ["pdf", "acrobat"],
  },
  {
    term: "application/msword",
    label: ".doc",
    note: "Word-un köhnə ikili formatıdır (97-2003 arası); yeni Word faylları artıq .docx işlədir.",
    section: "metn",
    match: ["doc", "word", "microsoft word"],
  },
  {
    term: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    label: ".docx",
    note: "Word-un 2007-dən bəri işlətdiyi formatdır, əslində içi XML sənədlərlə dolu ZIP arxividir. Tip adı uzundur. Bir hərf səhv yazılanda fayl açılmır.",
    section: "metn",
    match: ["docx", "word"],
  },
  {
    term: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    label: ".xlsx",
    note: "Excel-in cədvəl faylıdır, .docx kimi ZIP arxivində XML saxlayır. Tip adı əl ilə yazanda tez-tez səhv olunur.",
    section: "metn",
    match: ["xlsx", "excel"],
  },
  {
    term: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    label: ".pptx",
    note: "PowerPoint təqdimatının faylıdır, .docx və .xlsx ilə eyni ZIP+XML quruluşunu paylaşan üçüncü format.",
    section: "metn",
    match: ["pptx", "powerpoint", "teqdimat"],
  },
  {
    term: "application/vnd.oasis.opendocument.text",
    label: ".odt",
    note: "LibreOffice Writer və OpenOffice-in açıq standartla yazdığı mətn sənədidir, Word-dən asılı deyil.",
    section: "metn",
    match: ["odt", "libreoffice", "openoffice"],
  },
  {
    term: "application/rtf",
    label: ".rtf",
    note: "Qalın, kursiv və şrift kimi formatlaşdırmanı saxlayan, demək olar hər mətn redaktorunun açdığı köhnə ortaq formatdır.",
    section: "metn",
    match: ["rtf", "rich text"],
  },
  {
    term: "application/vnd.ms-excel",
    label: ".xls",
    note: "Excel-in 2007-dən əvvəlki ikili formatıdır, yerini .xlsx-ə verib.",
    section: "metn",
    match: ["xls", "excel", "köhnə excel"],
  },
  {
    term: "application/vnd.ms-powerpoint",
    label: ".ppt",
    note: "PowerPoint-in köhnə ikili formatıdır, yerini .pptx-ə verib.",
    section: "metn",
    match: ["ppt", "powerpoint"],
  },
  {
    term: "text/calendar",
    label: ".ics",
    note: "Təqvim tədbirini başqa proqrama daşıyan formatdır. Google Calendar və Outlook bunu birbaşa idxal edir.",
    section: "metn",
    match: ["ics", "calendar", "təqvim"],
  },
  {
    term: "application/epub+zip",
    label: ".epub",
    note: "Elektron kitab formatıdır, mətni ekran ölçüsünə görə özü yenidən düzür, PDF kimi səhifəni sabitləmir.",
    section: "metn",
    match: ["epub", "ebook", "elektron kitab"],
  },

  /* ---------- sekil ---------- */
  {
    term: "image/jpeg",
    label: ".jpg, .jpeg",
    note: "Foto üçün ən yayılmış sıxılmış formatdır, keyfiyyət itkisi var amma faylı çox kiçildir.",
    section: "sekil",
    match: ["jpg", "jpeg"],
  },
  {
    term: "image/png",
    label: ".png",
    note: "İtkisiz sıxılma və şəffaflıq (alfa kanal) dəstəkləyən formatdır, loqo və ikonlar üçün seçilir.",
    section: "sekil",
    match: ["png", "şəffaf", "transparent"],
  },
  {
    term: "image/gif",
    label: ".gif",
    note: "256 rənglə məhdudlaşan, animasiya dəstəkləyən köhnə formatdır (animasiyalı şəkillərin ənənəvi seçimi).",
    section: "sekil",
    match: ["gif", "animasiya"],
  },
  {
    term: "image/webp",
    label: ".webp",
    note: "Google-un formatıdır, eyni keyfiyyətdə JPEG-dən kiçik faylla PNG kimi şəffaflığı da dəstəkləyir.",
    section: "sekil",
    match: ["webp"],
  },
  {
    term: "image/avif",
    label: ".avif",
    note: "WebP-dən sonra gələn, daha yüksək sıxılma nisbəti verən yeni formatdır. Dəstək hələ hər brauzerdə tam deyil.",
    section: "sekil",
    match: ["avif"],
  },
  {
    term: "image/svg+xml",
    label: ".svg",
    note: "Piksel yox, riyazi əyri ilə çəkilən vektor formatdır: istənilən ölçüdə itki olmadan böyüyür. XML olduğu üçün içinə skript yerləşdirmək mümkündür, ona görə naməlum mənbədən yüklənən SVG XSS riski daşıyır.",
    section: "sekil",
    match: ["svg", "vector", "vektor qrafika"],
  },
  {
    term: "image/x-icon",
    label: ".ico",
    note: "Brauzer tabında görünən sayt ikonunun formatıdır, bir faylda bir neçə ölçünü birləşdirə bilir.",
    section: "sekil",
    match: ["ico", "favicon", "icon"],
  },
  {
    term: "image/heic",
    label: ".heic",
    note: "iPhone-un default şəkil formatıdır, JPEG-dən kiçik faylla eyni keyfiyyəti verir, amma bir çox Windows və veb proqram birbaşa açmır.",
    section: "sekil",
    match: ["heic", "iphone", "apple foto"],
  },
  {
    term: "image/tiff",
    label: ".tiff, .tif",
    note: "Çap və skan işində işlənən, itkisiz və çox qatlı ola bilən ağır formatdır.",
    section: "sekil",
    match: ["tiff", "tif", "skan"],
  },
  {
    term: "image/bmp",
    label: ".bmp",
    note: "Sıxılmamış, ona görə çox yer tutan Windows-un köhnə şəkil formatıdır.",
    section: "sekil",
    match: ["bmp", "bitmap"],
  },
  {
    term: "image/apng",
    label: ".apng",
    note: "PNG-nin animasiyalı versiyasıdır, GIF-dən fərqli olaraq 256 rəng məhdudiyyəti yoxdur.",
    section: "sekil",
    match: ["apng", "animated png"],
  },
  {
    term: "image/heif",
    label: ".heif",
    note: "HEIC-in daşıyıcı formatıdır, adətən eyni mənada işlədilir; bir neçə şəkli və dərinlik məlumatını bir faylda saxlaya bilir.",
    section: "sekil",
    match: ["heif"],
  },
  {
    term: "image/jp2",
    label: ".jp2",
    note: "JPEG 2000 formatıdır, JPEG-dən daha yaxşı sıxılma verir, amma geniş dəstəklənmir.",
    section: "sekil",
    match: ["jp2", "jpeg 2000"],
  },
  {
    term: "image/vnd.adobe.photoshop",
    label: ".psd",
    note: "Photoshop-un qat-qat saxlayan iş faylıdır, veb üçün deyil. Dərcdən əvvəl ayrıca formata ixrac tələb edir.",
    section: "sekil",
    match: ["psd", "photoshop"],
  },

  /* ---------- audio-video ---------- */
  {
    term: "audio/mpeg",
    label: ".mp3",
    note: "Ən yayılmış sıxılmış səs formatıdır, demək olar hər cihaz və proqram tərəfindən çalınır.",
    section: "audio-video",
    match: ["mp3", "mpeg audio"],
  },
  {
    term: "audio/ogg",
    label: ".ogg",
    note: "Açıq mənbəli sıxılmış səs konteyneridir, adətən Vorbis kodeki ilə gəlir.",
    section: "audio-video",
    match: ["ogg", "vorbis"],
  },
  {
    term: "audio/wav",
    label: ".wav",
    note: "Sıxılmamış səs formatıdır, keyfiyyəti maksimum saxlayır amma fayl çox böyük olur.",
    section: "audio-video",
    match: ["wav", "waveform"],
  },
  {
    term: "audio/webm",
    label: ".weba",
    note: "Vebə görə hazırlanmış açıq səs konteyneridir, adətən Opus kodeki ilə istifadə olunur.",
    section: "audio-video",
    match: ["webm audio", "weba"],
  },
  {
    term: "audio/aac",
    label: ".aac",
    note: "MP3-dən sonrakı nəsildir, eyni ölçüdə daha yaxşı keyfiyyət verir (Apple ekosisteminin standart səs formatı).",
    section: "audio-video",
    match: ["aac"],
  },
  {
    term: "audio/flac",
    label: ".flac",
    note: "İtkisiz sıxılan səs formatıdır: WAV keyfiyyətini saxlayır, faylı təxminən yarıya endirir.",
    section: "audio-video",
    match: ["flac", "lossless"],
  },
  {
    term: "audio/midi",
    label: ".mid, .midi",
    note: "Səsin özünü yox, hansı notun nə vaxt çalınacağını yazan formatdır. Fayl çox kiçikdir, səs cihazın öz sintezatorundan gəlir.",
    section: "audio-video",
    match: ["midi", "mid"],
  },
  {
    term: "audio/opus",
    label: ".opus",
    note: "Aşağı bitreytdə belə yüksək keyfiyyət verən müasir kodekdir, zəng və canlı yayımda geniş işlənir.",
    section: "audio-video",
    match: ["opus"],
  },
  {
    term: "video/mp4",
    label: ".mp4",
    note: "Ən çox dəstəklənən video konteyneridir, adətən H.264 video və AAC səs kodeki ilə gəlir.",
    section: "audio-video",
    match: ["mp4", "h264"],
  },
  {
    term: "video/webm",
    label: ".webm",
    note: "Vebə görə hazırlanmış açıq video formatıdır, VP8, VP9 və AV1 kodeklərini daşıyır (YouTube-un daxili formatlarından biridir).",
    section: "audio-video",
    match: ["webm"],
  },
  {
    term: "video/ogg",
    label: ".ogv",
    note: "Ogg konteynerinin video versiyasıdır, adətən Theora kodeki ilə gəlir. Geniş dəstəklənmir.",
    section: "audio-video",
    match: ["ogv", "theora"],
  },
  {
    term: "video/quicktime",
    label: ".mov",
    note: "Apple-ın QuickTime konteyneridir, iPhone-un çəkdiyi videoların standart formatıdır.",
    section: "audio-video",
    match: ["mov", "quicktime", "apple video"],
  },
  {
    term: "video/x-msvideo",
    label: ".avi",
    note: "Microsoft-un köhnə video konteyneridir, içindəki kodekdən asılı olaraq keyfiyyət çox dəyişir.",
    section: "audio-video",
    match: ["avi"],
  },
  {
    term: "video/3gpp",
    label: ".3gp",
    note: "Mobil şəbəkə üçün kiçildilmiş köhnə telefon video formatıdır.",
    section: "audio-video",
    match: ["3gp", "3gpp"],
  },
  {
    term: "video/mp2t",
    label: ".ts",
    note: "MPEG Transport Stream: canlı yayımın (HLS) bölündüyü kiçik video parçalarının formatıdır.",
    section: "audio-video",
    match: ["ts", "transport stream", "hls"],
  },
  {
    term: "application/vnd.apple.mpegurl",
    label: ".m3u8",
    note: "HLS canlı yayımının parça siyahısını göstərən mətn faylıdır: özü video daşımır, .ts parçalarının sırasını göstərir.",
    section: "audio-video",
    match: ["m3u8", "hls", "playlist"],
  },
  {
    term: "text/vtt",
    label: ".vtt",
    note: "Videoya altyazı və subtitr əlavə edən mətn formatıdır, vaxt kodları ilə hər sətri müəyyən hissəyə bağlayır.",
    section: "audio-video",
    match: ["vtt", "subtitle", "altyazı"],
  },

  /* ---------- arxiv ---------- */
  {
    term: "application/zip",
    label: ".zip",
    note: "Ən yayılmış arxiv formatıdır, bir neçə faylı birləşdirib sıxır. Demək olar hər əməliyyat sistemi açır.",
    section: "arxiv",
    match: ["zip"],
  },
  {
    term: "application/gzip",
    label: ".gz",
    note: "Tək faylı sıxan formatdır, adətən .tar ilə birləşib .tar.gz kimi çıxır (Linux dünyasının standartı).",
    section: "arxiv",
    match: ["gz", "gzip"],
  },
  {
    term: "application/x-tar",
    label: ".tar",
    note: "Faylları sıxmadan bir arxivə yığan formatdır: sıxılma üçün adətən üzərinə ayrıca gzip və ya bzip2 tətbiq olunur.",
    section: "arxiv",
    match: ["tar", "tarball"],
  },
  {
    term: "application/vnd.rar",
    label: ".rar",
    note: "WinRAR-ın sıxılma formatıdır, ZIP-dən yüksək sıxılma nisbəti verir amma açmaq üçün ayrıca proqram tələb edir.",
    section: "arxiv",
    match: ["rar", "winrar"],
  },
  {
    term: "application/x-7z-compressed",
    label: ".7z",
    note: "7-Zip-in açıq mənbəli formatıdır, ən yüksək sıxılma nisbətlərindən birini verir.",
    section: "arxiv",
    match: ["7z", "7zip"],
  },
  {
    term: "application/x-bzip2",
    label: ".bz2",
    note: "gzip-dən daha yüksək sıxılma verən, amma daha yavaş işləyən Linux arxiv formatıdır.",
    section: "arxiv",
    match: ["bz2", "bzip2"],
  },
  {
    term: "application/x-xz",
    label: ".xz",
    note: "LZMA əsaslı, bu gün ən yüksək sıxılma nisbətlərindən birini verən formatdır, proqram mənbə kodu paylaşımında geniş işlənir.",
    section: "arxiv",
    match: ["xz", "lzma"],
  },
  {
    term: "application/java-archive",
    label: ".jar",
    note: "Java proqramının bütün class fayllarını bir ZIP arxivində birləşdirən paket formatıdır.",
    section: "arxiv",
    match: ["jar", "java"],
  },
  {
    term: "application/x-iso9660-image",
    label: ".iso",
    note: "Bütöv diskin surətidir: CD/DVD-nin bütün fayl strukturunu bir faylda saxlayır, virtual mühitlərdə disk kimi bağlanır.",
    section: "arxiv",
    match: ["iso", "disk image"],
  },

  /* ---------- srift ---------- */
  {
    term: "font/woff",
    label: ".woff",
    note: "Vebə görə sıxılmış ilk açıq şrift formatıdır, WOFF2-dən əvvəlki nəsildir.",
    section: "srift",
    match: ["woff"],
  },
  {
    term: "font/woff2",
    label: ".woff2",
    note: "WOFF-un daha güclü sıxılan versiyasıdır. Bu gün vebdə şrift yükləməyin standart formatıdır.",
    section: "srift",
    match: ["woff2"],
  },
  {
    term: "font/ttf",
    label: ".ttf",
    note: "TrueType: masaüstü və vebdə geniş dəstəklənən, sıxılmamış şrift formatıdır.",
    section: "srift",
    match: ["ttf", "truetype"],
  },
  {
    term: "font/otf",
    label: ".otf",
    note: "OpenType: TTF-in üzərinə vektor əyriləri üçün fərqli riyaziyyat və daha zəngin tipoqrafiya imkanları əlavə edir.",
    section: "srift",
    match: ["otf", "opentype"],
  },
  {
    term: "application/vnd.ms-fontobject",
    label: ".eot",
    note: "Internet Explorer-in köhnə şrift formatıdır, artıq işlənmir. WOFF2 onu tamamilə əvəz edib.",
    section: "srift",
    match: ["eot", "embedded opentype"],
  },

  /* ---------- data ---------- */
  {
    term: "application/json",
    label: ".json",
    note: "API-lərin ən çox işlətdiyi data mübadiləsi formatıdır, açar-dəyər cütləri ilə strukturlaşdırılmış mətn.",
    section: "data",
    example: "Content-Type: application/json; charset=utf-8",
    match: ["json"],
  },
  {
    term: "application/ld+json",
    label: ".jsonld",
    note: "JSON üzərinə əlavə məna qatan formatdır: saytlarda schema.org strukturlaşdırılmış datası bu tip ilə yerləşdirilir.",
    section: "data",
    match: ["jsonld", "json-ld", "schema.org", "structured data"],
  },
  {
    term: "application/xml",
    label: ".xml",
    note: "Teqlərlə iyerarxik quruluş yaradan köhnə data formatıdır, sənəd kimi işlədiləndə (RSS, SOAP) bu tip yazılır.",
    section: "data",
    match: ["xml"],
  },
  {
    term: "application/javascript",
    label: ".js",
    note: "JavaScript faylının köhnəlmiş tipidir. IANA reyestri bunu köhnəlmiş sayır, indi serverlərin göndərdiyi standart tip text/javascript-dir.",
    section: "data",
    match: ["js", "javascript", "ecmascript", "text/javascript"],
  },
  {
    term: "application/octet-stream",
    label: ".bin",
    note: "'Nə olduğunu bilmirəm' deməkdir: brauzer bu tipi görəndə faylı açmır, birbaşa endirməyə keçir. Server düzgün tipi tapa bilmədikdə fallback kimi bunu göndərir.",
    section: "data",
    match: ["bin", "binary", "generic", "naməlum tip"],
  },
  {
    term: "application/wasm",
    label: ".wasm",
    note: "WebAssembly-nin ikili baytkodudur: brauzerdə demək olar maşın sürətində işləyən kodu daşıyır.",
    section: "data",
    match: ["wasm", "webassembly"],
  },
  {
    term: "application/manifest+json",
    label: ".webmanifest",
    note: "PWA-nın adını, ikonlarını və başlanğıc ekranını təyin edən manifest faylıdır. Telefonda 'ana ekrana əlavə et' bundan oxuyur.",
    section: "data",
    match: ["webmanifest", "pwa", "manifest"],
  },
  {
    term: "multipart/form-data",
    label: ".form-data",
    note: "Fayl deyil, HTTP sorğusunun bədən kodlamasıdır. Formda fayl yükləmə sahəsi olanda brauzer sorğunu bu tip ilə göndərir.",
    section: "data",
    example: '<form enctype="multipart/form-data">',
    match: ["form data", "multipart", "fayl yükləmə"],
  },
  {
    term: "application/x-www-form-urlencoded",
    label: ".urlencoded",
    note: "Formanın default göndərmə kodlamasıdır: sahə adı və dəyəri ad=dəyər&ad2=dəyər2 şəklində, boşluqlar + ilə əvəz olunaraq göndərilir.",
    section: "data",
    match: ["urlencoded", "form", "query string"],
  },
  {
    term: "text/event-stream",
    label: ".sse",
    note: "Server-Sent Events üçün açıq qalan HTTP cavabının tipidir. Real fayl uzantısı yoxdur, server bu tip ilə hadisələri ardıcıl göndərir.",
    section: "data",
    match: ["sse", "server sent events", "stream"],
  },
  {
    term: "application/rss+xml",
    label: ".rss",
    note: "Blogun yazılarını başqa proqramın (RSS oxuyucu) izləyə biləcəyi formada sadalayan xülasə faylıdır.",
    section: "data",
    match: ["rss", "feed"],
  },
  {
    term: "application/atom+xml",
    label: ".atom",
    note: "RSS-dən sonra çıxan, eyni məqsədi daşıyan alternativ xülasə formatıdır, sahə adları fərqlidir, funksiyası eynidir.",
    section: "data",
    match: ["atom", "feed"],
  },
  {
    term: "application/sql",
    label: ".sql",
    note: "Verilənlər bazası sorğularını və ya bazanın bütöv dampını saxlayan mətn faylıdır.",
    section: "data",
    match: ["sql", "dump", "baza"],
  },
  {
    term: "application/yaml",
    label: ".yaml, .yml",
    note: "JSON-dan oxunaqlı, girintiyə söykənən konfiqurasiya formatıdır, Docker Compose və GitHub Actions bunu işlədir.",
    section: "data",
    match: ["yaml", "yml", "config"],
  },
  {
    term: "application/graphql",
    label: ".graphql",
    note: "GraphQL sorğu dilinin sənəd tipidir (REST-in əvəzinə bir sorğuda dəqiq istənilən sahələri təyin etmək üçündür).",
    section: "data",
    match: ["graphql", "gql"],
  },
  {
    term: "application/vnd.api+json",
    label: ".json (JSON:API)",
    note: "JSON-un üzərinə əlaqə, səhifələmə və xəta formatını standartlaşdıran JSON:API spesifikasiyasının tipidir.",
    section: "data",
    match: ["json api", "jsonapi"],
  },
  {
    term: "application/problem+json",
    label: ".json (Problem Details)",
    note: "API xətasını sadə mətn yox, strukturlaşdırılmış formada qaytarmaq üçün RFC 7807 standartının tipidir.",
    section: "data",
    match: ["problem json", "rfc7807", "api error"],
  },
  {
    term: "application/x-ndjson",
    label: ".ndjson",
    note: "Hər sətri ayrıca JSON obyekti olan formatdır: böyük data axınını sətir-sətir emal etməyə imkan verir, bütöv massivi gözləmək lazım deyil.",
    section: "data",
    match: ["ndjson", "newline delimited json", "jsonlines"],
  },
  {
    term: "application/toml",
    label: ".toml",
    note: "YAML-a alternativ, girintiyə söykənməyən konfiqurasiya formatıdır: Rust ekosisteminin (Cargo) standart formatı.",
    section: "data",
    match: ["toml", "config"],
  },
  {
    term: "application/x-protobuf",
    label: ".proto",
    note: "Google-un ikili serialization formatıdır: JSON-dan kiçik və sürətlidir, amma insan gözü ilə oxunmur, ayrıca sxem faylı tələb edir.",
    section: "data",
    match: ["protobuf", "proto", "protocol buffers"],
  },
  {
    term: "application/vnd.google-earth.kml+xml",
    label: ".kml",
    note: "Coğrafi məlumatı (marker, xətt, çoxbucaqlı) xəritə proqramları üçün saxlayan formatdır, Google Earth və Google Maps bunu idxal edir.",
    section: "data",
    match: ["kml", "google earth", "xəritə"],
  },
];
