/**
 * Well-known network ports: the number a service always listens on, so a
 * firewall rule, a `docker-compose.yml` or a "connection refused" error can
 * be read without opening that service's own documentation.
 *
 * A row's `term` is the number itself, or a hyphenated range where the
 * protocol genuinely spans more than one — `137-139` for NetBIOS, `20-21`
 * for FTP's separate control and data channels. A single port is never
 * written as a one-item range, so every `term` is either a bare number or an
 * `a-b` pair, and a check can tell the two apart without guessing.
 *
 * Grouped the way a visitor already reaches for one: the web and its
 * proxies, mail, a database, a way onto another machine, the protocols that
 * hold the network itself together, and the ports a developer's own tools
 * default to.
 */
import type { ReferenceRow, ReferenceSection } from "./reference";

export const portlarSections: ReferenceSection[] = [
  { id: "veb", label: "Veb və proxy" },
  { id: "poct", label: "Poçt" },
  { id: "baza", label: "Verilənlər bazası" },
  { id: "giris", label: "Uzaqdan giriş və fayl" },
  {
    id: "infra",
    label: "İnfrastruktur və növbə",
    hint: "Şəbəkənin özünü ayaqda saxlayan protokollarla mesaj növbəsi (queue) sistemləri bir yerdədir.",
  },
  { id: "izleme", label: "Monitorinq və inkişaf" },
];

export const portlarRows: ReferenceRow[] = [
  /* ---------- veb ---------- */
  {
    term: "80",
    label: "HTTP",
    note: "Şifrələnməmiş veb trafikinin standart portudur — bugün demək olar bütün sənədli saytlar birbaşa buradan HTTPS-ə yönləndirir.",
    section: "veb",
    match: ["http", "web", "tcp"],
  },
  {
    term: "443",
    label: "HTTPS",
    note: "TLS ilə şifrələnmiş veb trafikinin portudur, brauzerin qıfıl işarəsi göstərdiyi bağlantı elə budur.",
    section: "veb",
    match: ["https", "tls", "ssl", "web", "tcp"],
  },
  {
    term: "3000",
    label: "Dev server (Node/React/Grafana)",
    note: "Node.js əsaslı dev serverlərin (Create React App, Ruby on Rails) ən çox rast gəlinən default portudur; Grafana da default olaraq bu portu dinləyir.",
    section: "veb",
    match: ["node", "react", "dev server", "grafana", "tcp"],
  },
  {
    term: "3128",
    label: "Squid proxy",
    note: "Squid önbelleğe alan proxy-nin klassik portudur, korporativ şəbəkələrdə çıxış trafikini süzmək üçün işlədilir.",
    section: "veb",
    match: ["squid", "proxy", "forward proxy", "tcp"],
  },
  {
    term: "4200",
    label: "Angular dev server",
    note: "Angular CLI-nin ng serve əmri ilə açdığı dev server portudur.",
    section: "veb",
    match: ["angular", "ng serve", "dev server", "tcp"],
  },
  {
    term: "5000",
    label: "Flask / .NET dev server",
    note: "Python Flask-ın və .NET-in default dev server portudur — macOS-da AirPlay Receiver bununla toqquşduğu üçün tez-tez dəyişdirilir.",
    section: "veb",
    match: ["flask", "dotnet", "dev server", "tcp"],
  },
  {
    term: "5173",
    label: "Vite dev server",
    note: "Vite-nin dev serverinin default portudur — bugün yeni frontend layihələrinin çoxunda rast gəlinir.",
    section: "veb",
    match: ["vite", "dev server", "tcp"],
  },
  {
    term: "8000",
    label: "Dev server (Django/PHP)",
    note: "Django-nun runserver əmrinin və PHP-nin daxili serverinin default portudur.",
    section: "veb",
    match: ["django", "php", "dev server", "tcp"],
  },
  {
    term: "8080",
    label: "HTTP-alt",
    note: "80-in ən çox işlədilən alternativi — proxy, Tomcat və konteynerdə çalışan veb tətbiqlər adətən bunu seçir.",
    section: "veb",
    match: ["http alt", "tomcat", "proxy", "tcp"],
  },
  {
    term: "8443",
    label: "HTTPS-alt",
    note: "443-ün alternativi, adətən admin panelləri və ya Tomcat-ın SSL portu üçün seçilir.",
    section: "veb",
    match: ["https alt", "tomcat ssl", "tcp"],
  },
  {
    term: "9000",
    label: "PHP-FPM / SonarQube / Portainer",
    note: "Bir neçə fərqli xidmət bu portu paylaşır — PHP-FPM-in FastCGI portu, SonarQube-un veb interfeysi, Portainer-in HTTP UI-si.",
    section: "veb",
    match: ["php-fpm", "sonarqube", "portainer", "tcp"],
  },
  {
    term: "3001",
    label: "Dev server (ikinci)",
    note: "3000 tutulanda ikinci Node və ya React dev serverinin adətən keçdiyi portdur.",
    section: "veb",
    match: ["dev server", "node", "alt port", "tcp"],
  },
  {
    term: "4000",
    label: "Phoenix / GraphQL dev server",
    note: "Elixir Phoenix framework-ünün və bir çox GraphQL sınaq serverinin default portudur.",
    section: "veb",
    match: ["phoenix", "graphql", "elixir", "tcp"],
  },
  {
    term: "8081",
    label: "HTTP-alt (ikinci)",
    note: "8080 tutulanda ikinci proxy və ya admin interfeysin keçdiyi portdur.",
    section: "veb",
    match: ["http alt", "proxy", "tcp"],
  },
  {
    term: "8082",
    label: "HTTP-alt (üçüncü)",
    note: "8080 və 8081-dən sonra üçüncü alternativ kimi seçilən HTTP portudur, adətən daxili admin panelləri üçün.",
    section: "veb",
    match: ["http alt", "admin panel", "tcp"],
  },
  {
    term: "9001",
    label: "Supervisor / Portainer HTTPS",
    note: "Proses meneceri Supervisor-un veb UI-si və Portainer-in HTTPS girişi bu portu paylaşır.",
    section: "veb",
    match: ["supervisor", "portainer https", "tcp"],
  },

  /* ---------- poct ---------- */
  {
    term: "25",
    label: "SMTP",
    note: "Serverlər arası poçt ötürməsinin klassik portudur; şifrələnməmiş olduğu üçün bir çox provayder bu portdan gedən trafiki bloklayır.",
    section: "poct",
    match: ["smtp", "mail", "poçt", "tcp"],
  },
  {
    term: "110",
    label: "POP3",
    note: "Poçt qutusundakı məktubları serverdən silərək lokal proqrama endirən köhnə protokoldur — bugün nadir işlədilir.",
    section: "poct",
    match: ["pop3", "mail", "tcp"],
  },
  {
    term: "143",
    label: "IMAP",
    note: "Məktubları serverdə saxlayaraq bir neçə cihazdan sinxron göstərən poçt protokoludur — POP3-ün yerini tutub.",
    section: "poct",
    match: ["imap", "mail", "tcp"],
  },
  {
    term: "465",
    label: "SMTPS",
    note: "SMTP-nin TLS ilə əvvəldən şifrələnmiş versiyasıdır — göndərmə tərəfində bu gün ən çox tövsiyə olunan portdur.",
    section: "poct",
    match: ["smtps", "smtp ssl", "mail", "tcp"],
  },
  {
    term: "587",
    label: "SMTP submission",
    note: "İstifadəçinin öz poçt proqramından (Outlook, Thunderbird) məktub göndərməsi üçün nəzərdə tutulub, autentifikasiya tələb edir və 25-dən fərqli olaraq provayderlər tərəfindən bloklanmır.",
    section: "poct",
    match: ["smtp submission", "mail client", "tcp"],
  },
  {
    term: "993",
    label: "IMAPS",
    note: "IMAP-ın TLS ilə şifrələnmiş versiyasıdır — bu gün demək olar bütün poçt müştəriləri bunu işlədir.",
    section: "poct",
    match: ["imaps", "imap ssl", "tcp"],
  },
  {
    term: "995",
    label: "POP3S",
    note: "POP3-ün TLS ilə şifrələnmiş versiyasıdır.",
    section: "poct",
    match: ["pop3s", "pop3 ssl", "tcp"],
  },
  {
    term: "119",
    label: "NNTP",
    note: "Usenet xəbər qruplarının paylaşılması üçün işlədilən köhnə protokoldur — poçtla eyni dövrün texnologiyasıdır.",
    section: "poct",
    match: ["nntp", "usenet", "news", "tcp"],
  },
  {
    term: "2525",
    label: "SMTP (alternativ)",
    note: "Bir çox bulud poçt provayderi (SendGrid, Mailgun) 25 bloklananda göndərməni bu portdan qəbul edir.",
    section: "poct",
    match: ["smtp alt", "sendgrid", "mailgun", "tcp"],
  },
  {
    term: "4190",
    label: "ManageSieve",
    note: "Poçt qutusunda serverdə saxlanılan süzgəc (Sieve) qaydalarını uzaqdan idarə etmək üçün işlədilir.",
    section: "poct",
    match: ["managesieve", "sieve", "mail filter", "tcp"],
  },

  /* ---------- baza ---------- */
  {
    term: "1433",
    label: "SQL Server",
    note: "Microsoft SQL Server-in default TCP portudur.",
    section: "baza",
    match: ["sql server", "mssql", "tcp"],
  },
  {
    term: "1521",
    label: "Oracle",
    note: "Oracle Database-in listener portudur — TNS protokolu bu üzərindən qoşulur.",
    section: "baza",
    match: ["oracle", "tns", "tcp"],
  },
  {
    term: "3306",
    label: "MySQL",
    note: "MySQL və MariaDB-nin default portudur.",
    section: "baza",
    match: ["mysql", "mariadb", "tcp"],
  },
  {
    term: "5432",
    label: "PostgreSQL",
    note: "PostgreSQL-in default portudur.",
    section: "baza",
    match: ["postgres", "psql", "postgresql", "tcp"],
  },
  {
    term: "6379",
    label: "Redis",
    note: "Redis-in default portudur; parolsuz və internetə açıq buraxılması ən çox rast gəlinən konfiqurasiya səhvlərindən biridir.",
    section: "baza",
    match: ["redis", "cache", "tcp"],
  },
  {
    term: "9200",
    label: "Elasticsearch",
    note: "Elasticsearch-in REST API portudur; autentifikasiyasız internetə açıq qalan nüsxələr illərdir data sızmalarının tipik mənbəyidir.",
    section: "baza",
    match: ["elasticsearch", "search engine", "tcp"],
  },
  {
    term: "11211",
    label: "Memcached",
    note: "Memcached-in default portudur; autentifikasiyası olmadığı üçün açıq qalan nüsxələr DDoS gücləndirmə (amplification) həmləsində istifadə olunur.",
    section: "baza",
    match: ["memcached", "cache", "udp"],
  },
  {
    term: "27017",
    label: "MongoDB",
    note: "MongoDB-nin default portudur; autentifikasiyasız açıq buraxılmış nüsxələr internetdə kütləvi axtarılan hədəflərdən biridir.",
    section: "baza",
    match: ["mongodb", "nosql", "tcp"],
  },
  {
    term: "5984",
    label: "CouchDB",
    note: "Apache CouchDB-nin HTTP əsaslı REST API portudur.",
    section: "baza",
    match: ["couchdb", "nosql", "tcp"],
  },
  {
    term: "8086",
    label: "InfluxDB",
    note: "Zaman seriyası (time-series) bazası InfluxDB-nin default HTTP portudur.",
    section: "baza",
    match: ["influxdb", "time series", "tcp"],
  },
  {
    term: "9042",
    label: "Cassandra",
    note: "Apache Cassandra-nın müştəri qoşulmaları üçün istifadə etdiyi CQL portudur.",
    section: "baza",
    match: ["cassandra", "cql", "tcp"],
  },
  {
    term: "1434",
    label: "SQL Server Browser",
    note: "Adlandırılmış SQL Server instansiyalarının hansı portda dinlədiyini göstərən köməkçi UDP xidmətidir.",
    section: "baza",
    match: ["sql server browser", "mssql", "udp"],
  },
  {
    term: "9300",
    label: "Elasticsearch transport",
    note: "Klaster daxilində node-lar arası kommunikasiya üçün işlədilir, xarici müştəri buradan qoşulmur.",
    section: "baza",
    match: ["elasticsearch", "cluster", "tcp"],
  },
  {
    term: "27018",
    label: "MongoDB (shard)",
    note: "Shard-lanmış MongoDB topologiyasında shard serverin dinlədiyi portdur, 27017 isə adi instansiya üçündür.",
    section: "baza",
    match: ["mongodb", "shard", "tcp"],
  },

  /* ---------- giris ---------- */
  {
    term: "20-21",
    label: "FTP",
    note: "21 idarəetmə kanalıdır, 20 isə data ötürməsi üçün açılır. Şifrələnməmiş olduğu üçün istifadəçi adı və parol açıq mətn kimi gedir.",
    section: "giris",
    match: ["ftp", "file transfer", "tcp"],
  },
  {
    term: "22",
    label: "SSH",
    note: "Şifrələnmiş uzaqdan giriş və fayl köçürməsi (SCP, SFTP) üçün standart portdur.",
    section: "giris",
    match: ["ssh", "secure shell", "scp", "sftp", "tcp"],
  },
  {
    term: "23",
    label: "Telnet",
    note: "Şifrələnməmiş, bütün trafiki açıq mətn kimi göndərən köhnə uzaqdan giriş protokoludur — internetə açıq qalması ciddi konfiqurasiya səhvi sayılır.",
    section: "giris",
    match: ["telnet", "tcp"],
  },
  {
    term: "69",
    label: "TFTP",
    note: "Autentifikasiyası olmayan sadələşdirilmiş fayl köçürmə protokoludur, adətən şəbəkə cihazlarının proqram yükləməsində işlədilir.",
    section: "giris",
    match: ["tftp", "udp"],
  },
  {
    term: "137-139",
    label: "NetBIOS",
    note: "Windows-un köhnə fayl və printer paylaşım protokoludur; SMB-dən əvvəlki nəsildir, bu gün əsasən köhnə şəbəkələrdə qalıb.",
    section: "giris",
    match: ["netbios", "windows sharing", "tcp", "udp"],
  },
  {
    term: "445",
    label: "SMB",
    note: "Windows fayl və printer paylaşımının bugünkü portudur; internetə açıq qalması WannaCry kimi qurdların yayılma yolu olub.",
    section: "giris",
    match: ["smb", "samba", "file sharing", "tcp"],
  },
  {
    term: "631",
    label: "IPP",
    note: "Internet Printing Protocol — şəbəkə printerinin çap tapşırığı qəbul etdiyi portdur, CUPS bunu işlədir.",
    section: "giris",
    match: ["ipp", "printing", "cups", "tcp"],
  },
  {
    term: "2049",
    label: "NFS",
    note: "Unix və Linux sistemləri arasında fayl sistemini şəbəkə üzərindən paylaşan protokoldur.",
    section: "giris",
    match: ["nfs", "network file system", "tcp", "udp"],
  },
  {
    term: "3389",
    label: "RDP",
    note: "Windows-un uzaqdan masaüstü protokoludur; internetə açıq qalan RDP portları brute-force həmləsinin ən çox rast gəlinən hədəflərindəndir.",
    section: "giris",
    match: ["rdp", "remote desktop", "tcp"],
  },
  {
    term: "5900",
    label: "VNC",
    note: "Ekranı uzaqdan göstərən və idarə edən protokoldur; bir çox VNC server default olaraq zəif və ya heç bir parol tələb etmir.",
    section: "giris",
    match: ["vnc", "remote desktop", "tcp"],
  },
  {
    term: "990",
    label: "FTPS",
    note: "FTP-nin TLS ilə şifrələnmiş versiyasıdır — idarəetmə kanalı bu portda açılır.",
    section: "giris",
    match: ["ftps", "ftp ssl", "tcp"],
  },
  {
    term: "5985",
    label: "WinRM",
    note: "Windows Remote Management-in HTTP portudur, PowerShell-in uzaqdan idarəetməsi bunun üzərindən işləyir.",
    section: "giris",
    match: ["winrm", "powershell remoting", "tcp"],
  },
  {
    term: "873",
    label: "rsync",
    note: "rsync daemon rejimində dinlədiyi portdur; SSH tunelindən istifadə edəndə bu port heç açılmır.",
    section: "giris",
    match: ["rsync", "file sync", "tcp"],
  },

  /* ---------- infra ---------- */
  {
    term: "53",
    label: "DNS",
    note: "Domen adını IP ünvana çevirən sorğuların portudur — həm TCP, həm UDP üzərində işləyir.",
    section: "infra",
    match: ["dns", "domain name system", "tcp", "udp"],
  },
  {
    term: "67-68",
    label: "DHCP",
    note: "Şəbəkəyə qoşulan cihaza avtomatik IP ünvan verən protokoldur — 67 server, 68 müştəri tərəfindədir.",
    section: "infra",
    match: ["dhcp", "ip lease", "udp"],
  },
  {
    term: "123",
    label: "NTP",
    note: "Cihazların saatını dəqiq server vaxtına sinxronlaşdıran protokoldur.",
    section: "infra",
    match: ["ntp", "time sync", "udp"],
  },
  {
    term: "179",
    label: "BGP",
    note: "İnternetin marşrutlaşdırma cədvəllərini avtonom sistemlər arasında paylaşan protokoldur — böyük operatorların bir-biri ilə danışdığı dildir.",
    section: "infra",
    match: ["bgp", "routing", "tcp"],
  },
  {
    term: "389",
    label: "LDAP",
    note: "Korporativ istifadəçi qovluğunu (Active Directory kimi) sorğulayan protokoldur.",
    section: "infra",
    match: ["ldap", "directory", "active directory", "tcp"],
  },
  {
    term: "636",
    label: "LDAPS",
    note: "LDAP-ın TLS ilə şifrələnmiş versiyasıdır.",
    section: "infra",
    match: ["ldaps", "ldap ssl", "tcp"],
  },
  {
    term: "1080",
    label: "SOCKS proxy",
    note: "Tətbiqdən asılı olmayan ümumi proxy protokoludur — HTTP proxy-dən fərqli olaraq istənilən TCP trafikini ötürə bilir.",
    section: "infra",
    match: ["socks", "socks5", "proxy", "tcp"],
  },
  {
    term: "1194",
    label: "OpenVPN",
    note: "OpenVPN-in default portudur, adətən UDP üzərində işlədilir.",
    section: "infra",
    match: ["openvpn", "vpn", "udp"],
  },
  {
    term: "1723",
    label: "PPTP",
    note: "Köhnə VPN protokoludur; şifrələməsi zəif sayıldığı üçün yeni qurulan sistemlərdə artıq tövsiyə olunmur.",
    section: "infra",
    match: ["pptp", "vpn", "tcp"],
  },
  {
    term: "1883",
    label: "MQTT",
    note: "IoT cihazlarının yüngül nəşr-abunə (pub/sub) protokoludur; şifrələnməmiş versiyasının açıq qalması cihazın uzaqdan idarə edilməsinə imkan verə bilər.",
    section: "infra",
    match: ["mqtt", "iot", "pub sub", "tcp"],
  },
  {
    term: "2375-2376",
    label: "Docker daemon",
    note: "Docker-in uzaqdan idarəetmə API portlarıdır — 2375 şifrələnməmiş, 2376 TLS ilədir. 2375-in internetə açıq qalması hostda kod icra etməyə bərabərdir.",
    section: "infra",
    match: ["docker", "docker daemon", "tcp"],
  },
  {
    term: "5060-5061",
    label: "SIP",
    note: "VoIP zənglərinin siqnalizasiya protokoludur — 5060 şifrələnməmiş, 5061 TLS ilədir.",
    section: "infra",
    match: ["sip", "voip", "tcp", "udp"],
  },
  {
    term: "5672",
    label: "RabbitMQ",
    note: "AMQP protokolu ilə işləyən növbə (queue) sisteminin default portudur.",
    section: "infra",
    match: ["rabbitmq", "amqp", "message queue", "tcp"],
  },
  {
    term: "6443",
    label: "Kubernetes API",
    note: "Klasterin idarəetmə mərkəzi olan API server portudur; internetə açıq və zəif qorunan API bütöv klasterin ələ keçirilməsinə səbəb ola bilər.",
    section: "infra",
    match: ["kubernetes", "k8s api", "tcp"],
  },
  {
    term: "9092",
    label: "Kafka",
    note: "Apache Kafka-nın broker portudur — böyük həcmli hadisə axınlarını (event stream) növbəyə yığan sistemdir.",
    section: "infra",
    match: ["kafka", "event streaming", "message queue", "tcp"],
  },
  {
    term: "51820",
    label: "WireGuard",
    note: "Müasir, sadə konfiqurasiyalı VPN protokolunun default portudur — UDP üzərində işləyir.",
    section: "infra",
    match: ["wireguard", "vpn", "udp"],
  },
  {
    term: "111",
    label: "RPCbind",
    note: "NFS kimi RPC əsaslı xidmətlərin hansı portda dinlədiyini göstərən köməkçi xidmətdir.",
    section: "infra",
    match: ["rpcbind", "portmapper", "tcp", "udp"],
  },
  {
    term: "500",
    label: "IKE",
    note: "IPsec VPN-in açar mübadiləsi (key exchange) mərhələsinin portudur.",
    section: "infra",
    match: ["ike", "ipsec", "vpn", "udp"],
  },
  {
    term: "4500",
    label: "IPsec NAT-T",
    note: "IPsec bağlantısı NAT arxasından keçəndə istifadə olunan əlavə portdur.",
    section: "infra",
    match: ["ipsec nat-t", "vpn", "udp"],
  },
  {
    term: "8291",
    label: "MikroTik Winbox",
    note: "MikroTik marşrutlaşdırıcılarının Winbox idarəetmə proqramının qoşulduğu portdur.",
    section: "infra",
    match: ["mikrotik", "winbox", "tcp"],
  },

  /* ---------- izleme ---------- */
  {
    term: "161-162",
    label: "SNMP",
    note: "Şəbəkə cihazlarını uzaqdan izləyən protokoldur — 161 sorğu, 162 tələ (trap) üçündür. Default 'public' community adı ilə açıq qalması geniş yayılmış konfiqurasiya səhvidir.",
    section: "izleme",
    match: ["snmp", "network monitoring", "udp"],
  },
  {
    term: "514",
    label: "syslog",
    note: "Şəbəkə cihazları və serverlərin log mesajlarını mərkəzi topladığı köhnə protokoldur.",
    section: "izleme",
    match: ["syslog", "logging", "udp"],
  },
  {
    term: "5601",
    label: "Kibana",
    note: "Elasticsearch üzərindəki datanı vizuallaşdıran Kibana panelinin default portudur.",
    section: "izleme",
    match: ["kibana", "elk stack", "tcp"],
  },
  {
    term: "8888",
    label: "Jupyter Notebook",
    note: "Jupyter Notebook-un default portudur, məlumat elmi işlərində geniş işlədilir.",
    section: "izleme",
    match: ["jupyter", "notebook", "data science", "tcp"],
  },
  {
    term: "9090",
    label: "Prometheus",
    note: "Prometheus monitorinq serverinin veb interfeysi və API-sinin default portudur.",
    section: "izleme",
    match: ["prometheus", "monitoring", "tcp"],
  },
  {
    term: "25565",
    label: "Minecraft",
    note: "Minecraft server protokolunun default portudur — şəbəkə portlarını öyrənərkən ən çox yadda qalan nümunələrdən biridir.",
    section: "izleme",
    match: ["minecraft", "game server", "tcp"],
  },
  {
    term: "6006",
    label: "Storybook",
    note: "Komponent kitabxanası Storybook-un dev serverinin default portudur.",
    section: "izleme",
    match: ["storybook", "component library", "tcp"],
  },
  {
    term: "9100",
    label: "Node Exporter",
    note: "Prometheus-un server metriklərini (CPU, yaddaş, disk) topladığı Node Exporter agentinin portudur.",
    section: "izleme",
    match: ["node exporter", "prometheus", "tcp"],
  },
  {
    term: "24224",
    label: "Fluentd",
    note: "Log toplayıcı Fluentd-nin daxili mesaj qəbulu üçün istifadə etdiyi portdur.",
    section: "izleme",
    match: ["fluentd", "log forwarding", "tcp"],
  },
  {
    term: "4318",
    label: "OpenTelemetry (HTTP)",
    note: "İzləmə (tracing) və metrik datasının OpenTelemetry kolektoruna HTTP üzərindən göndərildiyi portdur.",
    section: "izleme",
    match: ["opentelemetry", "otlp", "tracing", "tcp"],
  },
];
