/*
 * The rows for the `regex-spar` reference table — regular expression syntax,
 * written for the ECMAScript (JavaScript) flavour, one construct per row with
 * what it matches and a concrete pattern-plus-result example. React-free,
 * same shape as every other reference table's data file.
 */
import type { ReferenceRow, ReferenceSection } from "./reference";

export const regexSparSections: ReferenceSection[] = [
  { id: "sinif", label: "Simvol sinifləri" },
  { id: "tekrar", label: "Təkrar və kəmiyyət" },
  { id: "lovber", label: "Lövbər və sərhəd" },
  { id: "qrup", label: "Qruplaşdırma və istinad" },
  { id: "baxis", label: "Lookaround" },
  { id: "bayraq", label: "Bayraqlar" },
  { id: "qacir", label: "Qaçırılan simvollar" },
  { id: "unicode", label: "Unicode və AZ hərfləri" },
];

export const regexSparRows: ReferenceRow[] = [
  /* ---------- sinif ---------- */
  {
    term: ".",
    label: "istənilən simvol",
    note: "Sətir sonu simvolu (\\n) istisna, istənilən bir simvolu tutur. Sətir sonunu da tutması üçün `s` bayrağı lazımdır.",
    section: "sinif",
    example: '/a.c/ → "abc" tutur, amma "a\\nc" tutmur (s olmadan)',
    match: ["nöqtə", "istənilən simvol", "dot"],
  },
  {
    term: "\\d",
    label: "rəqəm",
    note: "Bir rəqəm simvolunu ([0-9]) tutur. Yalnız ASCII rəqəmlərdir — başqa yazı sistemlərinin rəqəmləri üçün `\\p{Nd}` lazımdır.",
    section: "sinif",
    example: '/\\d{3}/ → "994" tutur',
    match: ["rəqəm", "digit"],
  },
  {
    term: "\\d / \\D",
    label: "rəqəm / rəqəm olmayan",
    note: "`\\d` bir rəqəm simvolunu ([0-9]) tutur, `\\D` isə əksini — rəqəm olmayan istənilən simvolu. Yalnız ASCII rəqəmlərdir — başqa yazı sistemlərinin rəqəmi üçün `\\p{Nd}` lazımdır.",
    section: "sinif",
    example: '/\\d{3}/ → "994" tutur; /\\D+/ → "ünvan"dakı hərfləri tutur, rəqəmi tutmur',
    match: ["rəqəm", "digit", "rəqəm olmayan"],
  },
  {
    term: "\\w / \\W",
    label: "söz simvolu / söz olmayan",
    note: "`\\w` yalnız [A-Za-z0-9_] tutur — Azərbaycan hərflərini (ə ğ ı İ ö ş ü ç) TUTMUR, çünki bu sinif ASCII üçün təyin olunub; `\\W` onun əksidir. AZ hərfi lazımdırsa `\\p{L}` və `u` bayrağı işlədilməlidir.",
    section: "sinif",
    example: '/\\w+/ → "əli" sözündə yalnız "l" və "i" tutulur; /\\W/ isə "ə"ni tutur',
    match: ["söz simvolu", "word character", "söz olmayan", "azərbaycan hərfi tutmur"],
  },
  {
    term: "\\s / \\S",
    label: "boşluq / boşluq olmayan",
    note: "`\\s` boşluq, tab, yeni sətir kimi ağ boşluq simvollarını tutur, `\\S` isə əksini — boşluq olmayan istənilən simvolu.",
    section: "sinif",
    example: '/a\\sb/ → "a b" tutur, "ab" tutmur; /\\S+/ → "ali qasimov"da "ali" və "qasimov" ayrı tutulur',
    match: ["boşluq", "whitespace", "boşluq olmayan"],
  },
  {
    term: "[abc]",
    label: "simvol sinfi",
    note: "Mötərizədə sadalanan simvollardan yalnız birini tutur — sırasından asılı deyil.",
    section: "sinif",
    example: '/[aeiou]/ → "salam" içində "a" hərflərini tutur',
    match: ["simvol sinfi", "seçim mötərizəsi"],
  },
  {
    term: "[^abc]",
    label: "inkar sinfi",
    note: "Mötərizədəki `^` sinfi tərsinə çevirir — sadalananlardan BAŞQA istənilən simvolu tutur.",
    section: "sinif",
    example: '/[^0-9]/ → "a1b2" içində "a" və "b" tutulur',
    match: ["inkar sinfi", "istisna sinfi"],
  },
  {
    term: "[a-z]",
    label: "aralıq",
    note: "İki simvol arasında defislə göstərilən aralığı tutur — burada kiçik latın hərfləri.",
    section: "sinif",
    example: '/[a-z]+/ → "Salam2026" içində "alam" tutulur',
    match: ["hərf aralığı", "range"],
  },
  {
    term: "[a-zA-Z0-9_]",
    label: "\\w-nin əl ilə yazılışı",
    note: "`\\w` ilə eyni şeyi tutur, amma açıq yazıldığı üçün nəyin daxil olduğunu görmək asandır. AZ hərfi əlavə etmək istəsən aralığı özün genişləndirməlisən, yenə də tam düzgün olmur — `\\p{L}` daha etibarlıdır.",
    section: "sinif",
    example: '/[a-zA-Z0-9_]+/ → "user_1" tam tutulur',
    match: ["word sinfi əl ilə"],
  },

  /* ---------- tekrar ---------- */
  {
    term: "*",
    label: "0 və çox",
    note: "Əvvəlki elementin sıfır və ya daha çox təkrarını tutur — heç olmasa belə uyğun gəlir.",
    section: "tekrar",
    example: '/ab*c/ → "ac" və "abbbc" ikisini də tutur',
    match: ["ulduz", "sıfır və çox"],
  },
  {
    term: "+",
    label: "1 və çox",
    note: "Əvvəlki elementin ən azı bir dəfə təkrarını tələb edir.",
    section: "tekrar",
    example: '/ab+c/ → "abc" tutur, "ac" tutmur',
    match: ["bir və çox"],
  },
  {
    term: "?",
    label: "0 və ya 1",
    note: "Əvvəlki elementi opsional edir — ya var, ya yox, ikisi də uyğun sayılır.",
    section: "tekrar",
    example: '/colou?r/ → həm "color", həm "colour" tutur',
    match: ["opsional", "istəyə bağlı"],
  },
  {
    term: "{n}",
    label: "dəqiq n dəfə",
    note: "Əvvəlki elementin tam olaraq n dəfə təkrarını tələb edir — nə az, nə çox.",
    section: "tekrar",
    example: '/\\d{4}/ → "2026" tutur, "202" tutmur',
    match: ["dəqiq say"],
  },
  {
    term: "{n,}",
    label: "ən azı n dəfə",
    note: "Əvvəlki elementin ən azı n dəfə təkrarını tələb edir, yuxarı hədd yoxdur.",
    section: "tekrar",
    example: '/\\d{3,}/ → "12" tutmur, "1234567" tam tutulur',
    match: ["minimum say"],
  },
  {
    term: "{n,m}",
    label: "n-dən m-ə qədər",
    note: "Əvvəlki elementin n ilə m arasında (ikisi daxil) neçə dəfə təkrarına icazə verir.",
    section: "tekrar",
    example: '/\\d{2,4}/ → "12345" içindən yalnız "1234" tutulur',
    match: ["aralıq say"],
  },
  {
    term: "*?",
    label: "lazy 0+",
    note: "Aclıq deyil, tənbəllik — mümkün olan ƏN AZ simvolla uyğunluq axtarır. Adi `*` əksinə, mümkün qədər çox yığmağa çalışır (greedy).",
    section: "tekrar",
    example: '/<.*?>/ → "<a><b>" içində yalnız "<a>" tutur ("<.*>" isə hamısını tutardı)',
    match: ["lazy", "tənbəl təkrar"],
  },
  {
    term: "+?",
    label: "lazy 1+",
    note: "`+`-ın tənbəl variantı — ən azı bir, amma mümkün qədər az simvol tutmağa çalışır.",
    section: "tekrar",
    example: '/a.+?c/ → "aXcXc" içində yalnız "aXc" tutur',
    match: ["lazy", "tənbəl təkrar"],
  },
  {
    term: "??",
    label: "lazy 0-1",
    note: "`?`-in tənbəl variantı — mümkünsə elementi heç götürməməyi üstün tutur.",
    section: "tekrar",
    example: '/colou??r/ → əvvəlcə "color" formasını sınayır',
    match: ["lazy opsional"],
  },

  /* ---------- lovber ---------- */
  {
    term: "^",
    label: "başlanğıc",
    note: "Mətnin (m bayrağı ilə hər sətrin) başlanğıcını göstərir, heç bir simvol tutmur. `m` olmadan bütün mətnin, yalnız birinci sətrin əvvəlidir.",
    section: "lovber",
    example: '/^Salam/ → "Salam dünya" tutur, "Yaxşı, Salam" tutmur',
    match: ["başlanğıc lövbəri", "caret"],
  },
  {
    term: "$",
    label: "son",
    note: "Mətnin (m bayrağı ilə hər sətrin) sonunu göstərir. `m` olmadan bütün mətnin, yalnız son sətrin sonudur.",
    section: "lovber",
    example: '/dünya$/ → "salam dünya" tutur, "dünya salam" tutmur',
    match: ["son lövbəri", "dollar"],
  },
  {
    term: "\\b / \\B",
    label: "söz sərhədi / sərhəd olmayan",
    note: "`\\b` söz simvolu (\\w) ilə söz-olmayan simvol arasındakı sərhədi göstərir, heç bir simvol tutmur — bütöv sözü tapmaq üçün. `\\B` əksinə, sərhəd OLMAYAN mövqeləri, yəni sözün ortasını göstərir.",
    section: "lovber",
    example: '/\\bkat\\b/ → "kat" tutur, "kateqoriya" tutmur; /\\Bkat/ → "duplikat" içindəki "kat"ı tutur',
    match: ["söz sərhədi", "word boundary", "sərhəd olmayan"],
  },
  {
    term: "\\A",
    label: "mətnin əvvəli",
    note: "Mətnin mütləq əvvəlini göstərir, `m` bayrağından təsirlənmir — JavaScript-də dəstəklənmir, PCRE və Python-da var.",
    section: "lovber",
    example: 'Python: re.match(r"\\Asalam", mətn) yalnız mətnin əvvəlindəki "salam"ı tutur',
    match: ["mütləq başlanğıc"],
  },
  {
    term: "\\z",
    label: "mətnin sonu",
    note: "Mətnin mütləq sonunu göstərir, `m` bayrağından təsirlənmir — JavaScript-də dəstəklənmir, PCRE və Python-da var.",
    section: "lovber",
    example: 'Python: re.search(r"son\\z", mətn) yalnız mətnin sonundakı "son"u tutur',
    match: ["mütləq son"],
  },

  /* ---------- qrup ---------- */
  {
    term: "(...)",
    label: "tutan qrup",
    note: "Bir hissəni ayırıb nömrələnmiş qrup kimi yaddaşda saxlayır — nəticədə `m[1]`, `m[2]` kimi oxunur.",
    section: "qrup",
    example: '/(\\d{4})-(\\d{2})/ → "2026-09"da qrup 1 "2026", qrup 2 "09" olur',
    match: ["tutan qrup", "capturing group"],
  },
  {
    term: "(?:...)",
    label: "tutmayan qrup",
    note: "Simvolları qruplaşdırır (məsələn `|` və ya `*` üçün), amma nəticədə ayrıca qrup kimi saxlamır — yalnız quruluş üçün.",
    section: "qrup",
    example: '/(?:https?:\\/\\/)?example\\.com/ → "http://" olsun-olmasın uyğun gəlir, qrup siyahısında görünmür',
    match: ["tutmayan qrup", "non-capturing"],
  },
  {
    term: "(?<ad>...)",
    label: "adlandırılmış qrup",
    note: "Qrupu nömrə əvəzinə adla saxlayır — nəticədə `m.groups.ad` kimi oxunur, oxunaqlığı artırır.",
    section: "qrup",
    example: '/(?<il>\\d{4})-(?<ay>\\d{2})/ → "2026-09"da groups.il = "2026", groups.ay = "09"',
    match: ["adlandırılmış qrup", "named group"],
  },
  {
    term: "\\1",
    label: "nömrəli istinad",
    note: "Naxışın öz içində əvvəlki tutan qrupun tutduğu dəyəri təkrar tələb edir — məsələn eyni sözün iki dəfə gəlməsini tapmaq üçün.",
    section: "qrup",
    example: '/(\\w+) \\1/ → "salam salam" tutur, "salam görüş" tutmur',
    match: ["backreference", "geriyə istinad"],
  },
  {
    term: "\\k<ad>",
    label: "adlı istinad",
    note: "`\\1`-in adlandırılmış qrup versiyası — naxışın öz içində `(?<ad>...)` qrupunun dəyərinə istinad edir.",
    section: "qrup",
    example: '/(?<söz>\\w+)-\\k<söz>/ → "sınaq-sınaq" tutur',
    match: ["adlı geriyə istinad"],
  },
  {
    term: "|",
    label: "və ya",
    note: "İki və ya daha çox alternativdən birinin uyğun gəlməsini tələb edir — soldan sağa yoxlanır.",
    section: "qrup",
    example: '/pişik|it/ → "ev pişiyi" da, "küçə iti" da tutur',
    match: ["alternativ", "or işarəsi"],
  },

  /* ---------- baxis ---------- */
  {
    term: "(?=...)",
    label: "lookahead",
    note: "Naxışdan sonra müəyyən şeyin gəlməsini tələb edir, amma özü heç nə tutmur — nəticəyə daxil olmur.",
    section: "baxis",
    example: '/\\d+(?= AZN)/ → "150 AZN" içindən yalnız "150" tutulur',
    match: ["lookahead", "irəli baxış"],
  },
  {
    term: "(?!...)",
    label: "negative lookahead",
    note: "Naxışdan sonra müəyyən şeyin GƏLMƏMƏSİNİ tələb edir — özü heç nə tutmur.",
    section: "baxis",
    example: '/\\d+(?! AZN)/ → "150 AZN" içindəki "150"u yox, başqa yerdəki rəqəmi tutur',
    match: ["negative lookahead", "mənfi irəli baxış"],
  },
  {
    term: "(?<=...)",
    label: "lookbehind",
    note: "Naxışdan əvvəl müəyyən şeyin gəlməsini tələb edir, amma özü heç nə tutmur.",
    section: "baxis",
    example: '/(?<=\\$)\\d+/ → "$150" içindən yalnız "150" tutulur',
    match: ["lookbehind", "geri baxış"],
  },
  {
    term: "(?<!...)",
    label: "negative lookbehind",
    note: "Naxışdan əvvəl müəyyən şeyin GƏLMƏMƏSİNİ tələb edir — özü heç nə tutmur.",
    section: "baxis",
    example: '/(?<!\\$)\\d+/ → "$150 və 50" içindəki "50"ni tutur, "150"ni tutmur',
    match: ["negative lookbehind", "mənfi geri baxış"],
  },

  /* ---------- bayraq ---------- */
  {
    term: "g",
    label: "global",
    note: "İlk uyğunluqdan sonra dayanmır, bütün mətn boyu bütün uyğunluqları tapır.",
    section: "bayraq",
    example: '/a/g → "banana" içində 3 uyğunluq tapır, /a/ (g-siz) yalnız 1',
    match: ["global bayraq"],
  },
  {
    term: "i",
    label: "case-insensitive",
    note: "Böyük-kiçik hərf fərqini önəmsizləşdirir.",
    section: "bayraq",
    example: '/salam/i → "SALAM" və "Salam" ikisini də tutur',
    match: ["böyük kiçik hərf", "case insensitive"],
  },
  {
    term: "m",
    label: "multiline",
    note: "`^` və `$`-ı bütün mətnin yox, hər sətrin əvvəlinə/sonuna bağlayır.",
    section: "bayraq",
    example: '/^bənd/gm → hər sətir "bənd" ilə başlayırsa hamısını tutur',
    match: ["çoxsətirli", "multiline"],
  },
  {
    term: "s",
    label: "dotAll",
    note: "`.`-ə sətir sonu simvolunu (\\n) da tutmağa icazə verir — normalda `.` bunu keçir.",
    section: "bayraq",
    example: '/a.c/s → "a\\nc" tutur (s olmadan tutmazdı)',
    match: ["dotall", "nöqtə sətir sonunu tutsun"],
  },
  {
    term: "u",
    label: "unicode",
    note: "Naxışı düzgün Unicode kod nöqtəsi kimi oxuyur — `\\p{...}` sinifləri və emoji kimi surrogate cütlər yalnız bu bayraqla düzgün işləyir.",
    section: "bayraq",
    example: '/\\p{L}+/u → Azərbaycan hərflərini tutmaq üçün məcburidir',
    match: ["unicode bayrağı"],
  },
  {
    term: "y",
    label: "sticky",
    note: "Axtarışı mətnin istənilən yerində yox, məhz `lastIndex` mövqeyindən başlamağa məcbur edir — tokenizatorlarda ardıcıl oxuma üçün.",
    section: "bayraq",
    example: 'regex.lastIndex = 5; /\\d+/y həmin mövqedən başlamasa uyğunluq vermir',
    match: ["sticky bayrağı", "yapışqan"],
  },
  {
    term: "d",
    label: "indices",
    note: "Nəticəyə hər uyğunluğun və qrupun mətndəki başlanğıc/son indeksini (`.indices`) əlavə edir.",
    section: "bayraq",
    example: '/\\d+/d → nəticədə match.indices ilə "150"un tam mövqeyi görünür',
    match: ["indices bayrağı"],
  },

  /* ---------- qacir ---------- */
  {
    term: "\\.",
    label: "hərfi nöqtə",
    note: "Nöqtəni «istənilən simvol» mənasından çıxarıb hərfi nöqtə kimi tutur.",
    section: "qacir",
    example: '/192\\.168/ → "192.168" tutur, "192X168" tutmur',
    match: ["nöqtəni qaçır"],
  },
  {
    term: "\\\\",
    label: "hərfi tərs xətt",
    note: "Bir hərfi tərs xətti (\\) tutmaq üçün özü də qaçırılmalıdır.",
    section: "qacir",
    example: '/\\\\/ → "C:\\Users" mətnindəki "\\" işarəsini tutur',
    match: ["backslash qaçır"],
  },
  {
    term: "\\/",
    label: "hərfi sıfırlı xətt",
    note: "Naxış `/naxış/` şəklində yazılanda daxildəki `/` ilə naxışın sonunu bir-birindən ayırmaq üçün qaçırılır.",
    section: "qacir",
    example: '/https:\\/\\// → "https://" tutur',
    match: ["forward slash qaçır"],
  },
  {
    term: "\\$",
    label: "hərfi dollar",
    note: "Dolları «sətir sonu» lövbərindən çıxarıb hərfi dollar işarəsi kimi tutur.",
    section: "qacir",
    example: '/\\$\\d+/ → "$150" tutur',
    match: ["dollar qaçır"],
  },
  {
    term: "\\^",
    label: "hərfi qapaq",
    note: "Kareti «başlanğıc» lövbərindən çıxarıb hərfi `^` simvolu kimi tutur.",
    section: "qacir",
    example: '/a\\^b/ → "a^b" tutur',
    match: ["caret qaçır"],
  },
  {
    term: "\\[",
    label: "hərfi açıq mötərizə",
    note: "Kvadrat mötərizəni «simvol sinfi» başlanğıcından çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/\\[TODO\\]/ → "[TODO]" tutur',
    match: ["kvadrat mötərizə qaçır"],
  },
  {
    term: "\\]",
    label: "hərfi bağlı mötərizə",
    note: "Simvol sinfinin içindəki `]`-i sinfin sonu kimi oxunmaqdan çıxarır.",
    section: "qacir",
    example: '/\\[TODO\\]/ → "[TODO]" tutur',
    match: ["kvadrat mötərizə qaçır"],
  },
  {
    term: "\\(",
    label: "hərfi açıq mötərizə",
    note: "Adi mötərizəni qrup başlanğıcından çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/\\(\\d{3}\\)/ → "(994)" tutur',
    match: ["dairəvi mötərizə qaçır"],
  },
  {
    term: "\\)",
    label: "hərfi bağlı mötərizə",
    note: "Adi mötərizəni qrup sonundan çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/\\(\\d{3}\\)/ → "(994)" tutur',
    match: ["dairəvi mötərizə qaçır"],
  },
  {
    term: "\\{",
    label: "hərfi açıq fiqurlu mötərizə",
    note: "Fiqurlu mötərizəni kəmiyyət ({n}) sintaksisindən çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/\\{ad\\}/ → şablon mətnindəki "{ad}" sözünü hərfi tutur',
    match: ["fiqurlu mötərizə qaçır"],
  },
  {
    term: "\\}",
    label: "hərfi bağlı fiqurlu mötərizə",
    note: "Fiqurlu mötərizəni kəmiyyət sintaksisindən çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/\\{ad\\}/ → şablon mətnindəki "{ad}" sözünü hərfi tutur',
    match: ["fiqurlu mötərizə qaçır"],
  },
  {
    term: "\\|",
    label: "hərfi şaquli xətt",
    note: "Şaquli xətti «və ya» mənasından çıxarıb hərfi simvol kimi tutur.",
    section: "qacir",
    example: '/a\\|b/ → "a|b" mətnini tam tutur',
    match: ["pipe qaçır"],
  },
  {
    term: "\\+",
    label: "hərfi plus",
    note: "Plusu «bir və çox» kəmiyyətindən çıxarıb hərfi işarə kimi tutur.",
    section: "qacir",
    example: '/C\\+\\+/ → "C++" tutur',
    match: ["plus qaçır"],
  },
  {
    term: "\\*",
    label: "hərfi ulduz",
    note: "Ulduzu «sıfır və çox» kəmiyyətindən çıxarıb hərfi işarə kimi tutur.",
    section: "qacir",
    example: '/2\\*2=4/ → "2*2=4" tutur',
    match: ["ulduz qaçır"],
  },
  {
    term: "\\?",
    label: "hərfi sual işarəsi",
    note: "Sual işarəsini «opsional» kəmiyyətindən çıxarıb hərfi işarə kimi tutur.",
    section: "qacir",
    example: '/nə vaxt\\?/ → "nə vaxt?" tutur',
    match: ["sual işarəsi qaçır"],
  },
  {
    term: "\\n",
    label: "yeni sətir",
    note: "Yeni sətir simvolunu tutur — çoxsətirli mətndə sətirlərin arasını tapmaq üçün.",
    section: "qacir",
    example: '/sətir1\\nsətir2/ → aralarında yeni sətir olan "sətir1\\nsətir2"nü tutur',
    match: ["newline"],
  },
  {
    term: "\\t",
    label: "tab",
    note: "Tab simvolunu tutur — TSV kimi tab ilə ayrılmış mətn formatlarını parçalayanda faydalıdır.",
    section: "qacir",
    example: '/ad\\tsoyad/ → aralarında tab olan mətni tutur',
    match: ["tab simvolu"],
  },
  {
    term: "\\r",
    label: "karvan qaytarma",
    note: "Carriage return simvolunu tutur — Windows stilli sətir sonu (\\r\\n) təmizləyəndə lazım olur.",
    section: "qacir",
    example: '/\\r\\n/g → Windows sətir sonlarını tapıb təmizləmək üçün',
    match: ["carriage return"],
  },
  {
    term: "\\0",
    label: "boş simvol",
    note: "NUL simvolunu (kod nöqtəsi 0) tutur — praktikada nadir hallarda, ikilik mətndə rast gəlinir.",
    section: "qacir",
    example: '/\\0/ → NUL baytını tutur',
    match: ["null simvolu"],
  },
  {
    term: "\\xhh",
    label: "hex kod",
    note: "İki rəqəmli hex kodla göstərilən Latin-1 simvolunu tutur — məsələn `\\x41` böyük hərf «A»-dır.",
    section: "qacir",
    example: '/\\x41/ → "A" hərfini tutur',
    match: ["hex simvol kodu"],
  },
  {
    term: "\\uhhhh",
    label: "unicode kod (4 rəqəm)",
    note: "Dörd rəqəmli hex kodla UTF-16 vahidini tutur — Azərbaycan hərfi «ə» üçün `\\u0259`.",
    section: "qacir",
    example: '/\\u0259/ → "ə" hərfini tutur',
    match: ["unicode kod nöqtəsi"],
  },
  {
    term: "\\u{...}",
    label: "unicode kod (dəyişən uzunluq)",
    note: "`u` bayrağı ilə işləyəndə istənilən uzunluqda kod nöqtəsini göstərir — surrogate cütlərə ehtiyac olmadan emoji kimi geniş simvolları da tutur.",
    section: "qacir",
    example: '/\\u{1F600}/u → gülən emoji simvolunu tutur',
    match: ["genişləndirilmiş unicode kodu"],
  },
  {
    term: "[.]",
    label: "sinif daxilində sadə nöqtə",
    note: "Simvol sinfinin (`[...]`) içində nöqtə artıq «istənilən simvol» demək deyil, avtomatik hərfidir — burada ayrıca `\\.` yazmağa ehtiyac yoxdur.",
    section: "qacir",
    example: '/[.,;]/ → "." "," ";" işarələrindən birini hərfi mənada tutur, qaçırma tələb etmir',
    match: ["mötərizə içində qaçırma lazım deyil"],
  },

  /* ---------- unicode ---------- */
  {
    term: "\\p{L}",
    label: "istənilən hərf",
    note: "Latın, kiril, ərəb — istənilən yazı sistemindən istənilən hərfi tutur. Azərbaycan hərflərini (ə ğ ı İ ö ş ü ç) tutmaq üçün `\\w` əvəzinə bu işlədilməlidir. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{L}+/u → "əli" sözünü tam tutur, "\\w+" isə yalnız "l" və "i"ni tutardı',
    match: ["hər hansı hərf", "azərbaycan hərfi", "unicode hərf"],
  },
  {
    term: "\\p{Lu}",
    label: "böyük hərf",
    note: "Yalnız böyük hərfləri tutur — Azərbaycanın nöqtəli İ-si daxil. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{Lu}/gu → "İstanbul" sözündən "İ" hərfini tutur',
    match: ["böyük hərf unicode"],
  },
  {
    term: "\\p{Ll}",
    label: "kiçik hərf",
    note: "Yalnız kiçik hərfləri tutur. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{Ll}+/gu → "İstanbul" sözündən "stanbul" hissəsini tutur',
    match: ["kiçik hərf unicode"],
  },
  {
    term: "\\p{Nd}",
    label: "onluq rəqəm",
    note: "Yalnız ASCII deyil, istənilən yazı sistemindəki onluq rəqəmi tutur. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{Nd}+/gu → ərəb-hind rəqəmləri daxil bütün onluq rəqəm sistemlərini tutur',
    match: ["unicode rəqəm"],
  },
  {
    term: "\\p{N}",
    label: "istənilən rəqəm",
    note: "`\\p{Nd}`-dən genişdir — kəsr, romalı rəqəm kimi digər rəqəm kateqoriyalarını da tutur. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{N}/gu → "Ⅷ" (roma rəqəmi) simvolunu da tutur',
    match: ["hər hansı rəqəm unicode"],
  },
  {
    term: "\\p{Script=Latin}",
    label: "yazı sistemi",
    note: "Yalnız müəyyən yazı sisteminə aid simvolları tutur — mətndə latın və kiril qarışığını ayırmaq üçün faydalıdır. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{Script=Latin}+/gu → qarışıq mətndə yalnız latın hərflərindən ibarət hissələri tutur',
    match: ["yazı sistemi", "script unicode"],
  },
  {
    term: "\\p{P}",
    label: "durğu işarəsi",
    note: "İstənilən yazı sistemindəki durğu işarələrini (nöqtə, vergül, dırnaq və s.) tutur. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{P}/gu → "salam, necəsən?" mətnindəki "," və "?" işarələrini tutur',
    match: ["durğu işarəsi unicode", "punctuation"],
  },
  {
    term: "\\p{Alphabetic}",
    label: "əlifba simvolu",
    note: "`\\p{L}`-dən bir az genişdir — hərflərlə yanaşı hərf sayılan digər əlifba simvollarını da (məsələn bəzi diakritik işarələri) tutur. Yalnız `u` bayrağı ilə işləyir.",
    section: "unicode",
    example: '/\\p{Alphabetic}+/gu → əlifba mənşəli istənilən simvolu tutur',
    match: ["əlifba simvolu unicode"],
  },
];
