/*
 * The HTTP response status codes — which one a server returns and why, not a
 * literal translation of the English name. Every `note` explains the real
 * situation the code stands for, because the name "Not Found" on its own does
 * not tell anybody the difference between 404 and 410.
 *
 * Sections follow the code's leading digit, the same split RFC 9110 itself
 * uses.
 */
import type { ReferenceRow, ReferenceSection } from "./reference.js";

export const statusKodlariSections: ReferenceSection[] = [
  {
    id: "1xx",
    label: "1xx",
    hint: "İnformasiya: sorğu davam edir, əməliyyat hələ bitməyib.",
  },
  {
    id: "2xx",
    label: "2xx",
    hint: "Uğur: sorğu qəbul edildi və istənilən kimi icra olundu.",
  },
  {
    id: "3xx",
    label: "3xx",
    hint: "Yönləndirmə: resurs başqa ünvandadır və ya keşdəki nüsxə etibarlıdır.",
  },
  {
    id: "4xx",
    label: "4xx",
    hint: "Müştəri xətası: sorğuda problem var, server onu icra edə bilmir.",
  },
  {
    id: "5xx",
    label: "5xx",
    hint: "Server xətası: sorğu düzgündür, server onu yerinə yetirə bilmədi.",
  },
];

export const statusKodlariRows: ReferenceRow[] = [
  // 1xx
  {
    term: "100",
    label: "Continue",
    section: "1xx",
    note: "Server sorğunun başlığını qəbul etdi və müştəriyə gövdəni göndərməyə davam etməsini bildirir. Böyük POST sorğularında server gövdəni oxumadan əvvəl başlıqları yoxlamaq üçün işlədilir.",
    match: ["davam et", "continue"],
  },
  {
    term: "101",
    label: "Switching Protocols",
    section: "1xx",
    note: "Server `Upgrade` başlığındakı tələbi qəbul edib protokolu dəyişir: HTTP bağlantısını WebSocket-ə keçirəndə bu kod qaytarılır.",
    match: ["websocket", "protokol deyisimi", "switching protocols"],
  },
  {
    term: "102",
    label: "Processing",
    section: "1xx",
    note: "WebDAV sorğusunun icrası davam edir, amma hələ nəticə yoxdur. Uzun sürən əməliyyatlarda müştərinin bağlantını vaxtından əvvəl kəsməməsi üçün göndərilir.",
    match: ["webdav", "processing"],
  },
  {
    term: "103",
    label: "Early Hints",
    section: "1xx",
    note: "Server əsas cavabı hazırlayarkən brauzerə `Link` başlığı ilə hansı resursları əvvəlcədən yükləməyə başlaya biləcəyini bildirir: səhifə sürətini artırmaq üçün işlədilir.",
    match: ["erken ipucu", "preload", "early hints"],
  },

  // 2xx
  {
    term: "200",
    label: "OK",
    section: "2xx",
    note: "Sorğu uğurla icra olundu və cavab gövdəsində istənilən nəticə var. Ən çox işlədilən uğur kodudur: GET, POST və digər metodların standart uğur cavabıdır.",
    match: ["ok", "ugur"],
  },
  {
    term: "201",
    label: "Created",
    section: "2xx",
    note: "Sorğu nəticəsində serverdə yeni resurs yaradıldı: adətən POST ilə yeni qeyd əlavə edildikdə qaytarılır. Cavabda çox vaxt yeni resursun ünvanı `Location` başlığında gəlir.",
    match: ["yaradildi", "created"],
  },
  {
    term: "202",
    label: "Accepted",
    section: "2xx",
    note: "Sorğu qəbul edildi, amma emalı hələ bitməyib, nəticə sonradan hazır olacaq. Növbəyə atılan asinxron əməliyyatlarda işlədilir, uğur təminatı vermir.",
    match: ["qebul edildi", "asinxron", "accepted"],
  },
  {
    term: "203",
    label: "Non-Authoritative Information",
    section: "2xx",
    note: "Cavab orijinal serverdən deyil, aradakı bir proksi və ya keşdən gəlib və dəyişdirilmiş ola bilər. Nadir hallarda görünür, əksər müştəri onu adi 200 kimi qəbul edir.",
    match: ["proksi", "non-authoritative"],
  },
  {
    term: "204",
    label: "No Content",
    section: "2xx",
    note: "Sorğu uğurla icra olundu, amma cavabda göndəriləcək gövdə yoxdur: silmə əməliyyatlarında və ya formanın səhifəni yeniləmədən təsdiqində işlədilir.",
    match: ["mezmun yoxdur", "no content"],
  },
  {
    term: "205",
    label: "Reset Content",
    section: "2xx",
    note: "Sorğu uğurludur və server müştəridən formanı və ya görünüşü ilkin vəziyyətinə sıfırlamasını istəyir. 204-dən fərqli olaraq açıq sıfırlama tələb edir.",
    match: ["formani sifirla", "reset content"],
  },
  {
    term: "206",
    label: "Partial Content",
    section: "2xx",
    note: "Server `Range` başlığı ilə istənilən resursun yalnız bir hissəsini qaytarır: video axını və fasilədən sonra davam edən yükləmələrdə işlədilir.",
    match: ["range", "hisseli yukleme", "partial content"],
  },
  {
    term: "207",
    label: "Multi-Status",
    section: "2xx",
    note: "WebDAV sorğusunda bir neçə fərqli əməliyyatın nəticəsi ayrı-ayrı statuslarla bir cavabda birləşdirilir: hər alt-əməliyyatın öz kodu ola bilər.",
    match: ["webdav", "multi-status"],
  },
  {
    term: "208",
    label: "Already Reported",
    section: "2xx",
    note: "WebDAV bağlamasında eyni resurs artıq əvvəlki 207 cavabında sadalanıb, təkrar sadalanmasının qarşısını almaq üçün işlədilir.",
    match: ["webdav", "already reported"],
  },
  {
    term: "226",
    label: "IM Used",
    section: "2xx",
    note: "Server sorğuya uyğun instansiya manipulyasiyalarını tətbiq edib və cavab bunun nəticəsidir: HTTP Delta encoding genişlənməsinin nadir işlədilən kodudur.",
    match: ["delta encoding", "im used"],
  },

  // 3xx
  {
    term: "300",
    label: "Multiple Choices",
    section: "3xx",
    note: "Sorğuya uyğun bir neçə variant var və server hansının seçiləcəyini bilmir, məsələn eyni sənədin fərqli dillərdəki versiyaları. Praktikada demək olar ki işlədilmir.",
    match: ["yönləndirmə", "coxlu secim", "multiple choices"],
  },
  {
    term: "301",
    label: "Moved Permanently",
    section: "3xx",
    note: "Resurs həmişəlik yeni ünvana köçürülüb. Axtarış sistemləri köhnə ünvanın reytinq dəyərini yeni ünvana ötürür, brauzer və keş yeni ünvanı yadda saxlayır.",
    match: ["yönləndirmə", "daimi yonlendirme", "moved permanently"],
  },
  {
    term: "302",
    label: "Found",
    section: "3xx",
    note: "Resurs müvəqqəti olaraq başqa ünvandadır, köhnə ünvan hələ də etibarlıdır. Tarixən bəzi köhnə müştərilər bunu POST-u GET-ə çevirərək səhv işlətdiyi üçün 303 və 307 ayrıca yaradılıb.",
    match: ["yönləndirmə", "muveqqeti yonlendirme"],
  },
  {
    term: "303",
    label: "See Other",
    section: "3xx",
    note: "Nəticəni başqa bir ünvandan GET metodu ilə almaq lazımdır: adətən forma göndərildikdən sonra nəticə səhifəsinə yönləndirmək üçün işlədilir, metod həmişə GET-ə dəyişir.",
    match: ["yönləndirmə", "see other"],
  },
  {
    term: "304",
    label: "Not Modified",
    section: "3xx",
    note: "Müştərinin keşdəki nüsxəsi hələ etibarlıdır, server yenidən göndərmir. `If-None-Match` və ya `If-Modified-Since` başlığı ilə edilən şərtli sorğuya cavab kimi gəlir, gövdə boşdur.",
    match: ["yönləndirmə", "kesden oxu", "not modified"],
  },
  {
    term: "305",
    label: "Use Proxy",
    section: "3xx",
    note: "Sorğunun bir proksi vasitəsilə edilməli olduğunu bildirirdi: təhlükəsizlik səbəbindən köhnəlmiş elan olunub, müasir brauzerlər bunu nəzərə almır.",
    match: ["yönləndirmə", "kohnelib", "use proxy"],
  },
  {
    term: "306",
    label: "(Unused)",
    section: "3xx",
    note: "Erkən HTTP versiyasında ayrılmış koddur, heç vaxt rəsmi mənada işlədilməyib və indi ehtiyat kimi saxlanılır. Server bunu heç vaxt qaytarmamalıdır.",
    match: ["yönləndirmə", "islenmir", "unused"],
  },
  {
    term: "307",
    label: "Temporary Redirect",
    section: "3xx",
    note: "302-nin dəqiqləşdirilmiş versiyası: resurs müvəqqəti başqa ünvandadır, amma metod və gövdə dəyişmədən təkrarlanmalıdır. POST sorğusu POST olaraq yönləndirilir.",
    match: ["yönləndirmə", "temporary redirect"],
  },
  {
    term: "308",
    label: "Permanent Redirect",
    section: "3xx",
    note: "301-in dəqiqləşdirilmiş versiyası: resurs həmişəlik köçüb, amma metod dəyişmir. API-lərdə POST-un GET-ə düşməsi istənmirsə 301 əvəzinə bu işlədilir.",
    match: ["yönləndirmə", "permanent redirect"],
  },

  // 4xx
  {
    term: "400",
    label: "Bad Request",
    section: "4xx",
    note: "Sorğunun özündə problem var: sintaksis səhvi, yanlış format və ya server onu ümumiyyətlə emal edə bilmir. Xəta müştəri tərəfindədir, sorğu düzəldilmədən təkrarlanmamalıdır.",
    match: ["yanlis sorgu", "bad request"],
  },
  {
    term: "401",
    label: "Unauthorized",
    section: "4xx",
    note: "Sorğu kimlik təyini tələb edir və ya göndərilən məlumat yanlışdır: kim olduğu təsdiqlənməyib. Server adətən `WWW-Authenticate` başlığı ilə hansı üsulun gözlənildiyini bildirir.",
    match: ["kimlik teyini", "unauthorized"],
  },
  {
    term: "402",
    label: "Payment Required",
    section: "4xx",
    note: "Rəsmi mənada rezerv edilib, ödəniş tələb edən mikroödəniş sistemləri üçün nəzərdə tutulmuşdu, amma heç vaxt geniş standartlaşmayıb. Bəzi API-lər bunu limit bitdiyini bildirmək üçün qeyri-rəsmi işlədir.",
    match: ["payment required"],
  },
  {
    term: "403",
    label: "Forbidden",
    section: "4xx",
    note: "Server kim olduğunu bilir, amma bu resursa girişə icazə vermir: icazənin çatışmazlığıdır, kimlik təyini problemi deyil. Yenidən daxil olmaq bunu həll etmir.",
    match: ["qadagandir", "forbidden"],
  },
  {
    term: "404",
    label: "Not Found",
    section: "4xx",
    note: "Ünvan serverə çatdı, amma orada belə bir resurs yoxdur. Resursun heç vaxt olmadığı da, silindiyi də bu kodu alır, silindiyini ayrıca bildirmək üçün 410 var.",
    match: ["tapilmadi", "not found"],
  },
  {
    term: "405",
    label: "Method Not Allowed",
    section: "4xx",
    note: "Resurs mövcuddur, amma işlədilən metod (məsələn DELETE) ona qadağandır. Server `Allow` başlığında hansı metodların icazəli olduğunu qaytarmalıdır.",
    match: ["metoda icaze yoxdur", "method not allowed"],
  },
  {
    term: "406",
    label: "Not Acceptable",
    section: "4xx",
    note: "Server `Accept` başlığında istənilən formatda cavab hazırlaya bilmir, məsələn müştəri yalnız XML qəbul edir, server isə yalnız JSON verə bilir.",
    match: ["not acceptable"],
  },
  {
    term: "407",
    label: "Proxy Authentication Required",
    section: "4xx",
    note: "401-in proksi versiyası: sorğu aradakı proksi serverdən keçmək üçün ayrıca kimlik təyini tələb edir, son server bununla bağlı deyil.",
    match: ["proksi kimlik teyini", "proxy authentication"],
  },
  {
    term: "408",
    label: "Request Timeout",
    section: "4xx",
    note: "Server müştərinin sorğunu tam göndərməsini gözlədi, amma vaxt bitdi. Yavaş və ya qırılan bağlantılarda görünür.",
    match: ["vaxti kecdi", "request timeout"],
  },
  {
    term: "409",
    label: "Conflict",
    section: "4xx",
    note: "Sorğu resursun cari vəziyyəti ilə ziddiyyət təşkil edir, məsələn eyni adda qeyd artıq mövcuddur və ya versiya uyğunsuzluğu var. Sorğunu təkrarlamazdan əvvəl vəziyyəti yoxlamaq lazımdır.",
    match: ["ziddiyet", "conflict"],
  },
  {
    term: "410",
    label: "Gone",
    section: "4xx",
    note: "Resurs qəsdən silinib və bu daimidir: server bunu bilərəkdən bildirir, sadəcə tapılmadığını demir. Axtarış sistemləri bu kodu adi tapılmama xətasından daha sürətli indeksdən çıxarır.",
    match: ["silinib", "gone"],
  },
  {
    term: "411",
    label: "Length Required",
    section: "4xx",
    note: "Server sorğuda `Content-Length` başlığının olmasını tələb edir, amma müştəri onu göndərməyib.",
    match: ["length required"],
  },
  {
    term: "412",
    label: "Precondition Failed",
    section: "4xx",
    note: "Sorğuda göndərilən şərti başlıqlardan (`If-Match`, `If-Unmodified-Since`) biri doğrulanmadı: server resursun vəziyyətinin gözlənildiyi ilə üst-üstə düşmədiyini bildirir.",
    match: ["precondition failed"],
  },
  {
    term: "413",
    label: "Payload Too Large",
    section: "4xx",
    note: "Göndərilən gövdə serverin qəbul edə biləcəyi ölçüdən böyükdür: böyük fayl yükləmələrində ən çox rast gəlinən xətadır.",
    match: ["payload too large", "content too large"],
  },
  {
    term: "414",
    label: "URI Too Long",
    section: "4xx",
    note: "Sorğu ünvanı serverin işləmək istədiyindən uzundur: adətən GET sorğusuna həddindən artıq parametr əlavə edildikdə baş verir.",
    match: ["uri too long"],
  },
  {
    term: "415",
    label: "Unsupported Media Type",
    section: "4xx",
    note: "Göndərilən gövdənin `Content-Type`-ı server tərəfindən dəstəklənmir, məsələn server yalnız JSON gözləyərkən form-data göndərilib.",
    match: ["unsupported media type"],
  },
  {
    term: "416",
    label: "Range Not Satisfiable",
    section: "4xx",
    note: "Sorğuda istənilən bayt aralığı (`Range` başlığı) resursun ölçüsündən kənardadır və server onu qarşılaya bilmir.",
    match: ["range not satisfiable"],
  },
  {
    term: "417",
    label: "Expectation Failed",
    section: "4xx",
    note: "Müştərinin `Expect` başlığında bildirdiyi şərti server yerinə yetirə bilmir: nadir hallarda `Expect: 100-continue` ilə bağlı görünür.",
    match: ["expectation failed"],
  },
  {
    term: "418",
    label: "I'm a teapot",
    section: "4xx",
    note: "1 aprel zarafatı olaraq HTCPCP protokolunda yaradılıb: server çay dəmləmək istənilən sorğu ilə qarşılaşanda bunu qaytarır. Rəsmi RFC-dən çıxarılıb, amma bəzi API-lər bot filtrləmə üçün hələ də işlədir.",
    match: ["teapot", "cayniki"],
  },
  {
    term: "421",
    label: "Misdirected Request",
    section: "4xx",
    note: "Sorğu bu cavabı verə bilməyəcək serverə yönləndirilib: bir TCP bağlantısı bir neçə domeni paylaşanda (HTTP/2 connection coalescing) baş verə bilər.",
    match: ["misdirected request"],
  },
  {
    term: "422",
    label: "Unprocessable Content",
    section: "4xx",
    note: "Sorğunun sintaksisi düzgündür, amma göndərilən məlumat mənaca yanlışdır: validasiya xətaları üçün ən uyğun koddur, məsələn tələb olunan sahə boş qalıb.",
    match: ["unprocessable entity", "validasiya xetasi"],
  },
  {
    term: "423",
    label: "Locked",
    section: "4xx",
    note: "WebDAV-da resurs kilidlənib, sorğu icra oluna bilmir. Adətən başqa bir proses həmin resurs üzərində işləyərkən görünür.",
    match: ["webdav", "locked"],
  },
  {
    term: "424",
    label: "Failed Dependency",
    section: "4xx",
    note: "WebDAV sorğusu asılı olduğu başqa bir əməliyyatın uğursuz olması səbəbindən icra edilmədi.",
    match: ["webdav", "failed dependency"],
  },
  {
    term: "425",
    label: "Too Early",
    section: "4xx",
    note: "Server TLS 0-RTT ilə göndərilən sorğunu təkrar oyun (replay) riski olduğu üçün icra etmək istəmir: vaxtından əvvəl göndərilmiş sorğulara qarşı qorunmadır.",
    match: ["too early"],
  },
  {
    term: "426",
    label: "Upgrade Required",
    section: "4xx",
    note: "Server bu sorğunu yalnız fərqli bir protokolla (məsələn TLS) icra edəcək: `Upgrade` başlığında gözlədiyi protokolu bildirir.",
    match: ["upgrade required"],
  },
  {
    term: "428",
    label: "Precondition Required",
    section: "4xx",
    note: "Server sorğuda şərti başlığın (`If-Match` kimi) olmasını tələb edir, iki müştərinin eyni resursu bilmədən üzərinə yazmasının qarşısını almaq üçün.",
    match: ["precondition required"],
  },
  {
    term: "429",
    label: "Too Many Requests",
    section: "4xx",
    note: "Müştəri qısa müddətdə həddindən çox sorğu göndərib: sürət məhdudiyyəti (rate limiting) işə düşüb. `Retry-After` başlığı nə vaxt yenidən cəhd etmək lazım olduğunu göstərə bilər.",
    match: ["rate limit", "too many requests"],
  },
  {
    term: "431",
    label: "Request Header Fields Too Large",
    section: "4xx",
    note: "Sorğunun başlıqları (tək-tək və ya cəmi) serverin qəbul edə biləcəyi ölçüdən böyükdür: çox böyük kuki və ya token bu xətaya səbəb ola bilər.",
    match: ["header fields too large"],
  },
  {
    term: "451",
    label: "Unavailable For Legal Reasons",
    section: "4xx",
    note: "Resurs hüquqi qərar səbəbindən (məhkəmə qərarı, senzura tələbi) əlçatan deyil. Ad Ray Bradbury-nin 451 romanına istinadən seçilib, cavab çox vaxt qərarın mənbəyini göstərir.",
    match: ["huquqi sebeb", "legal reasons"],
  },

  // 5xx
  {
    term: "500",
    label: "Internal Server Error",
    section: "5xx",
    note: "Serverdə gözlənilməz xəta baş verdi və problemin dəqiq səbəbi bu kodla bildirilmir: tətbiqin özündəki istisnalar, kod xətaları adətən bura düşür.",
    match: ["daxili server xetasi", "internal server error"],
  },
  {
    term: "501",
    label: "Not Implemented",
    section: "5xx",
    note: "Server sorğuda işlədilən metodu tanımır və ya dəstəkləmir: resursla bağlı deyil, serverin ümumi imkanı ilə bağlıdır.",
    match: ["not implemented"],
  },
  {
    term: "502",
    label: "Bad Gateway",
    section: "5xx",
    note: "Server proksi və ya gateway rolunda işləyir və arxadakı serverdən etibarsız cavab alıb. Problem çox vaxt arxa serverin çökməsi və ya səhv formatda cavab verməsidir.",
    match: ["bad gateway"],
  },
  {
    term: "503",
    label: "Service Unavailable",
    section: "5xx",
    note: "Server hazırda sorğunu qarşılaya bilmir: yüklənmə, baxım işi və ya resurs çatışmazlığı səbəbindən. Adətən müvəqqətidir, `Retry-After` başlığı ilə nə vaxt yenidən cəhd etmək göstərilə bilər.",
    match: ["service unavailable", "baxim isi"],
  },
  {
    term: "504",
    label: "Gateway Timeout",
    section: "5xx",
    note: "Server proksi rolunda arxadakı serverdən cavab gözlədi, amma vaxtında cavab gəlmədi. Fərq ondadır ki, arxa server heç cavab verməyib, səhv cavab verməyib.",
    match: ["gateway timeout"],
  },
  {
    term: "505",
    label: "HTTP Version Not Supported",
    section: "5xx",
    note: "Server sorğuda işlədilən HTTP protokol versiyasını dəstəkləmir.",
    match: ["http version not supported"],
  },
  {
    term: "506",
    label: "Variant Also Negotiates",
    section: "5xx",
    note: "Server məzmun danışığı (content negotiation) üçün konfiqurasiya xətası ilə üzləşib: seçilən variantın özü də danışıq apara bilən resurs kimi qeyd olunub, dövr yaranıb.",
    match: ["variant also negotiates"],
  },
  {
    term: "507",
    label: "Insufficient Storage",
    section: "5xx",
    note: "WebDAV serverində sorğunu tamamlamaq üçün kifayət qədər yaddaş sahəsi yoxdur.",
    match: ["webdav", "insufficient storage"],
  },
  {
    term: "508",
    label: "Loop Detected",
    section: "5xx",
    note: "WebDAV serveri sorğunu icra edərkən sonsuz dövr aşkarladı: adətən bir-birinə istinad edən resurslar arasında yaranır.",
    match: ["webdav", "loop detected"],
  },
  {
    term: "510",
    label: "Not Extended",
    section: "5xx",
    note: "Sorğunu icra etmək üçün əlavə genişləndirmə tələb olunur, amma server bunu almayıb: HTTP Extension Framework ilə bağlı nadir işlədilən koddur.",
    match: ["not extended"],
  },
  {
    term: "511",
    label: "Network Authentication Required",
    section: "5xx",
    note: "İnternetə çıxış üçün əvvəlcə şəbəkədə kimlik təyini lazımdır: otel və ya hava limanı Wi-Fi-ında görünən \"captive portal\" səhifələri bu kodu işlədir.",
    match: ["captive portal", "network authentication required"],
  },
];
