/**
 * CIDR reference table: what a prefix length actually means, for every
 * IPv4 prefix, the IPv6 prefixes that come up in practice, and the address
 * ranges that are reserved rather than routable.
 *
 * `subnet` and `subnet-planlayici` compute an answer for the address someone
 * types in; this tool has no input at all — it is the table somebody scans
 * with their eyes, or searches by typing the one fragment they remember
 * (a mask, a wildcard, a hex value, a well-known block). That is why the
 * IPv4 half is generated by a loop rather than typed out 33 times: a prefix
 * length determines its mask, its wildcard, its hex form and its address
 * count by a fixed formula, and retyping a formula's output by hand is
 * exactly how a `/24` row ends up with a `/23` mask nobody notices until
 * somebody's ACL breaks. Only the sentence explaining what a block *of that
 * size* is actually used for is hand-written, because a formula cannot know
 * that a `/29` is what an ISP hands out behind a firewall.
 *
 * The worked example in every IPv4 row's `example` field is the same base
 * address, 203.0.113.45, masked down for that row — one of RFC 5737's
 * documentation addresses (see the `ayrilmis` section below), chosen so the
 * examples are consistent with each other and never look like a real
 * assignment. The IPv6 rows are hand-picked rather than generated, because
 * unlike IPv4's uniform 0–32 there is no complete list of prefixes anyone
 * looks up — only the handful that mean something (`/64` for SLAAC, `/48`
 * for a site) — but every address count is still computed from the prefix
 * with `BigInt`, never typed, because an IPv6 block's size stops fitting in
 * a normal number well before `/64`.
 */
import type { ReferenceRow, ReferenceSection } from "./reference";

export const subnetCedveliSections: ReferenceSection[] = [
  {
    id: "ipv4",
    label: "IPv4 prefiksləri",
    hint: "/32-dən /0-a qədər bütün 33 prefiks: maska, wildcard və nə üçün işlədildiyi.",
  },
  {
    id: "ipv6",
    label: "IPv6 prefiksləri",
    hint: "IPv6-da yayım (broadcast) ünvanı yoxdur, ona görə burada 'istifadə oluna bilən host' IPv4-dəki kimi cəmi-2 düsturu ilə hesablanmır, bloku bütöv əhatə edən ünvan sayı göstərilir.",
  },
  { id: "ayrilmis", label: "Ayrılmış və xüsusi diapazonlar" },
];

/* ---------- IPv4: generated, not typed ---------- */

function maskFromPrefix(prefix: number): number {
  if (prefix <= 0) return 0;
  if (prefix >= 32) return 0xffffffff;
  return (0xffffffff << (32 - prefix)) >>> 0;
}

function formatIpv4(value: number): string {
  const unsigned = value >>> 0;
  return [
    (unsigned >>> 24) & 0xff,
    (unsigned >>> 16) & 0xff,
    (unsigned >>> 8) & 0xff,
    unsigned & 0xff,
  ].join(".");
}

function toHexMask(value: number): string {
  return (value >>> 0).toString(16).padStart(8, "0");
}

/** Thousands-grouped digits with a thin space, same convention the subnet
 *  calculator uses for the same reason: a bare `4294967296` is not a number
 *  anyone can read at a glance. */
function formatCount(value: number): string {
  return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}

/** RFC 5737 TEST-NET-3 — reserved exactly for use in examples like this one. */
const DEMO_ADDRESS = (((203 << 24) | (0 << 16) | (113 << 8) | 45) >>> 0) as number;

/**
 * What a block of this size is actually used for, or where it shows up.
 * The one thing per prefix a formula cannot produce — every number inside
 * these sentences still comes from the loop below, never typed here.
 */
const IPV4_USAGE: Record<number, string> = {
  0: "Marşrutlaşdırma cədvəlində 0.0.0.0/0 default marşrutu bildirir: paket üçün daha dəqiq uyğun qeyd tapılmayanda bu yol seçilir.",
  1: "İnternetin yarısı qədər böyükdür, LAN-da deyil, yalnız marşrutlaşdırma cədvəllərində və nəhəng blok bölgüsündə rast gəlinir.",
  2: "Fəzanın dörddə biridir, LAN-da deyil, yalnız IANA səviyyəsindəki blok bölgüsündə rast gəlinir.",
  3: "Fəzanın səkkizdə biridir, LAN-da deyil, regional internet reyestrinin (RIR) səviyyəsindəki blok ölçüsüdür.",
  4: "Fəzanın on altıda biridir, LAN-da deyil, tarixən bir neçə köhnə A sinfi blokun cəmlənməsinə bərabər miqyasdır.",
  5: "Fəzanın otuz ikidə biridir, LAN-da deyil, nəhəng regional reyestrin bütöv payına bənzəyən miqyasdır.",
  6: "Fəzanın altmış dörddə biridir, LAN-da deyil, yalnız ən böyük operator bölgülərində rast gəlinən miqyasdır.",
  7: "Fəzanın yüz iyirmi səkkizdə biridir, LAN-da deyil, hələ də böyük operator blokunun ölçüsüdür.",
  8: "Köhnə 'A sinfi' termini məhz bu sərhədə uyğun gəlirdi; klassik ünvanlama 1993-cü ildə CIDR ilə ləğv edilib, bu gün /8 RIR-lərin ən böyük regional bloklarında görünür.",
  9: "Bir /8-in yarısıdır, böyük milli operatorun bütöv IPv4 payına bənzəyən miqyasdır.",
  10: "Bir /8-in dörddə biridir, böyük operator və ya çoxsaylı filialı olan qurumun regional payıdır.",
  11: "Regional operatora ayrılan tipik blok miqyasıdır.",
  12: "172.16.0.0/12 məhz bu ölçüdədir: RFC 1918-in orta ölçülü şəxsi blokunu tam əhatə edir.",
  13: "Orta ölçülü regional operatorun blokudur.",
  14: "Çoxsaylı filialı olan böyük qurumun bütöv daxili şəbəkəsini əhatə edən miqyasdır.",
  15: "198.18.0.0/15 məhz bu ölçüdədir: avadanlıq performans testləri üçün ayrılmış blokun ölçüsü budur.",
  16: "Köhnə 'B sinfi' termini məhz bu sərhədə uyğun gəlirdi; klassik ünvanlama 1993-cü ildə CIDR ilə ləğv edilib, bu gün bulud provayderlərinin (məsələn default VPC-lərin) sevimli ölçüsüdür.",
  17: "Bir /16-nın yarısıdır, böyük kampus şəbəkəsinin miqyasıdır.",
  18: "Bir /16-nın dörddə biridir, böyük data mərkəzi podunun tipik ölçüsüdür.",
  19: "Böyük kampus və ya data mərkəzi seqmentinin ölçüsüdür.",
  20: "Çoxsaylı VLAN-ı birləşdirən böyük ofis kompleksinin miqyasıdır.",
  21: "Orta ölçülü data mərkəzi seqmentinin tipik ölçüsüdür.",
  22: "Çoxmərtəbəli ofis binasının bütün şəbəkəsini əhatə edən miqyasdır.",
  23: "İki /24-ü birləşdirən blokdur, kiçik data mərkəzi seqmentində rast gəlinir.",
  24: "Köhnə 'C sinfi' termini məhz bu sərhədə uyğun gəlirdi; klassik ünvanlama 1993-cü ildə CIDR ilə ləğv edilib, amma insanlar bu gün də 'C sinfi' deyəndə adətən elə /24-ü nəzərdə tutur: ev və kiçik ofis şəbəkəsinin ənənəvi ölçüsüdür.",
  25: "Bir /24-ü ikiyə bölərkən alınan ölçüdür: VLAN seqmentləşdirməsində işlədilir.",
  26: "Filial ofisinin və ya kiçik şəbəkə seqmentinin tipik ölçüsüdür.",
  27: "Kiçik komanda seqmentinin və ya server rack-inin ölçüsüdür.",
  28: "Kiçik idarəetmə (management) VLAN-ının tipik ölçüsüdür.",
  29: "Provayderin firewall arxasındakı bir neçə serverə ictimai IP ayırarkən ən çox verdiyi blok ölçüsüdür.",
  30: "İki marşrutlaşdırıcı arasındakı nöqtə-nöqtə əlaqənin ənənəvi ölçüsüdür: /31 alternativ olsa da, bu hələ geniş yayılıb.",
  31: "Ünvan qənaəti üçün /30 əvəzinə getdikcə daha çox data mərkəzində seçilir.",
  32: "Marşrutlaşdırma cədvəlində tək bir hostu ayrıca qeyd etmək üçün işlədilir: host marşrutu adlanır.",
};

/** Extra search words beyond the wildcard and the hex mask — a synonym, an
 *  old classful name, a spec name — for the handful of prefixes visitors
 *  reach for by something other than the number. */
const IPV4_EXTRA_MATCH: Partial<Record<number, string[]>> = {
  0: ["default route", "default marsrut"],
  8: ["class a", "a sinfi"],
  16: ["class b", "b sinfi"],
  24: ["class c", "c sinfi"],
  31: ["point-to-point", "rfc 3021"],
  32: ["host route", "tek host"],
};

function countClause(prefix: number, total: string, usable: string): string {
  if (prefix === 32) {
    return `Bu blok tək bir ünvandır (${total}) və elə özü də host üçün istifadə olunur (${usable}): şəbəkə və yayım ayrımı mənasızdır, ona görə host sayı sıfır deyil, birdir`;
  }
  if (prefix === 31) {
    return `Bu blokda ${total} ünvan var və hər ikisi (${usable}) host üçün istifadə olunur, sıfır yox: RFC 3021 bu ölçünü xüsusi olaraq nöqtə-nöqtə əlaqə üçün ayırıb, şəbəkə/yayım konvensiyası tətbiq olunmur`;
  }
  return `Bu blokda ${total} ünvan var, bunlardan ${usable} host üçün istifadə oluna bilər (şəbəkə və yayım ünvanları çıxılıb)`;
}

function buildIpv4Rows(): ReferenceRow[] {
  const rows: ReferenceRow[] = [];
  for (let prefix = 32; prefix >= 0; prefix--) {
    const mask = maskFromPrefix(prefix);
    const wildcard = ~mask >>> 0;
    const total = 2 ** (32 - prefix);
    const usable = prefix === 32 ? 1 : prefix === 31 ? 2 : total - 2;
    const network = (DEMO_ADDRESS & mask) >>> 0;

    rows.push({
      term: `/${prefix}`,
      label: formatIpv4(mask),
      note: `${countClause(prefix, formatCount(total), formatCount(usable))}. ${IPV4_USAGE[prefix]}`,
      section: "ipv4",
      example: `${formatIpv4(network)}/${prefix}`,
      match: [formatIpv4(wildcard), toHexMask(mask), ...(IPV4_EXTRA_MATCH[prefix] ?? [])],
    });
  }
  return rows;
}

/* ---------- IPv6: hand-picked, still computed ---------- */

const SUPERSCRIPT_DIGITS: Record<string, string> = {
  "0": "⁰",
  "1": "¹",
  "2": "²",
  "3": "³",
  "4": "⁴",
  "5": "⁵",
  "6": "⁶",
  "7": "⁷",
  "8": "⁸",
  "9": "⁹",
};

function toSuperscript(value: number): string {
  return String(value)
    .split("")
    .map((digit) => SUPERSCRIPT_DIGITS[digit] ?? digit)
    .join("");
}

function formatBigCount(value: bigint): string {
  return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}

type Ipv6Spec = { prefix: number; usage: string; example: string; match?: string[] };

const IPV6_SPECS: Ipv6Spec[] = [
  {
    prefix: 128,
    usage: "tək bir IPv6 hostunu bildirən marşrutdur, IPv4-dəki /32-nin qarşılığıdır.",
    example: "2001:db8::1/128",
    match: ["single host", "host route", "tek host"],
  },
  {
    prefix: 127,
    usage:
      "hər ikisi host üçün istifadə olunur; RFC 6164 bu ölçünü marşrutlaşdırıcılar arası nöqtə-nöqtə əlaqə üçün tövsiyə edir, IPv4-dəki /31-in qarşılığıdır.",
    example: "2001:db8::/127",
    match: ["point-to-point", "rfc 6164"],
  },
  {
    prefix: 124,
    usage:
      "kiçik sınaq blokları və sənədləşmə nümunələrində rast gəlinən ən kiçik adi ayırma ölçülərindən biridir.",
    example: "2001:db8::/124",
    match: ["kicik blok"],
  },
  {
    prefix: 120,
    usage:
      "IPv4-dəki /24-ə bənzər miqyasdadır, amma SLAAC üçün yararsızdır: avtomatik ünvanlama məhz /64 tələb edir.",
    example: "2001:db8::/120",
    match: ["slaac yoxdur"],
  },
  {
    prefix: 112,
    usage:
      "son 16 biti IPv4-ün son oktetlərinə bənzər şəkildə əl ilə planlaşdırmaq üçün rahat ədəddir, amma bu da SLAAC-a uyğun deyil.",
    example: "2001:db8::/112",
  },
  {
    prefix: 96,
    usage:
      "son 32 bitə tam bir IPv4 ünvanını yerləşdirmək mümkündür; NAT64-ün tanınmış prefiksi 64:ff9b::/96 məhz bu ölçüdən istifadə edir.",
    example: "2001:db8::/96",
    match: ["nat64"],
  },
  {
    prefix: 80,
    usage: "/64 ilə /96 arasında qalan, real şəbəkələrdə demək olar rast gəlinməyən aralıq ölçüdür.",
    example: "2001:db8::/80",
  },
  {
    prefix: 64,
    usage:
      "bir IPv6 subnetinin standart ölçüsüdür; SLAAC (ünvanın özü-özünə konfiqurasiyası) məhz bu ölçünü tələb edir, daha uzun prefikslə işləmir.",
    example: "2001:db8::/64",
    match: ["slaac", "standart subnet"],
  },
  {
    prefix: 56,
    usage:
      "provayderin ev və kiçik ofis müştərisinə verdiyi tipik sayt ölçüsüdür, 256 ədəd /64 subnetinə bərabərdir.",
    example: "2001:db8:0:1200::/56",
    match: ["isp allocation", "sayt olcusu"],
  },
  {
    prefix: 48,
    usage:
      "RIR-lərin böyük təşkilata sayt ayırarkən tövsiyə etdiyi ənənəvi ölçüdür, 65 536 ədəd /64 subnetinə bərabərdir.",
    example: "2001:db8:1234::/48",
    match: ["site allocation"],
  },
  {
    prefix: 32,
    usage:
      "regional reyestrin (RIR) provayderə (LIR) verdiyi tipik minimum ayırma ölçüsüdür; sənədləşmə prefiksi 2001:db8::/32 də məhz bu ölçüdədir.",
    example: "2001:db8::/32",
    match: ["lir allocation"],
  },
  {
    prefix: 29,
    usage: "IANA-nın regional reyestrə (RIR) verdiyi ən kiçik standart blok ölçüsüdür.",
    example: "2001:db8::/29",
    match: ["iana allocation"],
  },
  {
    prefix: 16,
    usage: "regional reyestr səviyyəsində böyük tarixi bloklara aid miqyasdır.",
    example: "2001::/16",
  },
  {
    prefix: 3,
    usage:
      "2000::/3 bu gün marşrutlana bilən bütün qlobal unicast IPv6 fəzasıdır, demək olar bütün istifadə olunan IPv6 ünvanları elə bu blokun içindədir.",
    example: "2000::/3",
    match: ["global unicast", "2000::/3"],
  },
];

function buildIpv6Rows(): ReferenceRow[] {
  return IPV6_SPECS.map(({ prefix, usage, example, match }) => {
    const exponent = 128 - prefix;
    const count = 2n ** BigInt(exponent);
    return {
      term: `/${prefix}`,
      label: `2${toSuperscript(exponent)} ünvan`,
      note: `${formatBigCount(count)} ünvandan ibarətdir: ${usage}`,
      section: "ipv6",
      example,
      match,
    };
  });
}

/* ---------- reserved and special-purpose ranges ---------- */

const AYRILMIS_ROWS: ReferenceRow[] = [
  {
    term: "10.0.0.0/8",
    label: "RFC 1918 şəxsi şəbəkə",
    note: "16 777 216 ünvanlıq bu blok yönləndiricilər arxasında sərbəst təkrar istifadə olunan üç şəxsi diapazondan biridir və internetə birbaşa marşrutlanmır. Böyük korporativ şəbəkələrin ən çox seçdiyi RFC 1918 blokudur.",
    section: "ayrilmis",
    match: ["private", "şəxsi ipv4", "rfc1918"],
  },
  {
    term: "172.16.0.0/12",
    label: "RFC 1918 şəxsi şəbəkə",
    note: "172.16.0.0-dan 172.31.255.255-ə qədər 1 048 576 ünvanı əhatə edir: üç RFC 1918 blokunun ortancılıdır, Docker və bir çox konteyner şəbəkəsinin default aralığı məhz buradan seçilir.",
    section: "ayrilmis",
    match: ["private", "docker network", "rfc1918"],
  },
  {
    term: "192.168.0.0/16",
    label: "RFC 1918 şəxsi şəbəkə",
    note: "65 536 ünvanlıq bu blok ev marşrutlaşdırıcılarının fabrika ayarında ən çox rast gəlinən aralıqdır. Demək olar hər ev Wi-Fi şəbəkəsi 192.168.x.x ilə başlayır.",
    section: "ayrilmis",
    match: ["private", "home router", "rfc1918"],
  },
  {
    term: "100.64.0.0/10",
    label: "Operator NAT-ı (CGNAT)",
    note: "4 194 304 ünvanlıq bu blok mobil operatorların və bəzi internet provayderlərinin CGNAT arxasında müştərilərə verdiyi aralıqdır. 10.x və ya 192.168.x görmədən birbaşa bunu görürsənsə, provayder artıq öz NAT-ının arxasındadır.",
    section: "ayrilmis",
    match: ["cgnat", "carrier nat", "operator nat"],
  },
  {
    term: "127.0.0.0/8",
    label: "Loopback",
    note: "16 777 216 ünvanlıq bütöv blok cihazın öz-özünə göndərdiyi trafik üçün ayrılıb: təkcə 127.0.0.1 deyil, bu blokdakı istənilən ünvan da eyni effekti verir.",
    section: "ayrilmis",
    match: ["localhost", "loopback"],
  },
  {
    term: "169.254.0.0/16",
    label: "Link-local (APIPA)",
    note: "65 536 ünvanlıq bu blok DHCP serverdən cavab gəlmədikdə cihazın özünə təyin etdiyi ehtiyat ünvandır. Kabeli çıxarılmış və ya DHCP-siz şəbəkəyə qoşulan cihazın aldığı klassik ünvandır.",
    section: "ayrilmis",
    match: ["apipa", "dhcp cavab vermir"],
  },
  {
    term: "224.0.0.0/4",
    label: "Multicast",
    note: "268 435 456 ünvanlıq bu blok bir sorğunu eyni anda bir qrup qəbulediciyə göndərmək üçündür: OSPF, mDNS və IPTV yayımı bu diapazondan ünvan seçir.",
    section: "ayrilmis",
    match: ["multicast", "class d"],
  },
  {
    term: "240.0.0.0/4",
    label: "Ayrılmış (gələcək üçün)",
    note: "268 435 456 ünvanlıq bu blok tarixən 'gələcək istifadə üçün' ayrılıb (köhnə E sinfi) və bu gün də ictimai internetdə marşrutlanmır, praktik istifadəsi yoxdur.",
    section: "ayrilmis",
    match: ["class e", "reserved"],
  },
  {
    term: "255.255.255.255/32",
    label: "Məhdud yayım",
    note: "Tək ünvandır: yerli şəbəkə seqmentindəki bütün hostlara göndərilən yayım paketinin hədəfidir, marşrutlaşdırıcı bu paketi başqa seqmentə heç vaxt ötürmür.",
    section: "ayrilmis",
    match: ["broadcast", "yayim ünvanı"],
  },
  {
    term: "0.0.0.0/8",
    label: "'Bu şəbəkə'",
    note: "Bu blok 'hələ mənə ünvan verilməyib' vəziyyətini bildirir. DHCP sorğusu göndərən cihaz özünü mənbə kimi 0.0.0.0 ilə təqdim edir, hədəf ünvan kimi işlədilmir.",
    section: "ayrilmis",
    match: ["this network", "dhcp source"],
  },
  {
    term: "192.0.2.0/24",
    label: "TEST-NET-1",
    note: "256 ünvanlıq bu blok RFC 5737 ilə sənədləşmə və nümunə üçün ayrılıb. Heç vaxt internetdə marşrutlanmır, dərslikdə və ya kod nümunəsində təhlükəsiz işlətmək üçün nəzərdə tutulub.",
    section: "ayrilmis",
    match: ["documentation", "sened", "rfc5737"],
  },
  {
    term: "198.51.100.0/24",
    label: "TEST-NET-2",
    note: "256 ünvanlıq ikinci sənədləşmə blokudur: TEST-NET-1 ilə eyni məqsədi daşıyır, adətən iki fərqli tərəfi göstərən nümunələrdə (məsələn client və server) ayrı-ayrı işlədilir.",
    section: "ayrilmis",
    match: ["documentation", "sened", "rfc5737"],
  },
  {
    term: "203.0.113.0/24",
    label: "TEST-NET-3",
    note: "256 ünvanlıq üçüncü sənədləşmə blokudur: bu cədvəldəki bütün IPv4 nümunə ünvanları da məhz bu blokun içindən (203.0.113.45) seçilib.",
    section: "ayrilmis",
    match: ["documentation", "sened", "rfc5737"],
  },
  {
    term: "198.18.0.0/15",
    label: "Avadanlıq testi",
    note: "131 072 ünvanlıq bu blok RFC 2544 ilə şəbəkə avadanlığının performans testləri üçün ayrılıb. Real trafiklə qarışmasın deyə istehsalçı laboratoriyalarında işlədilir.",
    section: "ayrilmis",
    match: ["benchmark", "rfc2544"],
  },
  {
    term: "::1/128",
    label: "IPv6 loopback",
    note: "Tək ünvandır: IPv4-dəki 127.0.0.1-in IPv6 qarşılığıdır, cihazın öz-özünə göndərdiyi trafik üçündür.",
    section: "ayrilmis",
    match: ["localhost", "loopback"],
  },
  {
    term: "::/128",
    label: "Təyin olunmamış ünvan",
    note: "Tək ünvandır: cihazın hələ öz IPv6 ünvanını almadığı andakı mənbə ünvanıdır, IPv4-dəki 0.0.0.0-ın qarşılığıdır.",
    section: "ayrilmis",
    match: ["unspecified", "dhcpv6 solicit"],
  },
  {
    term: "fc00::/7",
    label: "Unique Local (ULA)",
    note: "IPv6-nın şəxsi ünvan qarşılığıdır. İnternetə marşrutlanmır, RFC 4193 təsadüfi seçilmiş qlobal ID ilə fd00::/8 alt blokunu praktikada standart edib.",
    section: "ayrilmis",
    match: ["private ipv6", "ula", "fd00"],
  },
  {
    term: "fe80::/10",
    label: "Link-local",
    note: "Hər IPv6 interfeysinə avtomatik təyin olunan yerli ünvandır: Neighbor Discovery kimi seqment-daxili tapşırıqlar üçündür, marşrutlaşdırıcı bunu heç vaxt ötürmür.",
    section: "ayrilmis",
    match: ["link local ipv6"],
  },
  {
    term: "ff00::/8",
    label: "Multicast",
    note: "IPv6-da yayım (broadcast) ünvanı ümumiyyətlə yoxdur. Onun yerini bu multicast blokundakı ünvanlar tutub, hər node bütün-node multicast qrupuna avtomatik qoşulur.",
    section: "ayrilmis",
    match: ["multicast ipv6", "broadcast yoxdur"],
  },
  {
    term: "2001:db8::/32",
    label: "Sənədləşmə",
    note: "RFC 3849 ilə sənədləşmə və nümunə üçün ayrılıb. Heç vaxt marşrutlanmır, bu cədvəldəki IPv6 sətirlərinin nümunə ünvanları da məhz bu blokdan seçilib.",
    section: "ayrilmis",
    match: ["documentation", "sened", "rfc3849"],
  },
  {
    term: "64:ff9b::/96",
    label: "NAT64",
    note: "RFC 6052-nin 'well-known prefix'-idir: NAT64 keçidi bir IPv4 ünvanını bu prefiksin son 32 bitinə yerləşdirərək IPv6-only cihaza IPv4-only hədəfə çatmaq imkanı verir.",
    section: "ayrilmis",
    match: ["nat64", "well-known prefix"],
  },
];

export const subnetCedveliRows: ReferenceRow[] = [
  ...buildIpv4Rows(),
  ...buildIpv6Rows(),
  ...AYRILMIS_ROWS,
];
